"use strict";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d");
const ui={chapter:document.querySelector("#chapter"),name:document.querySelector("#levelName"),instruction:document.querySelector("#instruction"),progress:document.querySelector("#progressFill"),demo:document.querySelector("#demoBtn"),picker:document.querySelector("#levelPicker"),toddler:document.querySelector("#toddlerBtn"),slow:document.querySelector("#slowBtn"),sound:document.querySelector("#soundBtn"),pause:document.querySelector("#pauseBtn"),restart:document.querySelector("#restartBtn"),pauseOverlay:document.querySelector("#pauseOverlay"),resume:document.querySelector("#resumeBtn"),finish:document.querySelector("#finishOverlay"),again:document.querySelector("#playAgainBtn")};
const chimes=[
 {name:"紅色 Do",color:"#ff667f",light:"#ffd3dc",freq:261.63,x:180},
 {name:"黃色 Re",color:"#ffd85f",light:"#fff3b0",freq:293.66,x:330},
 {name:"綠色 Mi",color:"#5bd28a",light:"#c8f7d8",freq:329.63,x:480},
 {name:"藍色 Sol",color:"#59bff2",light:"#c9efff",freq:392.00,x:630},
 {name:"紫色 La",color:"#9c78e8",light:"#e1d4ff",freq:440.00,x:780}
];
const levels=[
 {name:"彩霞問候",seq:[0,3]},{name:"雲朵應答",seq:[2,1]},{name:"星芽點點",seq:[4,0]},
 {name:"小風散步",seq:[0,2,3]},{name:"彩虹小橋",seq:[3,1,4]},{name:"露珠圓舞",seq:[2,4,0]},
 {name:"鳥羽旋律",seq:[1,3,2,0]},{name:"月光搖籃",seq:[4,2,1,3]},{name:"晴空飛行",seq:[0,3,4,2]},
 {name:"水晶合唱",seq:[2,0,4,1,3]},{name:"雲海迴聲",seq:[3,1,2,4,0]},{name:"天空音樂會",seq:[0,2,4,3,1]}
];
const chapters=["第一樂章 · 兩音問候","第二樂章 · 三音散步","第三樂章 · 彩虹合奏"];
const bg=new Image();bg.src="assets/cloud-chime-terrace.png";
let levelIndex=0,state="ready",input=[],active=-1,wrong=-1,toddler=false,slow=false,soundOn=true,paused=false,birdX=480,birdTarget=480,danceUntil=0,lastAction=performance.now(),timers=[],particles=[],audioCtx=null;
function current(){return levels[levelIndex]}
function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function later(fn,ms){const id=setTimeout(()=>{timers=timers.filter(x=>x!==id);fn()},ms);timers.push(id);return id}
function updateUI(){const chapterIndex=levelIndex<3?0:levelIndex<6?1:2;ui.chapter.textContent=chapters[chapterIndex];ui.name.textContent=`${levelIndex+1}/12 ${current().name}`;ui.progress.style.width=`${current().seq.length?input.length/current().seq.length*100:0}%`;ui.demo.textContent=toddler?"播放彩虹和弦":state==="showing"?"小鳥演奏中…":"聽小鳥示範";ui.demo.disabled=state==="showing"||state==="success";[...ui.picker.children].forEach((b,i)=>b.classList.toggle("active",i===levelIndex))}
function setup(){clearTimers();state=toddler?"free":"ready";input=[];active=-1;wrong=-1;danceUntil=0;lastAction=performance.now();ui.instruction.textContent=toddler?"自由敲風鈴，創作自己的音樂":"請小鳥先示範，再照順序敲風鈴";updateUI()}
function makePicker(){levels.forEach((l,i)=>{const b=document.createElement("button");b.innerHTML=`${i+1}<small>${l.name}</small>`;b.addEventListener("click",()=>{levelIndex=i;ui.finish.classList.add("hidden");setup()});ui.picker.appendChild(b)})}
function ensureAudio(){if(!soundOn)return null;audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function playTone(i,duration=.6){const ac=ensureAudio();if(!ac)return;const now=ac.currentTime,o1=ac.createOscillator(),o2=ac.createOscillator(),g=ac.createGain();o1.type="sine";o2.type="sine";o1.frequency.setValueAtTime(chimes[i].freq,now);o2.frequency.setValueAtTime(chimes[i].freq*2.01,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.075,now+.018);g.gain.exponentialRampToValueAtTime(.001,now+duration);o1.connect(g);o2.connect(g);g.connect(ac.destination);o1.start(now);o2.start(now);o1.stop(now+duration);o2.stop(now+duration)}
function spring(){const ac=ensureAudio();if(!ac)return;const now=ac.currentTime,o=ac.createOscillator(),g=ac.createGain();o.type="triangle";o.frequency.setValueAtTime(190,now);o.frequency.exponentialRampToValueAtTime(95,now+.2);g.gain.setValueAtTime(.04,now);g.gain.exponentialRampToValueAtTime(.001,now+.22);o.connect(g).connect(ac.destination);o.start(now);o.stop(now+.23)}
function sparkle(i,count=15){const x=chimes[i].x,y=315,colors=[chimes[i].light,"#fff","#ffe788"];for(let n=0;n<count;n++){const a=Math.random()*Math.PI*2,s=25+Math.random()*90;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-20,life:1,color:colors[n%3],r:2+Math.random()*4})}}
function ring(i,byBird=false){active=i;birdTarget=byBird?chimes[i].x:birdTarget;playTone(i);sparkle(i);later(()=>{if(active===i)active=-1},slow?650:420)}
function startDemo(){if(paused||state==="showing"||state==="success")return;if(toddler){chimes.forEach((_,i)=>later(()=>ring(i,true),i*130));return}clearTimers();state="showing";input=[];active=-1;wrong=-1;ui.instruction.textContent="看小鳥、聽音階…";updateUI();const gap=slow?1050:720;current().seq.forEach((v,i)=>later(()=>ring(v,true),250+i*gap));later(()=>{state="input";active=-1;ui.instruction.textContent="換你演奏囉！";updateUI()},350+current().seq.length*gap)}
function tap(i){if(paused)return;lastAction=performance.now();if(toddler){ring(i);return}if(state!=="input")return;ring(i);const expected=current().seq[input.length];if(i===expected){input.push(i);updateUI();if(input.length===current().seq.length)success()}else{wrong=i;state="retry";spring();ui.instruction.textContent="沒關係，再聽小鳥唱一次";updateUI();later(()=>{wrong=-1;state="ready";startDemo()},slow?1200:800)}}
function success(){state="success";danceUntil=performance.now()+(slow?3000:1900);ui.instruction.textContent="演奏成功！小鳥跳舞囉！";for(let i=0;i<5;i++)later(()=>sparkle(i,24),i*90);[0,2,4].forEach((v,i)=>later(()=>playTone(v,.8),i*160));updateUI();later(advance,slow?3200:2150)}
function advance(){if(levelIndex===11){state="ready";ui.finish.classList.remove("hidden");return}levelIndex++;setup()}
function setPaused(v){paused=v;ui.pauseOverlay.classList.toggle("hidden",!v);ui.pause.textContent=v?"繼續":"暫停";if(v){clearTimers();active=-1;if(state==="showing"||state==="retry"||state==="success"){state="ready";input=[]}}else{ui.instruction.textContent=toddler?"自由敲風鈴，創作自己的音樂":state==="input"?"換你演奏囉！":"請小鳥先示範，再照順序敲風鈴";updateUI()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*540/r.height}}
canvas.addEventListener("pointerdown",e=>{const p=point(e);for(let i=0;i<chimes.length;i++)if(Math.abs(p.x-chimes[i].x)<62&&p.y>190&&p.y<465){tap(i);break}});
ui.demo.addEventListener("click",startDemo);ui.toddler.addEventListener("click",()=>{toddler=!toddler;ui.toddler.textContent=`幼幼模式：${toddler?"開":"關"}`;ui.toddler.setAttribute("aria-pressed",String(toddler));setup()});ui.slow.addEventListener("click",()=>{slow=!slow;ui.slow.textContent=`慢慢玩：${slow?"開":"關"}`;ui.slow.setAttribute("aria-pressed",String(slow))});ui.sound.addEventListener("click",()=>{soundOn=!soundOn;ui.sound.textContent=`音效：${soundOn?"開":"關"}`;ui.sound.setAttribute("aria-pressed",String(soundOn))});ui.pause.addEventListener("click",()=>setPaused(!paused));ui.resume.addEventListener("click",()=>setPaused(false));ui.restart.addEventListener("click",setup);ui.again.addEventListener("click",()=>{ui.finish.classList.add("hidden");levelIndex=0;setup()});document.addEventListener("visibilitychange",()=>{if(document.hidden)setPaused(true)});window.addEventListener("blur",()=>setPaused(true));
function drawBird(t){birdX+=(birdTarget-birdX)*.08;const dance=t<danceUntil?Math.sin(t*.035)*22:0,bob=Math.sin(t/180)*4;ctx.save();ctx.translate(birdX+dance,125+bob);ctx.fillStyle="#60c6e5";ctx.beginPath();ctx.ellipse(0,0,35,27,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#83d9ee";ctx.beginPath();ctx.ellipse(-24,7,25,12,-.6,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(13,-7,11,0,Math.PI*2);ctx.fill();ctx.fillStyle="#283358";ctx.beginPath();ctx.arc(16,-8,4,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ff9b4a";ctx.beginPath();ctx.moveTo(31,-4);ctx.lineTo(47,2);ctx.lineTo(31,8);ctx.closePath();ctx.fill();ctx.restore()}
function crystalPath(x,y,w,h){ctx.beginPath();ctx.moveTo(x,y-h/2);ctx.lineTo(x+w/2,y-h*.2);ctx.lineTo(x+w*.38,y+h*.42);ctx.lineTo(x,y+h/2);ctx.lineTo(x-w*.38,y+h*.42);ctx.lineTo(x-w/2,y-h*.2);ctx.closePath()}
function drawChime(c,i,t){const lit=active===i,pulse=(Math.sin(t/170)+1)/2,wobble=lit?Math.sin(t*.08)*.08:wrong===i?Math.sin(t*.12)*.13:0;ctx.save();ctx.translate(c.x,0);ctx.strokeStyle="#866c55";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,160);ctx.lineTo(0,245);ctx.stroke();ctx.translate(0,315);ctx.rotate(wobble);ctx.shadowColor=lit?c.light:"rgba(63,66,130,.25)";ctx.shadowBlur=lit?35:10;crystalPath(0,0,82,135);ctx.fillStyle=lit?c.light:c.color;ctx.globalAlpha=.92;ctx.fill();ctx.strokeStyle="rgba(255,255,255,.75)";ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=1;ctx.strokeStyle="#775f55";ctx.beginPath();ctx.moveTo(0,68);ctx.lineTo(0,105);ctx.stroke();ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(0,112,23,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 18px sans-serif";ctx.textAlign="center";ctx.fillText(["Do","Re","Mi","Sol","La"][i],0,7);if((state==="input"&&i===current().seq[input.length]&&t-lastAction>5000)||toddler){ctx.strokeStyle=`rgba(255,246,154,${.35+pulse*.5})`;ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,68+pulse*6,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function draw(t){requestAnimationFrame(draw);if(paused)return;ctx.clearRect(0,0,960,540);if(bg.complete)ctx.drawImage(bg,0,0,960,540);else{ctx.fillStyle="#b9e5ff";ctx.fillRect(0,0,960,540)}ctx.strokeStyle="#8b6c51";ctx.lineWidth=13;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(110,160);ctx.quadraticCurveTo(480,137,850,160);ctx.stroke();chimes.forEach((c,i)=>drawChime(c,i,t));drawBird(t);particles.forEach(p=>{p.x+=p.vx/60;p.y+=p.vy/60;p.vy+=.55;p.life-=.018;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0)}
makePicker();setup();requestAnimationFrame(draw);
