(()=>{"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height;
const ui={start:document.getElementById("startPanel"),stage:document.getElementById("stagePanel"),pause:document.getElementById("pausePanel"),finish:document.getElementById("finishPanel"),stageTitle:document.getElementById("stageTitle"),stageHelp:document.getElementById("stageHelp"),stageIcon:document.getElementById("stageIcon"),stageText:document.getElementById("stageText"),roundText:document.getElementById("roundText"),progress:document.getElementById("progressBar"),startBtn:document.getElementById("startBtn"),stageBtn:document.getElementById("stageBtn"),resumeBtn:document.getElementById("resumeBtn"),replayBtn:document.getElementById("replayBtn"),restartBtn:document.getElementById("restartBtn"),toddlerBtn:document.getElementById("toddlerBtn"),slowBtn:document.getElementById("slowBtn"),hintBtn:document.getElementById("hintBtn"),soundBtn:document.getElementById("soundBtn"),pauseBtn:document.getElementById("pauseBtn")};
const stages=[{name:"第一階段：看圖案",title:"看圖案送包裹",help:"兔子、鳥兒、星星，包裹要送到相同圖案的浮島。",icon:"🖼️"},{name:"第二階段：雙條件",title:"同時看顏色和圖案",help:"兩個條件都相同，才是正確目的地。",icon:"🔎"},{name:"第三階段：照順序",title:"照任務卡的順序配送",help:"先找下一個包裹，再送到完全相同的目的地。",icon:"📋"}];
const C={r:"#ff7587",b:"#5dc8f1",y:"#ffe064",g:"#69dca2",p:"#a985ec"},places=["rabbit","bird","star"],placeNames={rabbit:"兔子浮島",bird:"鳥兒郵局",star:"星星塔"};
const sets=[[['rabbit','r'],['bird','b'],['star','y']],[['rabbit','b'],['bird','r'],['rabbit','g']],[['star','p'],['bird','y'],['star','b']],[['rabbit','g'],['star','r'],['bird','p']]];
const missions=[];for(let i=0;i<4;i++)missions.push({stage:0,items:[{symbol:places[i%3],color:'y'}],order:[0]});for(let i=0;i<4;i++)missions.push({stage:1,items:sets[i].map(([symbol,color])=>({symbol,color})),order:[0,1,2]});missions.push({stage:2,items:sets[1].slice(0,2).map(([symbol,color])=>({symbol,color})),dests:sets[1].map(([symbol,color])=>({symbol,color})),order:[1,0]},{stage:2,items:sets[2].map(([symbol,color])=>({symbol,color})),order:[2,0,1]},{stage:2,items:sets[3].map(([symbol,color])=>({symbol,color})),order:[1,2,0]},{stage:2,items:sets[0].map(([symbol,color])=>({symbol,color})),order:[2,1,0],final:true});
const DX=[205,480,755],DY=210,PX=[305,480,655],PY=438;
let state,last=performance.now(),audioCtx=null;
function reset(){state={mode:"ready",index:0,selected:null,delivered:new Set(),orderPos:0,toddler:false,slow:false,hint:false,sound:true,anim:null,shake:null,message:"",messageT:0,celebrate:0,inactive:0,sparkles:[]};prepare();updateHud()}
function mission(){return missions[state.index]}function prepare(){state.selected=null;state.delivered=new Set();state.orderPos=0;state.anim=null;state.shake=null;state.message="";state.messageT=0;state.celebrate=0;state.inactive=0}
function tone(freq,d=.12,type="sine",gain=.05){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(_){}}
function hidePanels(){[ui.start,ui.stage,ui.pause,ui.finish].forEach(p=>{p.classList.remove("show");p.setAttribute("aria-hidden","true")})}function showStage(){state.mode="stage";const s=stages[Math.floor(state.index/4)];ui.stageTitle.textContent=s.title;ui.stageHelp.textContent=s.help;ui.stageIcon.textContent=s.icon;hidePanels();ui.stage.classList.add("show");ui.stage.setAttribute("aria-hidden","false")}
function begin(){reset();hidePanels();showStage()}function playStage(){hidePanels();state.mode="playing";last=performance.now();canvas.focus();tone(523,.1);setTimeout(()=>tone(659,.13),90)}function setPaused(v,automatic=false){if(!["playing","paused"].includes(state.mode))return;state.mode=v?"paused":"playing";ui.pauseBtn.textContent=v?"▶ 繼續":"⏸ 暫停";if(v){hidePanels();ui.pause.classList.add("show");ui.pause.setAttribute("aria-hidden","false");ui.pause.querySelector("p").textContent=automatic?"畫面暫停了，飛船會等你回來。":"準備好再繼續配送。"}else{hidePanels();last=performance.now();canvas.focus()}}
function updateHud(){ui.stageText.textContent=stages[Math.min(2,Math.floor(state.index/4))].name;ui.roundText.textContent=`${Math.min(12,state.index+1)} / 12`;ui.progress.style.width=`${state.index/12*100}%`}
function nextRequired(){const m=mission();return m.stage===2?m.order[state.orderPos]:m.items.map((_,i)=>i).find(i=>!state.delivered.has(i))}
function selectPackage(i){if(state.mode!=="playing"||state.anim||state.celebrate||state.delivered.has(i))return;state.inactive=0;const m=mission();if(m.stage===2&&i!==nextRequired()){friendly("package",i,"先送任務卡上的下一箱喔");return}state.selected=i;tone(460,.07,"triangle",.03)}
function destinationMatches(item,dest){const m=mission();return!!item&&!!dest&&(m.stage===0?item.symbol===dest.symbol:item.symbol===dest.symbol&&item.color===dest.color)}
function destinations(){const m=mission();if(m.stage===0)return places.map(symbol=>({symbol,color:'neutral'}));return(m.dests||m.items).map(x=>({...x}))}
function chooseDestination(d){if(state.mode!=="playing"||state.anim||state.celebrate)return;state.inactive=0;const m=mission(),dest=destinations()[d];let pi=state.selected;if(state.toddler){const required=m.stage===2?nextRequired():m.items.findIndex((it,i)=>!state.delivered.has(i)&&destinationMatches(it,dest));if(required<0){friendly("dest",d,"這座浮島暫時沒有包裹喔");return}pi=required}else if(pi===null){friendly("dest",d,"先選一個包裹");return}const item=m.items[pi];if(!destinationMatches(item,dest)){friendly("dest",d,`${placeNames[item.symbol]}才是這箱的家`);return}const from={x:PX[pi]??480,y:PY},to={x:DX[d],y:DY};state.anim={pi,d,t:0,dur:state.slow?1.25:.78,from,to};state.selected=null;tone(520,.08,"triangle",.035)}
function friendly(kind,i,text){state.shake={kind,i,t:.5};state.message=text;state.messageT=1.6;tone(190,.15,"sine",.035)}
function delivered(){const a=state.anim;state.anim=null;state.delivered.add(a.pi);if(mission().stage===2)state.orderPos++;emit(a.to.x,a.to.y);tone(700,.12);setTimeout(()=>tone(880,.14),90);if(state.delivered.size===mission().items.length)state.celebrate=.01}
function nextMission(){state.index++;if(state.index>=missions.length){state.mode="finished";ui.progress.style.width="100%";hidePanels();ui.finish.classList.add("show");ui.finish.setAttribute("aria-hidden","false");tone(659,.15);setTimeout(()=>tone(880,.2),120);setTimeout(()=>tone(1047,.27),270);return}prepare();updateHud();if(state.index%4===0)showStage()}
function emit(x,y){for(let i=0;i<22;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*110;state.sparkles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.85,size:3+Math.random()*5,color:["#fff16d","#ff91bb","#70dda8","#8fe5ff"][i%4]})}}
function update(dt){if(state.mode!=="playing")return;state.inactive+=dt;if(state.toddler&&state.inactive>3)state.hint=true;if(state.anim){state.anim.t+=dt;if(state.anim.t>=state.anim.dur)delivered()}if(state.shake){state.shake.t-=dt;if(state.shake.t<=0)state.shake=null}state.messageT=Math.max(0,state.messageT-dt);if(state.celebrate>0){state.celebrate+=dt/(state.slow?2.6:1.7);if(state.celebrate>=1){state.celebrate=0;nextMission()}}for(const p of state.sparkles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=40*dt;p.life-=dt}state.sparkles=state.sparkles.filter(p=>p.life>0)}
function drawIcon(symbol,x,y,s=1,color="#315b75"){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle=color;ctx.strokeStyle=color;ctx.lineWidth=4;if(symbol==="rabbit"){ctx.beginPath();ctx.ellipse(-10,-22,8,20,-.25,0,Math.PI*2);ctx.ellipse(10,-22,8,20,.25,0,Math.PI*2);ctx.arc(0,5,22,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(-7,1,3,0,Math.PI*2);ctx.arc(7,1,3,0,Math.PI*2);ctx.fill()}else if(symbol==="bird"){ctx.beginPath();ctx.ellipse(0,5,25,18,-.15,0,Math.PI*2);ctx.arc(15,-8,14,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ffb84d";ctx.beginPath();ctx.moveTo(28,-8);ctx.lineTo(42,-3);ctx.lineTo(28,2);ctx.fill()}else{ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?12:28,px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}ctx.restore()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#66cbf6");g.addColorStop(.7,"#e1f8ff");g.addColorStop(1,"#fff0b6");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.42)";for(let i=0;i<7;i++){const x=25+i*165,y=90+(i%2)*65;ctx.beginPath();ctx.arc(x,y,24,0,Math.PI*2);ctx.arc(x+28,y+4,32,0,Math.PI*2);ctx.arc(x+58,y+8,22,0,Math.PI*2);ctx.fill()}}
function drawDestination(d,i){const dest=destinations()[i],shake=state.shake?.kind==="dest"&&state.shake.i===i?Math.sin(state.shake.t*65)*7:0,hint=state.hint&&((state.selected!==null&&destinationMatches(mission().items[state.selected],dest))||(state.toddler&&destinationMatches(mission().items[nextRequired()],dest)));ctx.save();ctx.translate(DX[i]+shake,DY);ctx.shadowColor=hint?"#ffe56c":"rgba(39,91,123,.22)";ctx.shadowBlur=hint?25:12;ctx.fillStyle="#8bdc91";ctx.strokeStyle="#fff";ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,35,104,31,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#a37b5b";ctx.beginPath();ctx.moveTo(-80,47);ctx.quadraticCurveTo(0,128,80,47);ctx.closePath();ctx.fill();ctx.fillStyle=dest.color==='neutral'?"#fff":C[dest.color];ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-45,-48,90,76,17);ctx.fill();ctx.stroke();drawIcon(dest.symbol,0,-10,.65);ctx.fillStyle="#315d76";ctx.font="800 15px sans-serif";ctx.textAlign="center";ctx.fillText(placeNames[dest.symbol],0,86);ctx.restore()}
function drawPackage(item,i){if(state.delivered.has(i)||state.anim?.pi===i)return;const selected=state.selected===i,required=nextRequired()===i,hint=state.hint&&required,shake=state.shake?.kind==="package"&&state.shake.i===i?Math.sin(state.shake.t*65)*7:0;ctx.save();ctx.translate(PX[i]+shake,PY);ctx.shadowColor=hint?"#ffe368":"rgba(35,77,103,.24)";ctx.shadowBlur=hint?24:10;ctx.fillStyle=mission().stage===0?"#f4cb86":C[item.color];ctx.strokeStyle=selected?"#ffd447":"#fff";ctx.lineWidth=selected?8:5;ctx.beginPath();ctx.roundRect(-58,-49,116,92,15);ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(113,75,44,.55)";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-46);ctx.lineTo(0,42);ctx.moveTo(-55,-12);ctx.lineTo(55,-12);ctx.stroke();drawIcon(item.symbol,0,16,.55);ctx.fillStyle="#315d76";ctx.font="800 17px sans-serif";ctx.textAlign="center";ctx.fillText(String(i+1),0,69);ctx.restore()}
function drawMissionCard(){const m=mission();ctx.save();ctx.fillStyle="rgba(255,255,255,.9)";ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(20,77,m.stage===2?255:205,76,20);ctx.fill();ctx.stroke();ctx.fillStyle="#37637d";ctx.font="800 15px sans-serif";ctx.fillText(m.stage===0?"看包裹圖案":m.stage===1?"顏色＋圖案都要相同":"任務順序",37,102);if(m.stage===2){m.order.forEach((pi,j)=>{ctx.globalAlpha=j<state.orderPos?0.3:1;ctx.fillStyle=j===state.orderPos?"#ffe264":"#dff4fb";ctx.beginPath();ctx.arc(62+j*60,127,20,0,Math.PI*2);ctx.fill();drawIcon(m.items[pi].symbol,62+j*60,127,.35);if(j<m.order.length-1){ctx.fillStyle="#6e94a9";ctx.font="800 18px sans-serif";ctx.fillText("→",86+j*60,133)}})}ctx.restore()}
function drawPlane(){if(!state.anim)return;const a=state.anim,q=Math.min(1,a.t/a.dur),e=1-Math.pow(1-q,3),x=a.from.x+(a.to.x-a.from.x)*e,y=a.from.y+(a.to.y-a.from.y)*e-95*Math.sin(q*Math.PI);ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(a.to.y-a.from.y,a.to.x-a.from.x)*.2);ctx.fillStyle="#75d99a";ctx.strokeStyle="#2d7780";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-42,3);ctx.quadraticCurveTo(0,-27,46,0);ctx.quadraticCurveTo(0,17,-42,3);ctx.fill();ctx.stroke();ctx.fillStyle="#ffe063";ctx.fillRect(-12,-3,25,18);ctx.restore()}
function drawFinalRecap(){if(!mission().final)return;ctx.save();ctx.globalAlpha=.55;ctx.strokeStyle="#ff7ca7";ctx.lineWidth=5;ctx.beginPath();ctx.arc(870,112,28,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(80,210,24,0,Math.PI*2);ctx.arc(105,215,29,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#69cef2";ctx.beginPath();ctx.moveTo(65,330);ctx.lineTo(130,330);ctx.stroke();ctx.strokeStyle="#ffd85a";ctx.beginPath();ctx.moveTo(785,338);ctx.lineTo(850,338);ctx.stroke();ctx.restore()}
function drawSparkles(){for(const p of state.sparkles){ctx.globalAlpha=Math.max(0,p.life/.85);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function render(){drawBackground();drawFinalRecap();destinations().forEach(drawDestination);mission().items.forEach(drawPackage);drawMissionCard();drawPlane();drawSparkles();if(state.messageT>0){ctx.save();ctx.fillStyle="rgba(255,255,255,.94)";ctx.strokeStyle="#ffd65b";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(280,327,400,52,20);ctx.fill();ctx.stroke();ctx.fillStyle="#315d76";ctx.font="800 18px sans-serif";ctx.textAlign="center";ctx.fillText(state.message,480,360);ctx.restore()}}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}function hit(p,x,y,w,h){return Math.abs(p.x-x)<w/2&&Math.abs(p.y-y)<h/2}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const p=point(e);for(let i=0;i<mission().items.length;i++)if(hit(p,PX[i],PY,125,115)){if(!state.toddler)selectPackage(i);return}for(let i=0;i<3;i++)if(hit(p,DX[i],DY,180,180)){chooseDestination(i);return}});
window.addEventListener("keydown",e=>{if(/^Digit[123]$|^Numpad[123]$/.test(e.code))selectPackage(Number(e.code.slice(-1))-1);const map={KeyQ:0,KeyW:1,KeyE:2};if(e.code in map)chooseDestination(map[e.code]);if(e.code==="KeyP")setPaused(state.mode==="playing")});
ui.startBtn.addEventListener("click",begin);ui.stageBtn.addEventListener("click",playStage);ui.resumeBtn.addEventListener("click",()=>setPaused(false));ui.replayBtn.addEventListener("click",begin);ui.restartBtn.addEventListener("click",()=>{reset();hidePanels();ui.start.classList.add("show");ui.start.setAttribute("aria-hidden","false");ui.pauseBtn.textContent="⏸ 暫停"});ui.pauseBtn.addEventListener("click",()=>setPaused(state.mode==="playing"));ui.toddlerBtn.addEventListener("click",()=>{state.toddler=!state.toddler;state.selected=null;state.inactive=0;ui.toddlerBtn.setAttribute("aria-pressed",String(state.toddler));ui.toddlerBtn.textContent=state.toddler?"👶 幼幼：開":"👶 幼幼模式"});ui.slowBtn.addEventListener("click",()=>{state.slow=!state.slow;ui.slowBtn.setAttribute("aria-pressed",String(state.slow));ui.slowBtn.textContent=state.slow?"🐢 慢速：開":"🐢 慢慢玩"});ui.hintBtn.addEventListener("click",()=>{state.hint=!state.hint;state.inactive=0;ui.hintBtn.setAttribute("aria-pressed",String(state.hint));ui.hintBtn.textContent=state.hint?"✨ 提示：開":"✨ 提示"});ui.soundBtn.addEventListener("click",()=>{state.sound=!state.sound;ui.soundBtn.setAttribute("aria-pressed",String(state.sound));ui.soundBtn.textContent=`${state.sound?"🔊":"🔇"} 音效：${state.sound?"開":"關"}`;if(state.sound)tone(620,.09)});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")setPaused(true,true)});window.addEventListener("blur",()=>{if(state.mode==="playing")setPaused(true,true)});reset();requestAnimationFrame(loop);
})();
