(()=>{"use strict";const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height,bg=new Image();bg.src="assets/cloud_island_storybook_bg.png";
const ui={start:document.getElementById("startPanel"),pause:document.getElementById("pausePanel"),mode:document.getElementById("modeText"),pop:document.getElementById("popText"),startBtn:document.getElementById("startBtn"),resumeBtn:document.getElementById("resumeBtn"),restartBtn:document.getElementById("restartBtn"),freeBtn:document.getElementById("freeBtn"),questBtn:document.getElementById("questBtn"),slowBtn:document.getElementById("slowBtn"),soundBtn:document.getElementById("soundBtn"),pauseBtn:document.getElementById("pauseBtn")};
const colors=["#ff8fa5","#ffbd67","#ffe56e","#76dda6","#69cef2","#ad91ef"],names=["粉紅","橙色","黃色","綠色","藍色","紫色"],spots=[[170,190],[390,175],[650,190],[810,300],[540,335],[260,345]];let state,last=performance.now(),audioCtx=null;
function reset(){state={mode:"ready",playMode:"free",paused:false,slow:false,sound:true,pops:0,clouds:spots.map((p,i)=>({x:p[0],y:p[1],baseY:p[1],color:i,scale:1,wobble:Math.random()*6.28})),particles:[],rings:[],quest:[],questPos:0,message:"",messageT:0};newQuest();updateUI()}
function tone(freq,d=.1,type="sine",gain=.045){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(_){}}
function newQuest(){const pool=[0,1,2,3,4,5],len=3+Math.floor(state.pops/8)%3;state.quest=[];for(let i=0;i<len;i++){const j=Math.floor(Math.random()*pool.length);state.quest.push(pool.splice(j,1)[0])}state.questPos=0}
function updateUI(){ui.pop.textContent=String(state.pops);ui.freeBtn.setAttribute("aria-pressed",String(state.playMode==="free"));ui.questBtn.setAttribute("aria-pressed",String(state.playMode==="quest"));ui.mode.textContent=state.playMode==="free"?"自由啵啵：想點哪朵都可以":`彩虹任務：第 ${state.questPos+1} 個，共 ${state.quest.length} 個`}
function start(){state.mode="playing";ui.start.classList.remove("show");canvas.focus();tone(523,.1);setTimeout(()=>tone(659,.12),80)}function hidePause(){ui.pause.classList.remove("show");ui.pause.setAttribute("aria-hidden","true")}
function pause(v,automatic=false){if(state.mode!=="playing"&&state.mode!=="paused")return;state.mode=v?"paused":"playing";ui.pauseBtn.textContent=v?"▶ 繼續":"⏸ 暫停";if(v){ui.pause.classList.add("show");ui.pause.setAttribute("aria-hidden","false");ui.pause.querySelector("p").textContent=automatic?"畫面暫停了，雲朵會等你回來。":"準備好再繼續玩。"}else{hidePause();last=performance.now();canvas.focus()}}
function burst(c){const kinds=["star","candy","petal"],kind=kinds[state.pops%3];for(let i=0;i<34;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*150;state.particles.push({x:c.x,y:c.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-35,life:1.2+Math.random()*.6,size:4+Math.random()*7,color:colors[(c.color+i)%6],kind,rot:Math.random()*6.28})}state.rings.push({x:c.x,y:c.y,r:28,life:.65})}
function popCloud(i){if(state.mode!=="playing")return;const c=state.clouds[i];if(state.playMode==="quest"&&c.color!==state.quest[state.questPos]){c.scale=.9;state.message=`找找 ${names[state.quest[state.questPos]]} 的雲朵`;state.messageT=1.3;tone(190,.16,"sine",.035);return}c.scale=1.22;state.pops++;burst(c);tone([420,480,540,600,680,760][c.color],.09,"sine",.05);if(state.playMode==="free")c.color=(c.color+1+Math.floor(Math.random()*5))%6;else{state.questPos++;if(state.questPos>=state.quest.length){state.message="彩虹任務完成！";state.messageT=1.7;tone(880,.16);setTimeout(()=>tone(1040,.2),100);newQuest()}}updateUI()}
function update(dt){if(state.mode!=="playing")return;const k=state.slow?0.55:1;for(const c of state.clouds){c.wobble+=dt*.8*k;c.y=c.baseY+Math.sin(c.wobble)*4;c.scale+=(1-c.scale)*Math.min(1,dt*7*k)}for(const p of state.particles){p.x+=p.vx*dt*k;p.y+=p.vy*dt*k;p.vy+=90*dt*k;p.rot+=dt*3;p.life-=dt*k}state.particles=state.particles.filter(p=>p.life>0);for(const r of state.rings){r.r+=100*dt*k;r.life-=dt*k}state.rings=state.rings.filter(r=>r.life>0);state.messageT=Math.max(0,state.messageT-dt*k)}
function drawBg(){if(bg.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,W,H);else{const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#67cbf6");g.addColorStop(1,"#eafaff");ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}ctx.fillStyle="rgba(42,114,158,.08)";ctx.fillRect(0,0,W,H)}
function drawCloud(c,i){ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.scale,c.scale);ctx.shadowColor=colors[c.color];ctx.shadowBlur=22;ctx.fillStyle=colors[c.color];ctx.strokeStyle="rgba(255,255,255,.94)";ctx.lineWidth=6;ctx.beginPath();ctx.arc(-43,9,35,0,Math.PI*2);ctx.arc(-12,-18,45,0,Math.PI*2);ctx.arc(32,-7,40,0,Math.PI*2);ctx.arc(47,20,30,0,Math.PI*2);ctx.arc(0,20,57,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowColor="transparent";ctx.fillStyle="#315468";ctx.beginPath();ctx.arc(-16,5,4,0,Math.PI*2);ctx.arc(17,5,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#315468";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,12,12,.1,Math.PI-.1);ctx.stroke();if(state.playMode==="quest"&&c.color===state.quest[state.questPos]){ctx.strokeStyle="#ffe15d";ctx.lineWidth=7;ctx.shadowColor="#fff18c";ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(0,5,76,58,0,0,Math.PI*2);ctx.stroke()}ctx.fillStyle="rgba(255,255,255,.9)";ctx.font="800 16px sans-serif";ctx.textAlign="center";ctx.fillText(String(i+1),0,67);ctx.restore()}
function drawParticle(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.globalAlpha=Math.min(1,p.life/.4);ctx.fillStyle=p.color;ctx.strokeStyle="rgba(255,255,255,.75)";ctx.lineWidth=2;ctx.beginPath();if(p.kind==="star"){for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?p.size*.45:p.size,px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}else if(p.kind==="candy"){ctx.roundRect(-p.size,-p.size*.55,p.size*2,p.size*1.1,p.size*.4);ctx.moveTo(-p.size,0);ctx.lineTo(-p.size*1.7,-p.size*.7);ctx.lineTo(-p.size*1.7,p.size*.7);ctx.closePath();ctx.moveTo(p.size,0);ctx.lineTo(p.size*1.7,-p.size*.7);ctx.lineTo(p.size*1.7,p.size*.7);ctx.closePath()}else{ctx.ellipse(0,0,p.size*.55,p.size,0,0,Math.PI*2)}ctx.fill();ctx.stroke();ctx.restore()}
function drawQuest(){if(state.playMode!=="quest")return;ctx.save();ctx.fillStyle="rgba(255,255,255,.92)";ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(250,76,460,74,22);ctx.fill();ctx.stroke();ctx.fillStyle="#315d77";ctx.font="800 16px sans-serif";ctx.fillText("照順序點：",275,106);state.quest.forEach((c,i)=>{ctx.globalAlpha=i<state.questPos?0.25:1;ctx.fillStyle=colors[c];ctx.beginPath();ctx.arc(410+i*56,113,19,0,Math.PI*2);ctx.fill();if(i===state.questPos){ctx.strokeStyle="#ffd33f";ctx.lineWidth=6;ctx.stroke()}});ctx.restore()}
function render(){drawBg();drawQuest();state.clouds.forEach(drawCloud);state.rings.forEach(r=>{ctx.save();ctx.globalAlpha=r.life/.65;ctx.strokeStyle="#fff7a5";ctx.lineWidth=7;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();ctx.restore()});state.particles.forEach(drawParticle);if(state.messageT>0){ctx.save();ctx.fillStyle="rgba(255,255,255,.94)";ctx.strokeStyle="#ffd65b";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(285,465,390,48,19);ctx.fill();ctx.stroke();ctx.fillStyle="#315d76";ctx.font="800 18px sans-serif";ctx.textAlign="center";ctx.fillText(state.message,480,496);ctx.restore()}}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}function hit(p){let best=-1,dist=Infinity;state.clouds.forEach((c,i)=>{const d=Math.hypot(p.x-c.x,p.y-c.y);if(d<80&&d<dist){best=i;dist=d}});return best}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const i=hit(point(e));if(i>=0)popCloud(i)});window.addEventListener("keydown",e=>{if(/^Digit[1-6]$|^Numpad[1-6]$/.test(e.code))popCloud(Number(e.code.slice(-1))-1);if(e.code==="KeyP")pause(state.mode==="playing")});ui.startBtn.addEventListener("click",start);ui.resumeBtn.addEventListener("click",()=>pause(false));ui.pauseBtn.addEventListener("click",()=>pause(state.mode==="playing"));ui.restartBtn.addEventListener("click",()=>{reset();hidePause();ui.start.classList.add("show");ui.pauseBtn.textContent="⏸ 暫停"});ui.freeBtn.addEventListener("click",()=>{state.playMode="free";state.message="自由啵啵！想點哪朵都可以";state.messageT=1.3;updateUI()});ui.questBtn.addEventListener("click",()=>{state.playMode="quest";state.clouds.forEach((c,i)=>c.color=i);newQuest();state.message="照著上方顏色點雲朵";state.messageT=1.3;updateUI()});ui.slowBtn.addEventListener("click",()=>{state.slow=!state.slow;ui.slowBtn.setAttribute("aria-pressed",String(state.slow));ui.slowBtn.textContent=state.slow?"🐢 慢速：開":"🐢 慢慢玩"});ui.soundBtn.addEventListener("click",()=>{state.sound=!state.sound;ui.soundBtn.setAttribute("aria-pressed",String(state.sound));ui.soundBtn.textContent=`${state.sound?"🔊":"🔇"} 音效：${state.sound?"開":"關"}`;if(state.sound)tone(620,.09)});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")pause(true,true)});window.addEventListener("blur",()=>{if(state.mode==="playing")pause(true,true)});reset();requestAnimationFrame(loop);
})();
