'use strict';
const $=id=>document.getElementById(id),c=$('canvas'),g=c.getContext('2d');let game=new StairGame(),running=false,paused=false,sound=true,audio=null,clock=0,particles=[],toastUntil=0;const held=new Map();let serial=0;
const colors={grass:'#86be74',mushroom:'#ee927e',leaf:'#c4d67a',water:'#79cbd6',honey:'#e8b756'};
function note(combo){if(!sound)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain(),t=audio.currentTime;o.frequency.value=[261.63,293.66,329.63,392,440][Math.max(0,combo-1)%5];v.gain.setValueAtTime(.06,t);v.gain.exponentialRampToValueAtTime(.001,t+.3);o.connect(v).connect(audio.destination);o.start();o.stop(t+.3);}catch{sound=false;$('sound').textContent='音效不可用';}}
function message(s){$('toast').textContent=s;toastUntil=clock+2.5;}
function overlay(title,body,symbol,button){$('title').textContent=title;$('message').textContent=body;$('symbol').textContent=symbol;$('continue').textContent=button;$('overlay').classList.remove('hidden');held.clear();}
function begin(){game=new StairGame({mode:$('mode').value,course:$('course').value});running=true;paused=false;held.clear();particles=[];$('overlay').classList.add('hidden');$('pause').textContent='暫停';note(1);}
function pause(){if(!running||game.state!=='play')return;paused=!paused;held.clear();$('pause').textContent=paused?'繼續':'暫停';if(paused)overlay('先在樹蔭休息','按繼續，森林會等你。','☁️','繼續');else $('overlay').classList.add('hidden');}
$('start').onclick=begin;$('pause').onclick=pause;$('continue').onclick=()=>{if(!running||game.state==='complete')begin();else if(paused)pause();else if(game.state==='rest'){game.resume();$('overlay').classList.add('hidden');}};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音效：'+(sound?'開':'關');$('sound').setAttribute('aria-pressed',sound);};$('magic').onclick=()=>{if(running&&!paused)game.magic();};
for(const [id,dir] of [['left',-1],['right',1]]){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,{dir,order:++serial});};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>held.delete(e.pointerId));}
const keys={ArrowLeft:-1,a:-1,A:-1,ArrowRight:1,d:1,D:1};window.addEventListener('keydown',e=>{if(/SELECT|INPUT/.test(e.target.tagName))return;if(keys[e.key]){e.preventDefault();if(!e.repeat)held.set(e.code,{dir:keys[e.key],order:++serial});}if(e.code==='Space'){e.preventDefault();if(!e.repeat&&running&&!paused)game.magic();}if(e.code==='KeyP'&&!e.repeat)pause();});window.addEventListener('keyup',e=>held.delete(e.code));function blur(){held.clear();if(running&&!paused&&game.state==='play')pause();}window.addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
function round(x,y,w,h,r,fill){g.fillStyle=fill;g.beginPath();g.roundRect(x,y,w,h,r);g.fill();}
function text(s,x,y,size,color='#eff8d9'){g.fillStyle=color;g.font=`bold ${size}px system-ui`;g.textAlign='center';g.fillText(s,x,y);}
function burst(x,y){for(let i=0;i<15;i++)particles.push({x,y,vx:(Math.random()-.5)*120,vy:-40-Math.random()*90,life:1});}
function render(dt){const t=game.time,u=game.player;const bg=g.createLinearGradient(0,0,0,800);bg.addColorStop(0,'#133e43');bg.addColorStop(.55,'#326856');bg.addColorStop(1,'#82a273');g.fillStyle=bg;g.fillRect(0,0,600,800);
 for(let i=0;i<9;i++){const x=(i*137)%630,y=(i*191-game.camera*.22)%940;round(x-26,y-100,35,1000,15,'#204d464a');g.fillStyle='#83ba8025';g.beginPath();g.ellipse(x,y+190,100,65,-.5,0,7);g.fill();}
 for(let i=0;i<25;i++){g.globalAlpha=.25+Math.sin(t+i)*.18;g.fillStyle='#ffeca1';g.beginPath();g.arc((i*193)%600,(i*89-game.camera*.15+10000)%800,2,0,7);g.fill();}g.globalAlpha=1;
 const visible=game.platforms.filter(p=>p.y-game.camera>-30&&p.y-game.camera<830);
 const target=visible.filter(p=>!p.gone&&p.y>u.y+8&&Math.abs(u.x-p.x)<p.w/2).sort((a,b)=>a.y-b.y)[0];if(target){g.fillStyle='#19372f65';g.beginPath();g.ellipse(u.x,target.y-game.camera-3,15,4,0,0,7);g.fill();}
 for(const p of visible){const y=p.y-game.camera;if(p.gone){g.globalAlpha=.18;}const type=t<game.magicUntil?'grass':p.type;let wobble=0;if(type==='leaf'&&p.touched!==null)wobble=Math.sin(t*30)*3;
 round(p.x-p.w/2+wobble,y,p.w,16,8,'#574f35');round(p.x-p.w/2+wobble,y-5,p.w,10,6,colors[type]);
 if(type==='grass'){for(let j=0;j<p.w/20;j++){g.strokeStyle='#abd593';g.beginPath();g.moveTo(p.x-p.w/2+j*20,y);g.lineTo(p.x-p.w/2+j*20-4,y-10);g.stroke();}}
 if(type==='water')text(p.dir>0?'› › › ›':'‹ ‹ ‹ ‹',p.x,y+8,21,'#ebfeff');if(type==='mushroom'){text('●   ●   ●',p.x,y+4,13,'#fff1d0');}if(type==='honey'){for(let j=0;j<4;j++)round(p.x-55+j*35,y+7,8,14,4,'#dfb055');}if(type==='leaf')text('≋',p.x,y+6,20,'#5d7844');
 if(p.coin&&!p.gone){text('🌰',p.x,y-21,20);}if(p.id%10===0&&p.id>0)text('休息站 '+p.id,p.x,y+35,13);g.globalAlpha=1;}
 const sy=u.y-game.camera;
 if(t<game.magicUntil){g.fillStyle='#edb1df22';g.fillRect(0,0,600,800);g.strokeStyle='#ffdfaa';g.lineWidth=3;g.beginPath();g.arc(u.x,sy-22,38+Math.sin(t*3)*4,0,7);g.stroke();}
 g.save();g.translate(u.x,sy);const walk=held.size&&u.on?Math.sin(t*18)*3:0;round(-13,-10+walk,10,10,4,'#493b34');round(3,-10-walk,10,10,4,'#493b34');round(-17,-39,34,31,12,'#d7b675');g.fillStyle='#f4d6a4';g.beginPath();g.arc(0,-45,19,0,7);g.fill();g.fillStyle='#77ac7a';g.beginPath();g.ellipse(0,-61,23,8,-.1,0,7);g.fill();g.strokeStyle='#40644a';g.lineWidth=3;g.beginPath();g.moveTo(2,-67);g.lineTo(8,-75);g.stroke();round(-9,-48,4,5,2,'#273e35');round(6,-48,4,5,2,'#273e35');g.strokeStyle='#986c48';g.lineWidth=2;g.beginPath();g.arc(0,-41,5,0,Math.PI);g.stroke();g.restore();
 for(const p of particles){if(!paused&&game.state==='play'){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}g.globalAlpha=Math.max(0,p.life);text('✦',p.x,p.y,12,'#ffe5a2');}g.globalAlpha=1;particles=particles.filter(p=>p.life>0);
 round(0,0,600,28,8,'#244d38');text('柔軟樹冠 · 雲朵守護',300,20,12,'#accb95');
 $('depth').textContent=game.depth+' 層';$('nuts').textContent=game.acorns;$('combo').textContent=game.combo;$('toast').style.opacity=clock<toastUntil?'1':'0';const cd=Math.ceil(game.cooldown-game.time);$('magic').disabled=!running||paused||game.state!=='play'||cd>0;$('magic').textContent=cd>0?`🌈 魔法休息 ${cd}s`:'🌈 妍妍魔法';}
let previous=performance.now(),acc=0;function frame(now){const dt=Math.min((now-previous)/1000,.08);previous=now;if(!paused)clock+=dt;if(running&&!paused){acc+=dt;while(acc>=1/120){const values=[...held.values()].sort((a,b)=>b.order-a.order);game.tick(1/120,values[0]?.dir||0);acc-=1/120;}}else acc=0;
 for(const e of game.events.splice(0)){if(e.type==='land'){note(e.combo);burst(game.player.x,game.player.y-game.camera-20);}if(e.type==='rescue')message('☁️ 雲朵接住你了，再找下一階！');if(e.type==='magic')message('🌈 妍妍魔法！特殊平台暫時變青草');if(e.type==='wrap')message('☁️ 穿過雲朵，來到另一邊');if(e.type==='rest')overlay('松鼠休息站',`已收集 ${game.acorns} 顆橡果。準備好再繼續！`,'🐿️','繼續往下');if(e.type==='complete')overlay('森林探險完成！',`橡果 ${game.acorns} 顆 · 最佳連續落地 ${game.best} 次 · 雲朵救援 ${game.rescues} 次`,'🌈','再玩一次');}
 render(dt);requestAnimationFrame(frame);}
requestAnimationFrame(frame);
