import test from 'node:test';import assert from 'node:assert/strict';
import {makeKitchenScene,closeKitchen,clickOverlay,doc,win} from './fixtures/kitchen_scene_mock.mjs';
import {kitchenPilot} from './fixtures/kitchen_pilot.mjs';
import {KITCHEN_TARGETS} from '../src/data/KitchenConfig.js';
const active=new Set();const scene=(missing=false)=>{const s=makeKitchenScene(missing);active.add(s);return s;};
const tick=(s,n=1)=>{for(let i=0;i<n;i++)s.update(0,100);};
const start=(s,i=0)=>{s.startLevel(i);clickOverlay(s,'開張！');};
test.afterEach(()=>{for(const s of active)closeKitchen(s);active.clear();document.hidden=false;window.innerWidth=844;window.innerHeight=390;});
test('selection has six large level cards and all three difficulties',()=>{const s=scene();assert.equal(s.levelButtons.length,6);assert.equal(s.levelButtons[0].height,190);s.difficultyButton.emit('pointerdown');assert.equal(s.difficulty,'rush');s.difficultyButton.emit('pointerdown');assert.equal(s.difficulty,'relaxed');});
test('all six complete shifts work through actual scene pointer handlers and result flow',(t)=>{
  // Use the recorded-route seed; wall-clock seeds made this replay nondeterministic.
  t.mock.method(Date,'now',()=>12345);
  const s=scene();for(let i=0;i<6;i++){start(s,i);const r=kitchenPilot(s.session,{dispatch(kind,value){if(kind==='select')s.chefCards[value].c.emit('pointerdown');if(kind==='command')s.buttons[value].emit('pointerdown');if(kind==='skill')s.buttons.skill.emit('pointerdown');if(kind==='trash'){s.buttons.trash.emit('pointerdown');clickOverlay(s,'丟棄手上物品');}},step:()=>tick(s)});assert.equal(r.status,'won',`kitchen ${i+1}`);assert.equal(s.mode,'finished');assert(s.records[`${i+1}:standard`]);}
});
test('briefing freezes the shift until player taps open',()=>{const s=scene();s.startLevel(0);assert.equal(s.mode,'paused');tick(s,30);assert.equal(s.session.time,0);clickOverlay(s,'開張！');tick(s);assert.equal(s.session.time,.1);});
test('food and workbench buttons issue walking commands with large art',()=>{const s=scene();start(s);s.buttons.tomato.emit('pointerdown');tick(s,30);assert.equal(s.session.chefs[0].held.food,'tomato');s.buttons.chop.emit('pointerdown');tick(s,70);assert(s.session.chefs[0].held.prepared);assert.equal(s.chefViews[0].body.displayWidth,114);assert(s.foodViews[0].list.some(o=>o.displayWidth===95));});
test('chef cards and number shortcuts select without cancelling queued movement',()=>{const s=scene();start(s);s.buttons.egg.emit('pointerdown');s.chefCards[1].c.emit('pointerdown');assert.equal(s.session.selected,1);assert.equal(s.session.chefs[0].target,'egg');s.input.keyboard.emit('keydown',{code:'Digit3'});assert.equal(s.session.selected,2);});
test('each gameplay target uses the tested bounds exported by layout config',()=>{const s=scene();start(s);for(const t of KITCHEN_TARGETS){const v=s.buttons[t.id]||(/^chef/.test(t.id)?s.chefCards[Number(t.id.slice(-1))].c:/^order/.test(t.id)?s.orderViews[Number(t.id.slice(-1))].c:s.objects.find(o=>o.kind==='container'&&o.x===t.x&&o.y===t.y&&o.interactive));assert(v,t.id);assert.equal(v.width,t.w,t.id);assert.equal(v.height,t.h,t.id);}});
test('orders open paused large recipes, pages navigate, and closing resumes same state',()=>{const s=scene();start(s);tick(s,12);const time=s.session.time;s.orderViews[0].c.emit('pointerdown');assert.equal(s.mode,'recipe');assert(s.overlay.list.some(o=>o.displayWidth===124));tick(s,50);assert.equal(s.session.time,time);const before=s.recipeIndex;clickOverlay(s,'下一道 →');assert.equal(s.recipeIndex,(before+1)%6);clickOverlay(s,'懂了，繼續料理');assert.equal(s.mode,'playing');assert.equal(s.session.time,time);});
test('cleanup is explicit and cancelling preserves food and combo',()=>{const s=scene();start(s);s.buttons.egg.emit('pointerdown');tick(s,30);const held=s.session.chefs[0].held;s.buttons.trash.emit('pointerdown');assert.equal(s.mode,'cleanup');tick(s,30);clickOverlay(s,'不丟棄，繼續料理');assert.equal(s.session.chefs[0].held,held);s.buttons.trash.emit('pointerdown');clickOverlay(s,'丟棄手上物品');assert.equal(s.session.chefs[0].held,null);assert.equal(s.session.stats.waste,1);});
test('blur and document hiding pause everything and require manual resume',()=>{const s=scene();start(s);s.buttons.egg.emit('pointerdown');s.game.events.emit('blur');const state=JSON.stringify(s.session);tick(s,40);assert.equal(JSON.stringify(s.session),state);clickOverlay(s,'繼續料理');document.hidden=true;doc.emit('visibilitychange');assert.equal(s.mode,'paused');document.hidden=false;doc.emit('visibilitychange');assert.equal(s.mode,'paused');});
test('portrait during gameplay pauses, blocks hidden inputs and does not auto resume on rotation',()=>{const s=scene();start(s);window.innerWidth=390;window.innerHeight=844;win.emit('resize');assert(s.portraitOverlay);assert.equal(s.mode,'paused');s.buttons.egg.emit('pointerdown');s.chefCards[2].c.emit('pointerdown');s.input.keyboard.emit('keydown',{code:'Escape'});tick(s,20);assert.equal(s.session.selected,0);assert.equal(s.session.time,0);window.innerWidth=844;window.innerHeight=390;win.emit('resize');assert.equal(s.portraitOverlay,null);assert.equal(s.mode,'paused');clickOverlay(s,'繼續料理');assert.equal(s.mode,'playing');});
test('portrait menu cannot launch a tiny kitchen and recovers after rotation',()=>{window.innerWidth=390;window.innerHeight=844;const s=scene();s.levelButtons[0].emit('pointerdown');assert.equal(s.session,null);window.innerWidth=844;window.innerHeight=390;win.emit('resize');s.levelButtons[0].emit('pointerdown');assert(s.session);});
test('portrait over a recipe keeps the recipe and its paused state when landscape returns',()=>{const s=scene();start(s);s.showRecipe();const overlay=s.overlay;window.innerWidth=390;window.innerHeight=844;win.emit('resize');window.innerWidth=844;window.innerHeight=390;win.emit('resize');assert.equal(s.overlay,overlay);assert.equal(s.mode,'recipe');assert(s.session.paused);});
test('restart confirmation cancellation preserves state while confirmation starts a new shift',()=>{const s=scene();start(s);tick(s,20);s.pauseGame();clickOverlay(s,'重新開張');assert.equal(s.mode,'confirm');clickOverlay(s,'取消，繼續料理');assert(Math.abs(s.session.time-2)<1e-8);s.pauseGame();clickOverlay(s,'重新開張');clickOverlay(s,'確認重新開張');assert.equal(s.session.time,0);assert.equal(s.mode,'paused');});
test('expired shift produces loss screen without overwriting best records',()=>{const s=scene();start(s);s.records['1:standard']={stars:3,score:999};s.session.remaining=.01;tick(s);assert.equal(s.mode,'finished');assert.equal(s.session.status,'lost');assert.equal(s.records['1:standard'].score,999);clickOverlay(s,'再開張一次');assert.equal(s.session.stats.score,0);});
test('sound toggle stops future synthesized tones and updates label',()=>{const s=scene();start(s);s.soundButton.emit('pointerdown');assert(!s.soundOn);assert.match(s.soundButton.label.text,/關/);});
test('help offers distinct chef roles and returns to selection without a session',()=>{const s=scene();s.showHelp();assert.equal(s.mode,'help');assert(s.overlay.list.some(o=>o.text==='兔兔 · 快腳'));clickOverlay(s,'選擇廚房');assert.equal(s.mode,'select');assert.equal(s.session,null);});
test('missing assets retain a working exit to the integrated hub',()=>{const s=scene(true);clickOverlay(s,'返回遊戲列表');assert.equal(s.destination,'MiniGameHub');});
test('leaving pauses work and shutdown removes all owned listeners and captures',()=>{const s=scene();start(s);s.leave();assert.equal(s.destination,'MiniGameHub');assert(s.session.paused);closeKitchen(s);active.delete(s);assert.equal(doc.listenerCount('visibilitychange'),0);assert.equal(win.listenerCount('resize'),0);assert.equal(s.input.keyboard.listenerCount('keydown'),0);assert.equal(s.game.events.listenerCount('blur'),0);assert.equal(s.captures.size,0);assert.equal(s.session,null);});
