// Phaser display/input simulation; real browser and physical-device QA remain separate.
import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {skyPilot} from './fixtures/sky_pilot.mjs';
class Display extends EventEmitter{
    constructor(x=0,y=0,text=''){super();Object.assign(this,{x,y,text,list:[],width:512,height:512,visible:true});}
    add(items){this.list.push(...(Array.isArray(items)?items:[items]));return this;}
    setText(text){this.text=text;return this;}setAlpha(alpha){this.alpha=alpha;return this;}setVisible(visible){this.visible=visible;return this;}
    setDisplaySize(width,height){Object.assign(this,{width,height});return this;}setFrame(frame){this.frame=frame;return this;}
    setInteractive(){this.interactive=true;return this;}destroy(){if(this.destroyed)return;this.destroyed=true;this.list.forEach(o=>o.destroy?.());}
}
for(const m of ['setOrigin','setDepth','setSize','setStrokeStyle','fillStyle','lineStyle','fillRoundedRect','strokeRoundedRect','setWordWrapWidth','setAngle','setTint','lineBetween','fillRect','clear','fillCircle','strokeCircle','setScale'])Display.prototype[m]=function(){return this;};
Display.prototype.createGeometryMask=function(){return {destroy(){this.destroyed=true;}};};
Display.prototype.setMask=function(mask){this.mask=mask;return this;};
globalThis.Phaser={Scene:class{}};const doc=new EventEmitter();globalThis.document={hidden:false,addEventListener:(k,f)=>doc.on(k,f),removeEventListener:(k,f)=>doc.off(k,f)};
const {default:Scene}=await import('../src/scenes/ForestSkyGame.js');const active=new Set();
function scene(missing=false){
    const s=new Scene(),objects=[];s.init({returnScene:'MiniGameHub'});s.textures={exists:()=>!missing};s.events=new EventEmitter();s.game={events:new EventEmitter()};
    s.sound={stopAll(){},context:null};s.input=new EventEmitter();s.input.keyboard=new EventEmitter();s.input.manager={pointersTotal:1};s.input.addPointer=n=>s.input.manager.pointersTotal+=n;
    s.captures=new Set();s.input.keyboard.addCapture=k=>k.forEach(v=>s.captures.add(v));s.input.keyboard.removeCapture=k=>k.forEach(v=>s.captures.delete(v));
    s.add=Object.fromEntries(['image','rectangle','circle','graphics','container','text'].map(m=>[m,(x,y,t)=>{const o=new Display(x,y,t);objects.push(o);return o;}]));
    s.children={removeAll(){objects.forEach(o=>o.destroy());objects.length=0;}};s.tweens={killAll(){}};
    s.scene={manager:{keys:{MiniGameHub:{}}},start:name=>{s.destination=name;}};s.create();active.add(s);return s;
}


const close=s=>{s.events.emit('shutdown');active.delete(s);};test.afterEach(()=>{for(const s of active)close(s);document.hidden=false;});
const click=(s,label)=>{const b=s.overlay?.list.find(o=>o.label?.text===label);assert(b,label);b.emit('pointerdown');};
const tick=(s,n=1)=>{for(let i=0;i<n;i++)s.update(0,100);};
function fly(s){let frames=0;while(s.mode==='playing'&&frames++<2100){const input=skyPilot(s.session),p=s.session.player,point={id:1,x:320+p.x,y:82+p.y};s.input.emit('pointerdown',point,[]);s.input.emit('pointermove',{id:1,x:point.x+input.target.x-p.x,y:point.y+input.target.y-p.y});s.changeWeapon(input.weapon);if(input.bomb)s.bombButton.emit('pointerdown');if(input.dash)s.dashButton.emit('pointerdown');tick(s);s.input.emit('pointerup',{id:1});}assert.equal(s.mode,'finished');}

test('all 15 missions run through scene controls, scrolling, boss transitions and three-star results',()=>{const s=scene();click(s,'選擇第一段航程');for(let i=0;i<15;i++){s.startLevel(i);fly(s);assert.equal(s.session.status,'won',`mission ${i+1}`);assert.equal(s.records[`${i+1}:rookie`].stars,3);}close(s);});
test('relative touch dragging never teleports the aircraft and release outside clears movement',()=>{const s=scene();s.startLevel(0);s.input.emit('pointerdown',{id:1,x:700,y:450},[]);assert.equal(s.session.player.x,320);s.input.emit('pointermove',{id:1,x:800,y:400});tick(s);assert(s.session.player.x>320&&s.session.player.x<354);s.input.emit('pointerupoutside',{id:1});assert.equal(s.target,null);const x=s.session.player.x;tick(s);assert.equal(s.session.player.x,x);close(s);});
test('second touch can charge while first touch steers, and release fires one charged shot',()=>{const s=scene();s.startLevel(0);s.input.emit('pointerdown',{id:1,x:640,y:580},[]);s.input.emit('pointermove',{id:1,x:690,y:560});s.chargeButton.emit('pointerdown',{id:2});tick(s,9);assert(s.session.player.charge>.8);assert(s.session.player.x>320);s.input.emit('pointerup',{id:2});assert(s.drag);tick(s);assert.equal(s.session.stats.charged,1);s.input.emit('pointerup',{id:1});assert.equal(s.drag,null);assert.equal(s.touchCharge.size,0);close(s);});
test('selection release and HUD touches do not move the plane, and a second finger cannot steal steering',()=>{const s=scene();s.startLevel(0);s.input.emit('pointerdown',{id:1,x:600,y:300},[{}]);assert.equal(s.drag,null);s.input.emit('pointerdown',{id:1,x:640,y:500},[]);s.input.emit('pointerdown',{id:2,x:800,y:300},[]);assert.equal(s.drag.id,1);s.input.emit('pointerup',{id:2});assert.equal(s.drag.id,1);close(s);});
test('keyboard movement, weapon cycling, focus and dash buttons reach the combat model',()=>{const s=scene();s.startLevel(0);s.input.keyboard.emit('keydown',{code:'KeyD'});tick(s);assert(s.session.player.x>350);s.input.keyboard.emit('keyup',{code:'KeyD'});s.input.keyboard.emit('keydown',{code:'Digit3'});assert.equal(s.session.player.weapon,2);s.input.keyboard.emit('keydown',{code:'KeyQ'});assert.equal(s.session.player.weapon,3);s.input.keyboard.emit('keydown',{code:'ShiftLeft'});tick(s);assert.equal(s.session.stats.dashes,1);s.input.keyboard.emit('keydown',{code:'KeyB'});tick(s);assert.equal(s.session.stats.bombs,1);close(s);});
test('one-frame tool requests survive a display frame shorter than one physics step',()=>{const s=scene();s.startLevel(0);s.dashButton.emit('pointerdown');s.update(0,1);assert(s.dashRequest);assert.equal(s.session.stats.dashes,0);s.update(0,10);assert.equal(s.session.stats.dashes,1);assert(!s.dashRequest);close(s);});
test('blur pauses bullets, aircraft and effects; resume cancels held charge without consuming energy',()=>{const s=scene();s.startLevel(7);s.chargeButton.emit('pointerdown',{id:2});tick(s,8);s.game.events.emit('blur');assert.equal(s.mode,'paused');assert.equal(s.session.player.charge,0);const snapshot=JSON.stringify([s.session.time,s.session.player,s.session.shots,s.effects]);tick(s,30);assert.equal(JSON.stringify([s.session.time,s.session.player,s.session.shots,s.effects]),snapshot);assert.equal(s.touchCharge.size,0);click(s,'繼續飛行');tick(s);assert.equal(s.session.stats.charged,0);close(s);});
test('visibility return does not automatically resume and paused controls cannot launch bombs or change weapons',()=>{const s=scene();s.startLevel(0);document.hidden=true;doc.emit('visibilitychange');assert.equal(s.mode,'paused');const weapon=s.session.player.weapon;s.bombButton.emit('pointerdown');s.dashButton.emit('pointerdown');s.weaponButtons[2].emit('pointerdown');tick(s);assert.equal(s.session.stats.bombs,0);assert.equal(s.session.player.weapon,weapon);document.hidden=false;doc.emit('visibilitychange');assert.equal(s.mode,'paused');close(s);});
test('restart confirmation preserves current run when cancelled and resets it when confirmed',()=>{const s=scene();s.startLevel(0);tick(s,20);const time=s.session.time;s.pauseGame();click(s,'本關重新開始');assert.equal(s.mode,'confirm');tick(s,10);assert.equal(s.session.time,time);click(s,'繼續目前航程');assert.equal(s.session.time,time);s.pauseGame();click(s,'本關重新開始');click(s,'重新起飛');assert.equal(s.session.time,0);assert.equal(s.session.player.power,0);close(s);});
test('difficulty-specific records survive replays while each new round resets supplies',()=>{const s=scene();s.startLevel(0);fly(s);assert.equal(s.records['1:rookie'].stars,3);click(s,'再飛一次');assert.equal(s.session.player.bombs,2);assert.equal(s.session.stats.kills,0);s.difficulty='brave';s.startLevel(0);fly(s);assert.equal(s.records['1:brave'].stars,3);assert.equal(s.records['1:rookie'].stars,3);close(s);});
test('completion locks flight controls and next-stage and selection navigation remain usable',()=>{const s=scene();s.startLevel(0);fly(s);const x=s.session.player.x;s.input.keyboard.emit('keydown',{code:'KeyD'});s.bombButton.emit('pointerdown');tick(s,5);assert.equal(s.session.player.x,x);click(s,'下一關 →');assert.equal(s.index,1);s.pauseGame();click(s,'返回選關');assert.equal(s.mode,'select');close(s);});
test('loss gives a recoverable retry flow with fresh health',()=>{const s=scene();s.startLevel(0);s.session.player.hp=1;s.session.player.shield=0;s.session.player.invuln=0;s.session.hitPlayer();tick(s);assert.equal(s.mode,'finished');assert.equal(s.session.status,'lost');click(s,'再飛一次');assert.equal(s.session.player.hp,6);assert.equal(s.session.status,'playing');close(s);});
test('leaving destroys the playfield mask and cleans only owned listeners and captures',()=>{const s=scene();s.startLevel(0);const mask=s.worldMask;assert.equal(s.world.mask,mask);s.leave();assert.equal(s.destination,'MiniGameHub');assert(s.session.paused);close(s);assert(mask.destroyed);assert.equal(s.input.listenerCount('pointermove'),0);assert.equal(s.input.keyboard.listenerCount('keydown'),0);assert.equal(doc.listenerCount('visibilitychange'),0);assert.equal(s.captures.size,0);assert.equal(s.input.manager.pointersTotal,3);});
test('missing artwork recovers to the existing integrated game list',()=>{const s=scene(true);click(s,'返回遊戲列表');assert.equal(s.destination,'MiniGameHub');close(s);});
