import assert from 'node:assert/strict';
import {LavaStepSession,LAVA_STEP_LEVELS,CoolingSession,COOLING_LEVELS,LavaPipeSession,PIPE_LEVELS,isPipeAligned,VolcanoEchoSession,ECHO_LEVELS,LavaBridgeSession,BRIDGE_LEVELS} from '../src/data/VolcanoSeriesData.js';

const step=new LavaStepSession();for(const i of step.level.order)step.tap(i);assert.equal(step.complete,true);assert.equal(step.advance(),true);assert.equal(step.levelIndex,1);
LAVA_STEP_LEVELS.forEach(l=>assert.ok(l.order.length>=3));
const cool=new CoolingSession();assert.deepEqual(cool.level.allowed,[1,2]);assert.equal(cool.hint(),2);assert.equal(cool.add(2),'added');assert.equal(cool.add(2),'too_much');assert.equal(cool.hint(),1);assert.equal(cool.add(1),'complete');assert.equal(cool.complete,true);assert.equal(cool.attempts,3);assert.equal(COOLING_LEVELS.length,5);assert.equal(cool.advance(),true);assert.equal(cool.add(3),'ignored');assert.equal(cool.add(2),'added');assert.equal(cool.undo(),true);assert.equal(cool.value,0);
assert.equal(isPipeAligned('straight',0,2),true);assert.equal(isPipeAligned('corner',0,2),false);
const pipe=new LavaPipeSession();assert.equal(pipe.complete,false);const firstHint=pipe.hint();assert.ok(firstHint>=0);pipe.level.target.forEach((target,i)=>{let guard=0;while(!isPipeAligned(pipe.level.types[i],pipe.rotations[i],target)&&guard++<4)pipe.rotate(i);});assert.equal(pipe.complete,true);assert.equal(PIPE_LEVELS.length,5);assert.equal(pipe.advance(),true);pipe.reset();assert.equal(pipe.complete,false);
const echo=new VolcanoEchoSession();assert.equal(echo.level.active.length,2);assert.equal(echo.sequence.length,2);assert.equal(echo.press('rock'),'again');assert.equal(echo.progress,0);assert.equal(echo.replay(),true);assert.equal(echo.replays,1);for(const id of echo.sequence)echo.press(id);assert.equal(echo.complete,true);assert.equal(echo.replay(),false);assert.equal(echo.advance(),true);assert.equal(echo.sequence.length,3);assert.equal(ECHO_LEVELS.length,5);
const bridge=new LavaBridgeSession();assert.deepEqual(bridge.level.allowed,[1,2]);assert.equal(bridge.add(3),'ignored');assert.equal(bridge.hint(),2);assert.equal(bridge.add(1),'added');assert.equal(bridge.hint(),1);assert.equal(bridge.add(2),'too_long');assert.equal(bridge.add(1),'complete');assert.equal(bridge.complete,true);assert.equal(bridge.advance(),true);assert.equal(bridge.add(2),'added');assert.equal(bridge.undo(),true);assert.equal(bridge.length,0);bridge.reset();assert.equal(bridge.resets,1);assert.equal(BRIDGE_LEVELS.length,5);
console.log('volcano_series_logic: five gentle game loops and all level sets passed');
