(()=>{
"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height;
const ui={start:document.getElementById("startPanel"),stage:document.getElementById("stagePanel"),pause:document.getElementById("pausePanel"),finish:document.getElementById("finishPanel"),stageTitle:document.getElementById("stageTitle"),stageHelp:document.getElementById("stageHelp"),stageIcon:document.getElementById("stageIcon"),stageText:document.getElementById("stageText"),roundText:document.getElementById("roundText"),progress:document.getElementById("progressBar"),startBtn:document.getElementById("startBtn"),stageBtn:document.getElementById("stageBtn"),resumeBtn:document.getElementById("resumeBtn"),replayBtn:document.getElementById("replayBtn"),restartBtn:document.getElementById("restartBtn"),toddlerBtn:document.getElementById("toddlerBtn"),slowBtn:document.getElementById("slowBtn"),hintBtn:document.getElementById("hintBtn"),soundBtn:document.getElementById("soundBtn"),pauseBtn:document.getElementById("pauseBtn")};
const tokens={r:{color:"#ff6f7f",symbol:"heart"},o:{color:"#ffad51",symbol:"sun"},y:{color:"#ffe05a",symbol:"star"},g:{color:"#68dca2",symbol:"leaf"},b:{color:"#5cc7f0",symbol:"drop"},p:{color:"#aa83ec",symbol:"diamond"}};
const stages=[
 {name:"第一階段：照著補",title:"照著範例補顏色",help:"上方會直接告訴你缺少哪一塊。",icon:"🎨"},
 {name:"第二階段：彩虹順序",title:"找出彩虹的順序",help:"看看缺口左右兩邊，下一個顏色是什麼？",icon:"🌈"},
 {name:"第三階段：圖案規律",title:"找出圖案規律",help:"顏色和圖案會重複出現，找出少掉的一塊。",icon:"🧠"}
];
const levels=[
 {seq:"roygbpr",miss:[2],direct:true},{seq:"gbproyg",miss:[4],direct:true},{seq:"pygbroy",miss:[1],direct:true},{seq:"broypgb",miss:[5],direct:true},
 {seq:"royroyr",miss:[2,5]},{seq:"gbpgbpg",miss:[1,4]},{seq:"ygygygy",miss:[2,5]},{seq:"bprbprb",miss:[0,3]},
 {seq:"rbrbrbr",miss:[2,5]},{seq:"oogpoog",miss:[1,4]},{seq:"ypgypgy",miss:[1,2,5]},{seq:"rrbyrrb",miss:[2,4,6]}
];
const optionXs=[305,480,655],optionY=445,tileXs=[142,255,368,481,594,707,820],tileY=270;
let state,last=performance.now(),audioCtx=null;
function reset(){state={mode:"ready",index:0,filled:{},activeMissing:0,options:[],toddler:false,slow:false,hint:false,sound:true,anim:null,wrong:null,success:0,walk:0,sparkles:[],inactive:0};prepare();updateHud()}
function tone(freq,d=.12,type="sine",gain=.05){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(_){}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function currentLevel(){return levels[state.index]}
function currentSlot(){return currentLevel().miss[state.activeMissing]}
function correctId(){return currentLevel().seq[currentSlot()]}
function prepareOptions(){const correct=correctId(),ids=Object.keys(tokens).filter(x=>x!==correct);shuffle(ids);state.options=shuffle([correct,ids[0],ids[1]]).map((id,i)=>({id,x:optionXs[i],y:optionY,homeX:optionXs[i],homeY:optionY}));}
function prepare(){state.filled={};state.activeMissing=0;state.anim=null;state.wrong=null;state.success=0;state.walk=0;state.inactive=0;prepareOptions()}
function hidePanels(){[ui.start,ui.stage,ui.pause,ui.finish].forEach(p=>{p.classList.remove("show");p.setAttribute("aria-hidden","true")})}
function showStage(){state.mode="stage";const s=stages[Math.floor(state.index/4)];ui.stageTitle.textContent=s.title;ui.stageHelp.textContent=s.help;ui.stageIcon.textContent=s.icon;hidePanels();ui.stage.classList.add("show");ui.stage.setAttribute("aria-hidden","false")}
function begin(){reset();hidePanels();showStage()}
function playStage(){hidePanels();state.mode="playing";last=performance.now();canvas.focus();tone(523,.1);setTimeout(()=>tone(659,.13),90)}
function setPaused(v,automatic=false){if(!["playing","paused"].includes(state.mode))return;state.mode=v?"paused":"playing";ui.pauseBtn.textContent=v?"▶ 繼續":"⏸ 暫停";if(v){hidePanels();ui.pause.classList.add("show");ui.pause.setAttribute("aria-hidden","false");ui.pause.querySelector("p").textContent=automatic?"畫面暫停了，彩虹橋會等你回來。":"彩虹橋會等你回來。"}else{hidePanels();last=performance.now();canvas.focus()}}
function updateHud(){const s=Math.floor(state.index/4);ui.stageText.textContent=stages[Math.min(2,s)].name;ui.roundText.textContent=`${Math.min(12,state.index+1)} / 12`;ui.progress.style.width=`${state.index/12*100}%`}
function choose(i){if(state.mode!=="playing"||state.anim||state.wrong||state.success||state.walk)return;state.inactive=0;const o=state.options[i],slot=currentSlot();state.anim={i,t:0,d:state.slow?.72:.46,sx:o.x,sy:o.y,tx:tileXs[slot],ty:tileY}}
function judge(){const o=state.options[state.anim.i],id=o.id,slot=currentSlot();state.anim=null;if(id===correctId()){state.filled[slot]=id;emit(tileXs[slot],tileY);const note=[523,587,659,698,784,880][Object.keys(tokens).indexOf(id)];tone(note,.18,"sine",.055);state.success=state.slow?0.72:0.46}else{state.wrong={id,x:tileXs[slot],y:tileY,t:0,d:state.slow?0.9:0.62};tone(180,.18,"sine",.04)}}
function advanceFill(){state.success=0;state.activeMissing++;if(state.activeMissing>=currentLevel().miss.length){state.walk=.01;tone(659,.12);setTimeout(()=>tone(784,.14),100)}else prepareOptions()}
function nextLevel(){state.index++;if(state.index>=levels.length){state.mode="finished";ui.progress.style.width="100%";hidePanels();ui.finish.classList.add("show");ui.finish.setAttribute("aria-hidden","false");tone(659,.15);setTimeout(()=>tone(880,.2),120);setTimeout(()=>tone(1047,.27),270);return}prepare();updateHud();if(state.index%4===0)showStage()}
function emit(x,y){for(let i=0;i<22;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*105;state.sparkles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.8,size:3+Math.random()*5,color:["#fff16d","#ff8fb9","#73dca8","#85dcff"][i%4]})}}
function update(dt){if(state.mode!=="playing")return;state.inactive+=dt;if(state.toddler&&state.inactive>3)state.hint=true;
 if(state.anim){const a=state.anim;a.t=Math.min(a.d,a.t+dt);const p=a.t/a.d,e=1-Math.pow(1-p,3),o=state.options[a.i];o.x=a.sx+(a.tx-a.sx)*e;o.y=a.sy+(a.ty-a.sy)*e;if(p>=1)judge()}
 if(state.wrong){state.wrong.t+=dt;state.wrong.y+=130*dt;state.wrong.x+=Math.sin(state.wrong.t*18)*2;if(state.wrong.t>=state.wrong.d){state.wrong=null;prepareOptions()}}
 if(state.success>0){state.success-=dt;if(state.success<=0)advanceFill()}
 if(state.walk>0){state.walk+=dt/(state.slow?2.4:1.55);if(state.walk>=1){state.walk=0;nextLevel()}}
 for(const p of state.sparkles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=45*dt;p.life-=dt}state.sparkles=state.sparkles.filter(p=>p.life>0)
}
function symbolPath(g,name,s){g.beginPath();if(name==="heart"){g.moveTo(0,s*.65);g.bezierCurveTo(-s*1.1,-s*.05,-s*.75,-s*.8,0,-s*.35);g.bezierCurveTo(s*.75,-s*.8,s*1.1,-s*.05,0,s*.65)}else if(name==="sun"){g.arc(0,0,s*.46,0,Math.PI*2);for(let i=0;i<8;i++){const a=i*Math.PI/4;g.moveTo(Math.cos(a)*s*.62,Math.sin(a)*s*.62);g.lineTo(Math.cos(a)*s*.9,Math.sin(a)*s*.9)}}else if(name==="star"){for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?s*.35:s*.78;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?g.lineTo(x,y):g.moveTo(x,y)}g.closePath()}else if(name==="leaf"){g.moveTo(-s*.7,s*.55);g.quadraticCurveTo(-s*.7,-s*.65,s*.7,-s*.7);g.quadraticCurveTo(s*.72,s*.65,-s*.7,s*.55);g.moveTo(-s*.6,s*.45);g.lineTo(s*.48,-s*.48)}else if(name==="drop"){g.moveTo(0,-s*.85);g.bezierCurveTo(s*.8,0,s*.7,s*.75,0,s*.82);g.bezierCurveTo(-s*.7,s*.75,-s*.8,0,0,-s*.85)}else{g.moveTo(0,-s*.8);g.lineTo(s*.62,0);g.lineTo(0,s*.8);g.lineTo(-s*.62,0);g.closePath()}}
function drawToken(id,x,y,w=92,h=78,alpha=1){const t=tokens[id];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.shadowColor="rgba(31,77,107,.22)";ctx.shadowBlur=12;ctx.shadowOffsetY=5;ctx.fillStyle=t.color;ctx.strokeStyle="rgba(255,255,255,.94)";ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,18);ctx.fill();ctx.stroke();ctx.shadowColor="transparent";ctx.strokeStyle="rgba(39,69,88,.72)";ctx.fillStyle="rgba(255,255,255,.82)";ctx.lineWidth=4;symbolPath(ctx,t.symbol,23);ctx.fill();ctx.stroke();ctx.restore()}
function drawBackground(){const gr=ctx.createLinearGradient(0,0,0,H);gr.addColorStop(0,"#69ccf7");gr.addColorStop(.7,"#e0f8ff");gr.addColorStop(1,"#fff2bd");ctx.fillStyle=gr;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.48)";for(let i=0;i<7;i++){const x=(i*180+35)%W,y=95+(i%2)*65;ctx.beginPath();ctx.arc(x,y,27,0,Math.PI*2);ctx.arc(x+30,y+3,35,0,Math.PI*2);ctx.arc(x+62,y+8,24,0,Math.PI*2);ctx.fill()}ctx.fillStyle="rgba(81,153,181,.22)";ctx.beginPath();ctx.ellipse(70,350,170,50,0,0,Math.PI*2);ctx.ellipse(890,350,170,50,0,0,Math.PI*2);ctx.fill()}
function drawBridge(){const lv=currentLevel(),slot=currentSlot();ctx.save();ctx.strokeStyle="#aa7a63";ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(90,315);ctx.quadraticCurveTo(480,178,870,315);ctx.stroke();ctx.lineWidth=5;ctx.strokeStyle="#d8aa7e";ctx.beginPath();ctx.moveTo(90,328);ctx.quadraticCurveTo(480,191,870,328);ctx.stroke();ctx.restore();
 for(let i=0;i<7;i++){const missing=lv.miss.includes(i),filled=state.filled[i];if(!missing||filled)drawToken(filled||lv.seq[i],tileXs[i],tileY-(Math.sin((i/6)*Math.PI)*52),86,70);else{const active=i===slot,pulse=.5+.5*Math.sin(performance.now()/230);ctx.save();ctx.translate(tileXs[i],tileY-(Math.sin((i/6)*Math.PI)*52));ctx.strokeStyle=active?(state.hint?`rgba(255,205,56,${.65+.35*pulse})`:"rgba(255,255,255,.95)"):"rgba(255,255,255,.48)";ctx.lineWidth=active?7:4;ctx.setLineDash([10,8]);ctx.beginPath();ctx.roundRect(-43,-35,86,70,18);ctx.stroke();ctx.restore()}}
 if(lv.direct){const id=correctId();ctx.save();ctx.fillStyle="rgba(255,255,255,.88)";ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(28,82,190,104,22);ctx.fill();ctx.stroke();ctx.fillStyle="#37647f";ctx.font="800 16px sans-serif";ctx.fillText("照著這一塊補回去",48,109);ctx.restore();drawToken(id,123,150,74,56)}
}
function drawOptions(){for(let i=0;i<state.options.length;i++){const o=state.options[i],glow=state.hint&&o.id===correctId();ctx.save();ctx.fillStyle=glow?"rgba(255,225,72,.4)":"rgba(255,255,255,.34)";ctx.strokeStyle=glow?"#ffd044":"rgba(255,255,255,.8)";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(o.homeX-78,391,156,126,24);ctx.fill();ctx.stroke();ctx.fillStyle="#35627d";ctx.font="800 18px sans-serif";ctx.textAlign="center";ctx.fillText(String(i+1),o.homeX,506);ctx.restore();if(!(state.wrong&&state.wrong.id===o.id))drawToken(o.id,o.x,o.y,82,66)}if(state.wrong)drawToken(state.wrong.id,state.wrong.x,state.wrong.y,82,66,Math.max(0,1-state.wrong.t/state.wrong.d))}
function drawCharacter(){const p=state.walk>0?state.walk:0,x=74+p*810,y=235-Math.sin(Math.min(1,p)*Math.PI)*55;ctx.save();ctx.translate(x,y);ctx.fillStyle="#ffe09a";ctx.strokeStyle="#745143";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,20,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-13,-14);ctx.lineTo(-20,-35);ctx.lineTo(-4,-20);ctx.moveTo(13,-14);ctx.lineTo(20,-35);ctx.lineTo(4,-20);ctx.fill();ctx.stroke();ctx.fillStyle="#334c5b";ctx.beginPath();ctx.arc(-7,-2,2.5,0,Math.PI*2);ctx.arc(7,-2,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawSparkles(){for(const p of state.sparkles){ctx.globalAlpha=Math.max(0,p.life/.8);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawHintNeighbors(){if(!state.hint||state.mode!=="playing")return;const s=currentSlot(),lv=currentLevel(),phase=Math.floor(performance.now()/500)%2,idx=phase===0?s-1:s+1;if(idx<0||idx>6||lv.miss.includes(idx)&&!state.filled[idx])return;const y=tileY-Math.sin((idx/6)*Math.PI)*52;ctx.save();ctx.strokeStyle="rgba(255,235,92,.9)";ctx.lineWidth=8;ctx.shadowColor="#fff19a";ctx.shadowBlur=18;ctx.beginPath();ctx.roundRect(tileXs[idx]-50,y-42,100,84,22);ctx.stroke();ctx.restore()}
function render(){drawBackground();drawBridge();drawHintNeighbors();drawCharacter();drawOptions();drawSparkles();if(state.toddler&&state.mode==="playing"){ctx.save();ctx.fillStyle="rgba(255,255,255,.88)";ctx.beginPath();ctx.roundRect(720,82,215,40,17);ctx.fill();ctx.fillStyle="#37647f";ctx.font="800 15px sans-serif";ctx.fillText("慢慢看，提示會來幫忙",738,108);ctx.restore()}}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function optionAt(p){for(let i=0;i<state.options.length;i++)if(Math.abs(p.x-state.options[i].homeX)<80&&Math.abs(p.y-optionY)<70)return i;return-1}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const i=optionAt(point(e));if(i>=0)choose(i)});window.addEventListener("keydown",e=>{if(["Digit1","Digit2","Digit3","Numpad1","Numpad2","Numpad3"].includes(e.code)){const n=Number(e.code.slice(-1))-1;if(n>=0&&n<3)choose(n)}if(e.code==="KeyP")setPaused(state.mode==="playing")});
ui.startBtn.addEventListener("click",begin);ui.stageBtn.addEventListener("click",playStage);ui.resumeBtn.addEventListener("click",()=>setPaused(false));ui.replayBtn.addEventListener("click",begin);ui.restartBtn.addEventListener("click",()=>{reset();hidePanels();ui.start.classList.add("show");ui.start.setAttribute("aria-hidden","false");ui.pauseBtn.textContent="⏸ 暫停"});ui.pauseBtn.addEventListener("click",()=>setPaused(state.mode==="playing"));
ui.toddlerBtn.addEventListener("click",()=>{state.toddler=!state.toddler;state.inactive=0;ui.toddlerBtn.setAttribute("aria-pressed",String(state.toddler));ui.toddlerBtn.textContent=state.toddler?"👶 幼幼：開":"👶 幼幼模式"});ui.slowBtn.addEventListener("click",()=>{state.slow=!state.slow;ui.slowBtn.setAttribute("aria-pressed",String(state.slow));ui.slowBtn.textContent=state.slow?"🐢 慢速：開":"🐢 慢慢玩"});ui.hintBtn.addEventListener("click",()=>{state.hint=!state.hint;state.inactive=0;ui.hintBtn.setAttribute("aria-pressed",String(state.hint));ui.hintBtn.textContent=state.hint?"✨ 提示：開":"✨ 提示"});ui.soundBtn.addEventListener("click",()=>{state.sound=!state.sound;ui.soundBtn.setAttribute("aria-pressed",String(state.sound));ui.soundBtn.textContent=`${state.sound?"🔊":"🔇"} 音效：${state.sound?"開":"關"}`;if(state.sound)tone(620,.09)});
document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")setPaused(true,true)});window.addEventListener("blur",()=>{if(state.mode==="playing")setPaused(true,true)});reset();requestAnimationFrame(loop);
})();
