(()=>{
"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height;
const ui={start:document.getElementById("startPanel"),stage:document.getElementById("stagePanel"),pause:document.getElementById("pausePanel"),finish:document.getElementById("finishPanel"),stageTitle:document.getElementById("stageTitle"),stageHelp:document.getElementById("stageHelp"),stageIcon:document.getElementById("stageIcon"),stageText:document.getElementById("stageText"),roundText:document.getElementById("roundText"),progress:document.getElementById("progressBar"),startBtn:document.getElementById("startBtn"),stageBtn:document.getElementById("stageBtn"),resumeBtn:document.getElementById("resumeBtn"),replayBtn:document.getElementById("replayBtn"),restartBtn:document.getElementById("restartBtn"),undoBtn:document.getElementById("undoBtn"),toddlerBtn:document.getElementById("toddlerBtn"),slowBtn:document.getElementById("slowBtn"),hintBtn:document.getElementById("hintBtn"),soundBtn:document.getElementById("soundBtn"),pauseBtn:document.getElementById("pauseBtn")};
const stages=[{name:"第一階段：跟著雲路",title:"沿著雲朵走",help:"這一段只有一條路，點相鄰雲格慢慢前進。",icon:"☁️"},{name:"第二階段：選擇岔路",title:"岔路出現了",help:"看看哪條路能到目的地；走錯可以退回來。",icon:"🛤️"},{name:"第三階段：風和彩虹",title:"認識單向風與彩虹格",help:"順著箭頭走；彩虹格走過一次會暫時消失。",icon:"🌈"}];
function L(path,branches=[],goal="garden",arrows=[],rainbow=[]){const edges=[];function add(seq){for(let i=0;i<seq.length-1;i++)edges.push([seq[i],seq[i+1]])}add(path);branches.forEach(add);return{path,edges,goal,arrows,rainbow}}
const levels=[
 L(["0,2","1,2","2,2","3,2","4,2","5,2"]),L(["0,3","0,2","1,2","1,1","2,1","3,1","4,1","4,2","5,2"],[],"wheel"),L(["0,1","1,1","2,1","2,2","3,2","4,2","5,2"],[],"pond"),L(["0,3","1,3","1,2","2,2","3,2","3,1","4,1","5,1"]),
 L(["0,2","1,2","2,2","3,2","4,2","5,2"],[["2,2","2,1","3,1"]],"wheel"),L(["0,3","1,3","2,3","2,2","3,2","4,2","5,2"],[["1,3","1,2","1,1"],["3,2","3,3","4,3"]],"pond"),L(["0,1","1,1","2,1","3,1","3,2","4,2","5,2"],[["2,1","2,2","2,3"],["3,1","4,1","5,1"]]),L(["0,3","1,3","1,2","2,2","3,2","4,2","5,2"],[["2,2","2,1","3,1","4,1"],["3,2","3,3"]],"wheel"),
 L(["0,2","1,2","2,2","3,2","4,2","5,2"],[["1,2","1,1"]],"pond",["1,2>2,2"],["3,2"]),L(["0,3","1,3","1,2","2,2","3,2","4,2","5,2"],[["2,2","2,1","3,1"]],"garden",["1,3>1,2","3,2>4,2"],["2,2"]),L(["0,1","1,1","2,1","2,2","3,2","4,2","5,2"],[["1,1","1,2","1,3"],["3,2","3,1"]],"wheel",["2,1>2,2","4,2>5,2"],["3,2"]),L(["0,3","1,3","2,3","2,2","3,2","3,1","4,1","5,1"],[["1,3","1,2","0,2"],["3,2","4,2","5,2"]],"garden",["2,3>2,2","3,2>3,1"],["2,2","3,1"])
];
const X=[150,280,410,540,670,800],Y=[125,220,315,410];
let state,last=performance.now(),audioCtx=null;
function reset(){state={mode:"ready",index:0,current:null,history:[],used:new Set(),toddler:false,slow:false,hint:false,sound:true,move:null,wobble:null,celebrate:0,inactive:0,sparkles:[]};prepare();updateHud()}
function prepare(){const lv=levels[state.index];state.current=lv.path[0];state.history=[state.current];state.used=new Set();state.move=null;state.wobble=null;state.celebrate=0;state.inactive=0}
function tone(freq,d=.12,type="sine",gain=.05){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(_){}}
const xy=id=>{const[c,r]=id.split(",").map(Number);return{x:X[c],y:Y[r]}};const key=(a,b)=>`${a}>${b}`;
function neighbors(id,forHint=false){const lv=levels[state.index],out=[];for(const[a,b]of lv.edges){if(a===id&&(!lv.arrows.includes(key(b,a))))out.push(b);if(b===id&&(!lv.arrows.includes(key(a,b))))out.push(a)}return out.filter(n=>!state.used.has(n)||n===state.current||(!forHint&&state.history.at(-2)===n))}
function validMove(from,to){return neighbors(from).includes(to)}
function shortestNext(){const lv=levels[state.index],goal=lv.path.at(-1),q=[[state.current,[]]],seen=new Set([state.current]);while(q.length){const[n,path]=q.shift();if(n===goal)return path[0]||null;for(const x of neighbors(n,true)){if(!seen.has(x)){seen.add(x);q.push([x,[...path,x]])}}}return null}
function hidePanels(){[ui.start,ui.stage,ui.pause,ui.finish].forEach(p=>{p.classList.remove("show");p.setAttribute("aria-hidden","true")})}
function showStage(){state.mode="stage";const s=stages[Math.floor(state.index/4)];ui.stageTitle.textContent=s.title;ui.stageHelp.textContent=s.help;ui.stageIcon.textContent=s.icon;hidePanels();ui.stage.classList.add("show");ui.stage.setAttribute("aria-hidden","false")}
function begin(){reset();hidePanels();showStage()}function playStage(){hidePanels();state.mode="playing";last=performance.now();canvas.focus();tone(523,.1);setTimeout(()=>tone(659,.13),90)}
function setPaused(v,automatic=false){if(!["playing","paused"].includes(state.mode))return;state.mode=v?"paused":"playing";ui.pauseBtn.textContent=v?"▶ 繼續":"⏸ 暫停";if(v){hidePanels();ui.pause.classList.add("show");ui.pause.setAttribute("aria-hidden","false");ui.pause.querySelector("p").textContent=automatic?"畫面暫停了，小雨滴會等你回來。":"小雨滴會停在原地等你。"}else{hidePanels();last=performance.now();canvas.focus()}}
function updateHud(){ui.stageText.textContent=stages[Math.min(2,Math.floor(state.index/4))].name;ui.roundText.textContent=`${Math.min(12,state.index+1)} / 12`;ui.progress.style.width=`${state.index/12*100}%`}
function go(to){if(state.mode!=="playing"||state.move||state.celebrate)return;state.inactive=0;const prev=state.history.at(-2);if(to===prev){undo();return}if(!validMove(state.current,to)){state.wobble={id:to,t:.45};tone(180,.16,"sine",.035);return}const lv=levels[state.index];if(state.used.has(to)){state.wobble={id:to,t:.45};return}const from=state.current,a=xy(from),b=xy(to);state.move={from,to,t:0,d:state.slow?0.72:0.42,a,b};tone(470,.06,"triangle",.025);if(lv.rainbow.includes(to))state.used.add(to)}
function undo(){if(state.mode!=="playing"||state.move||state.history.length<2||state.celebrate)return;const from=state.history.pop(),to=state.history.at(-1),a=xy(from),b=xy(to);if(levels[state.index].rainbow.includes(from))state.used.delete(from);state.current=to;state.move={from,to,t:0,d:state.slow?0.62:0.36,a,b,undo:true};state.inactive=0;tone(350,.07,"triangle",.025)}
function arrive(){const m=state.move;state.move=null;if(!m.undo){state.current=m.to;state.history.push(m.to)}if(state.current===levels[state.index].path.at(-1)){state.celebrate=.01;emit(...Object.values(xy(state.current)));tone(659,.14);setTimeout(()=>tone(880,.2),120)}}
function next(){state.index++;if(state.index>=levels.length){state.mode="finished";ui.progress.style.width="100%";hidePanels();ui.finish.classList.add("show");ui.finish.setAttribute("aria-hidden","false");tone(659,.15);setTimeout(()=>tone(880,.2),120);setTimeout(()=>tone(1047,.27),270);return}prepare();updateHud();if(state.index%4===0)showStage()}
function emit(x,y){for(let i=0;i<24;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*105;state.sparkles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.85,size:3+Math.random()*5,color:["#fff16d","#ff91bb","#70dda8","#8fe5ff"][i%4]})}}
function update(dt){if(state.mode!=="playing")return;state.inactive+=dt;if(state.toddler&&state.inactive>3)state.hint=true;if(state.move){state.move.t+=dt;if(state.move.t>=state.move.d)arrive()}if(state.wobble){state.wobble.t-=dt;if(state.wobble.t<=0)state.wobble=null}if(state.celebrate>0){state.celebrate+=dt/(state.slow?2.5:1.7);if(state.celebrate>=1){state.celebrate=0;next()}}for(const p of state.sparkles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=40*dt;p.life-=dt}state.sparkles=state.sparkles.filter(p=>p.life>0)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#67cbf6");g.addColorStop(.68,"#e1f8ff");g.addColorStop(1,"#dff2c6");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.43)";for(let i=0;i<7;i++){const x=35+i*160,y=92+(i%2)*52;ctx.beginPath();ctx.arc(x,y,24,0,Math.PI*2);ctx.arc(x+27,y+3,31,0,Math.PI*2);ctx.arc(x+55,y+7,22,0,Math.PI*2);ctx.fill()}ctx.fillStyle="rgba(78,160,105,.24)";ctx.fillRect(0,465,W,75)}
function drawEdge(a,b){const A=xy(a),B=xy(b),lv=levels[state.index],arrow=lv.arrows.includes(key(a,b))?1:lv.arrows.includes(key(b,a))?-1:0;ctx.save();ctx.strokeStyle="rgba(255,255,255,.78)";ctx.lineWidth=13;ctx.lineCap="round";ctx.setLineDash([9,13]);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.setLineDash([]);if(arrow){const from=arrow===1?A:B,to=arrow===1?B:A,mx=(from.x+to.x)/2,my=(from.y+to.y)/2,ang=Math.atan2(to.y-from.y,to.x-from.x);ctx.translate(mx,my);ctx.rotate(ang);ctx.fillStyle="#f5bb3f";ctx.strokeStyle="white";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-12,-13);ctx.lineTo(-12,13);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}
function drawCloudNode(id){const p=xy(id),lv=levels[state.index],goal=id===lv.path.at(-1),rainbow=lv.rainbow.includes(id),used=state.used.has(id)&&id!==state.current,hint=state.hint&&id===shortestNext(),wobble=state.wobble?.id===id?Math.sin(state.wobble.t*60)*7:0;ctx.save();ctx.translate(p.x+wobble,p.y);ctx.globalAlpha=used?0.28:1;ctx.shadowColor=hint?"#ffe76c":"rgba(31,93,128,.2)";ctx.shadowBlur=hint?25:10;ctx.fillStyle=rainbow?"#fff5a7":"#fff";ctx.strokeStyle=hint?"#ffd348":rainbow?"#ff94bd":"#86bed7";ctx.lineWidth=hint?7:4;ctx.beginPath();ctx.arc(-24,5,23,0,Math.PI*2);ctx.arc(0,-8,29,0,Math.PI*2);ctx.arc(28,5,23,0,Math.PI*2);ctx.arc(0,12,38,0,Math.PI*2);ctx.fill();ctx.stroke();if(rainbow){ctx.strokeStyle="#ff708b";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,9,20,Math.PI,0);ctx.stroke();ctx.strokeStyle="#66cdef";ctx.beginPath();ctx.arc(0,9,13,Math.PI,0);ctx.stroke()}if(goal){ctx.fillStyle="#2d6684";ctx.font="800 14px sans-serif";ctx.textAlign="center";ctx.fillText(lv.goal==="garden"?"花園":lv.goal==="wheel"?"水車":"池塘",0,48)}ctx.restore()}
function drawGoalEffect(){const lv=levels[state.index],p=xy(lv.path.at(-1)),t=state.celebrate;if(lv.goal==="garden"){for(let i=-1;i<=1;i++){ctx.save();ctx.translate(p.x+i*22,p.y-45);ctx.strokeStyle="#3b9c65";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,20);ctx.lineTo(0,-5-Math.sin(t*Math.PI)*15);ctx.stroke();ctx.fillStyle=["#ff8caf","#ffe064","#9f8bea"][i+1];ctx.beginPath();ctx.arc(0,-8-Math.sin(t*Math.PI)*15,8+8*t,0,Math.PI*2);ctx.fill();ctx.restore()}}else if(lv.goal==="wheel"){ctx.save();ctx.translate(p.x,p.y-53);ctx.rotate(t*Math.PI*4);ctx.strokeStyle="#a67453";ctx.lineWidth=5;for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-28);ctx.stroke()}ctx.beginPath();ctx.arc(0,0,28,0,Math.PI*2);ctx.stroke();ctx.restore()}else{ctx.save();ctx.strokeStyle=`rgba(84,190,235,${1-t*.7})`;ctx.lineWidth=5;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(p.x,p.y-35,20+t*(25+i*18),7+t*(8+i*4),0,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function drawDrop(){let p=xy(state.current);if(state.move){const m=state.move,q=Math.min(1,m.t/m.d),e=1-Math.pow(1-q,3);p={x:m.a.x+(m.b.x-m.a.x)*e,y:m.a.y+(m.b.y-m.a.y)*e-28*Math.sin(q*Math.PI)}}ctx.save();ctx.translate(p.x,p.y-5);ctx.fillStyle="#4fc7f3";ctx.strokeStyle="#287ea5";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-32);ctx.bezierCurveTo(30,2,24,31,0,34);ctx.bezierCurveTo(-24,31,-30,2,0,-32);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(-8,5,5,0,Math.PI*2);ctx.arc(8,5,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#244b61";ctx.beginPath();ctx.arc(-7,6,2.5,0,Math.PI*2);ctx.arc(9,6,2.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#244b61";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,13,7,.15,Math.PI-.15);ctx.stroke();ctx.restore()}
function drawSparkles(){for(const p of state.sparkles){ctx.globalAlpha=Math.max(0,p.life/.85);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function render(){drawBackground();const lv=levels[state.index];lv.edges.forEach(e=>drawEdge(e[0],e[1]));[...new Set(lv.edges.flat())].forEach(drawCloudNode);if(state.celebrate)drawGoalEffect();drawDrop();drawSparkles();if(state.toddler&&state.mode==="playing"){ctx.save();ctx.fillStyle="rgba(255,255,255,.88)";ctx.beginPath();ctx.roundRect(20,472,225,40,17);ctx.fill();ctx.fillStyle="#37647f";ctx.font="800 15px sans-serif";ctx.fillText("停一下，下一格會發光",37,498);ctx.restore()}}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}function nodeAt(p){const ids=[...new Set(levels[state.index].edges.flat())];return ids.find(id=>{const q=xy(id);return Math.hypot(p.x-q.x,p.y-q.y)<55})||null}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const id=nodeAt(point(e));if(id)go(id)});ui.undoBtn.addEventListener("click",undo);ui.startBtn.addEventListener("click",begin);ui.stageBtn.addEventListener("click",playStage);ui.resumeBtn.addEventListener("click",()=>setPaused(false));ui.replayBtn.addEventListener("click",begin);ui.restartBtn.addEventListener("click",()=>{reset();hidePanels();ui.start.classList.add("show");ui.start.setAttribute("aria-hidden","false");ui.pauseBtn.textContent="⏸ 暫停"});ui.pauseBtn.addEventListener("click",()=>setPaused(state.mode==="playing"));
ui.toddlerBtn.addEventListener("click",()=>{state.toddler=!state.toddler;state.inactive=0;ui.toddlerBtn.setAttribute("aria-pressed",String(state.toddler));ui.toddlerBtn.textContent=state.toddler?"👶 幼幼：開":"👶 幼幼模式"});ui.slowBtn.addEventListener("click",()=>{state.slow=!state.slow;ui.slowBtn.setAttribute("aria-pressed",String(state.slow));ui.slowBtn.textContent=state.slow?"🐢 慢速：開":"🐢 慢慢玩"});ui.hintBtn.addEventListener("click",()=>{state.hint=!state.hint;state.inactive=0;ui.hintBtn.setAttribute("aria-pressed",String(state.hint));ui.hintBtn.textContent=state.hint?"✨ 提示：開":"✨ 提示"});ui.soundBtn.addEventListener("click",()=>{state.sound=!state.sound;ui.soundBtn.setAttribute("aria-pressed",String(state.sound));ui.soundBtn.textContent=`${state.sound?"🔊":"🔇"} 音效：${state.sound?"開":"關"}`;if(state.sound)tone(620,.09)});
document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")setPaused(true,true)});window.addEventListener("blur",()=>{if(state.mode==="playing")setPaused(true,true)});reset();requestAnimationFrame(loop);
})();
