"use strict";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d");
const ui={chapter:document.querySelector("#chapter"),name:document.querySelector("#levelName"),instruction:document.querySelector("#instruction"),progress:document.querySelector("#progressFill"),hint:document.querySelector("#hintBtn"),picker:document.querySelector("#levelPicker"),toddler:document.querySelector("#toddlerBtn"),slow:document.querySelector("#slowBtn"),sound:document.querySelector("#soundBtn"),pause:document.querySelector("#pauseBtn"),restart:document.querySelector("#restartBtn"),pauseOverlay:document.querySelector("#pauseOverlay"),resume:document.querySelector("#resumeBtn"),finish:document.querySelector("#finishOverlay"),again:document.querySelector("#playAgainBtn")};
const spirits={sun:{name:"墨鏡小太陽",icon:"☀️",color:"#ffd65c",freq:523},moon:{name:"睡帽小月亮",icon:"🌙",color:"#aa93ef",freq:392},rain:{name:"雨傘小水滴",icon:"💧",color:"#64c9f2",freq:330},rainbow:{name:"彩虹精靈",icon:"🌈",color:"#f58fbd",freq:659},snow:{name:"雪花精靈",icon:"❄️",color:"#bcefff",freq:440}};
const levels=[
 {name:"早安太陽",cards:["sun","moon","moon","sun"]},{name:"滴答雨聲",cards:["rain","sun","rain","sun"]},{name:"月光晚安",cards:["moon","rainbow","moon","rainbow"]},
 {name:"彩虹午後",cards:["rainbow","sun","rain","sun","rainbow","rain"]},{name:"星夜細雨",cards:["moon","rain","snow","rain","moon","snow"]},{name:"雲朵天氣站",cards:["sun","snow","rainbow","snow","sun","rainbow"]},
 {name:"四季轉轉",cards:["rain","sun","moon","snow","moon","rain","snow","sun"]},{name:"月下彩虹",cards:["rainbow","moon","snow","rain","moon","rainbow","rain","snow"]},{name:"晴雨魔法",cards:["sun","rainbow","rain","snow","rain","sun","snow","rainbow"]},
 {name:"五色天空",cards:["sun","rain","moon","snow","rainbow","snow","sun","rainbow","rain","moon"]},{name:"天氣嘉年華",cards:["rainbow","moon","rain","sun","snow","sun","rainbow","snow","moon","rain"]},{name:"雲端大捉迷藏",cards:["snow","sun","rainbow","moon","rain","moon","rain","snow","sun","rainbow"]}
];
const chapters=["第一章 · 兩對精靈","第二章 · 三對精靈","第三章 · 四對精靈","第四章 · 五對精靈"];
const bg=new Image();bg.src="assets/weather-observatory.png";
let levelIndex=0,cards=[],first=null,locked=false,toddler=false,slow=false,soundOn=true,paused=false,hintIndices=[],hintUntil=0,lastAction=performance.now(),weather="",weatherUntil=0,weatherStart=0,success=false,timers=[],particles=[],audioCtx=null;
function current(){return levels[levelIndex]}
function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function later(fn,ms){const id=setTimeout(()=>{timers=timers.filter(x=>x!==id);fn()},ms);timers.push(id);return id}
function chapterIndex(){const n=current().cards.length;return n===4?0:n===6?1:n===8?2:3}
function layout(count){const cols=count<=4?2:count<=6?3:count<=8?4:5,rows=2,w=count<=4?190:count<=6?170:count<=8?150:128,h=count<=6?135:118,gx=count<=4?45:count<=6?28:count<=8?25:22,gy=24,total=cols*w+(cols-1)*gx,startX=(960-total)/2+w/2,startY=count<=4?220:205;return Array.from({length:count},(_,i)=>({x:startX+(i%cols)*(w+gx),y:startY+Math.floor(i/cols)*(h+gy),w,h}))}
function setup(){clearTimers();cards=current().cards.map((type,i)=>({type,faceUp:false,matched:false,...layout(current().cards.length)[i],wobbleUntil:0}));first=null;locked=false;hintIndices=[];hintUntil=0;weather="";success=false;lastAction=performance.now();ui.instruction.textContent="翻開兩朵雲，找出相同的天氣精靈";updateUI()}
function updateUI(){const matched=cards.filter(c=>c.matched).length/2,total=cards.length/2;ui.chapter.textContent=chapters[chapterIndex()];ui.name.textContent=`${levelIndex+1}/12 ${current().name}`;ui.progress.style.width=`${total?matched/total*100:0}%`;[...ui.picker.children].forEach((b,i)=>b.classList.toggle("active",i===levelIndex))}
function makePicker(){levels.forEach((l,i)=>{const b=document.createElement("button");b.innerHTML=`${i+1}<small>${l.name}</small>`;b.addEventListener("click",()=>{levelIndex=i;ui.finish.classList.add("hidden");setup()});ui.picker.appendChild(b)})}
function tone(freq,duration=.32,type="sine",vol=.055){if(!soundOn)return;audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();const n=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,n);g.gain.setValueAtTime(vol,n);g.gain.exponentialRampToValueAtTime(.001,n+duration);o.connect(g).connect(audioCtx.destination);o.start(n);o.stop(n+duration)}
function spring(){tone(145,.2,"triangle",.035)}
function burst(x,y,color,count=22){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*110;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-35,life:1,color,r:2+Math.random()*5})}}
function showHint(){const hidden=cards.filter(c=>!c.matched);if(!hidden.length)return;if(first){hintIndices=[cards.findIndex(c=>!c.matched&&!c.faceUp&&c.type===first.type)]}else{const c=hidden[0];hintIndices=cards.map((x,i)=>!x.matched&&x.type===c.type?i:-1).filter(i=>i>=0)}hintUntil=performance.now()+2500;tone(620,.18)}
function flip(index){if(paused||locked||success)return;const c=cards[index];if(!c||c.matched||c.faceUp)return;c.faceUp=true;lastAction=performance.now();tone(spirits[c.type].freq,.18);burst(c.x,c.y,spirits[c.type].color,10);if(!first){first=c;ui.instruction.textContent="再找一個相同的精靈";if(toddler){hintIndices=[cards.findIndex(x=>x!==c&&!x.matched&&x.type===c.type)];hintUntil=performance.now()+999999}return}locked=true;if(first.type===c.type){const matchedType=c.type;first.matched=true;c.matched=true;weather=matchedType;weatherStart=performance.now();weatherUntil=weatherStart+(slow?2600:1800);burst(first.x,first.y,spirits[matchedType].color,30);burst(c.x,c.y,spirits[matchedType].color,30);tone(spirits[matchedType].freq*1.5,.45);ui.instruction.textContent=`找到${spirits[matchedType].name}！`;first=null;hintIndices=[];updateUI();later(()=>{locked=false;if(cards.every(x=>x.matched))complete();else ui.instruction.textContent="繼續找下一對天氣精靈"},slow?1200:750)}else{const a=first,b=c;a.wobbleUntil=b.wobbleUntil=performance.now()+500;spring();ui.instruction.textContent="不一樣也沒關係，雲朵再藏好";later(()=>{a.faceUp=false;b.faceUp=false;first=null;locked=false;hintIndices=[];ui.instruction.textContent="再翻兩朵雲試試看"},slow?1500:900)}}
function complete(){success=true;ui.instruction.textContent="全部找到！天空精靈一起轉圈！";Object.values(spirits).forEach((s,i)=>later(()=>tone(s.freq,.45),i*110));later(advance,slow?3400:2300)}
function advance(){if(levelIndex===11){ui.finish.classList.remove("hidden");return}levelIndex++;setup()}
function setPaused(v){paused=v;ui.pauseOverlay.classList.toggle("hidden",!v);ui.pause.textContent=v?"繼續":"暫停";if(v){clearTimers();if(locked){cards.filter(c=>c.faceUp&&!c.matched).forEach(c=>c.faceUp=false);first=null;locked=false}if(success)success=false}else{if(cards.every(c=>c.matched))complete();else ui.instruction.textContent="翻開兩朵雲，找出相同的天氣精靈"}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*540/r.height}}
canvas.addEventListener("pointerdown",e=>{const p=point(e);for(let i=cards.length-1;i>=0;i--){const c=cards[i];if(Math.abs(p.x-c.x)<=c.w/2+10&&Math.abs(p.y-c.y)<=c.h/2+12){flip(i);break}}});ui.hint.addEventListener("click",showHint);ui.toddler.addEventListener("click",()=>{toddler=!toddler;ui.toddler.textContent=`幼幼模式：${toddler?"開":"關"}`;ui.toddler.setAttribute("aria-pressed",String(toddler));hintIndices=[];if(first&&toddler){hintIndices=[cards.findIndex(c=>c!==first&&!c.matched&&c.type===first.type)];hintUntil=performance.now()+999999}});ui.slow.addEventListener("click",()=>{slow=!slow;ui.slow.textContent=`慢慢玩：${slow?"開":"關"}`;ui.slow.setAttribute("aria-pressed",String(slow))});ui.sound.addEventListener("click",()=>{soundOn=!soundOn;ui.sound.textContent=`音效：${soundOn?"開":"關"}`;ui.sound.setAttribute("aria-pressed",String(soundOn))});ui.pause.addEventListener("click",()=>setPaused(!paused));ui.resume.addEventListener("click",()=>setPaused(false));ui.restart.addEventListener("click",setup);ui.again.addEventListener("click",()=>{ui.finish.classList.add("hidden");levelIndex=0;setup()});document.addEventListener("visibilitychange",()=>{if(document.hidden)setPaused(true)});window.addEventListener("blur",()=>setPaused(true));
function cloudPath(x,y,w,h){ctx.beginPath();ctx.moveTo(x-w*.42,y+h*.32);ctx.bezierCurveTo(x-w*.62,y+h*.15,x-w*.53,y-h*.18,x-w*.28,y-h*.15);ctx.bezierCurveTo(x-w*.2,y-h*.48,x+w*.13,y-h*.55,x+w*.25,y-h*.22);ctx.bezierCurveTo(x+w*.53,y-h*.27,x+w*.62,y+h*.1,x+w*.42,y+h*.31);ctx.closePath()}
function drawSpirit(c,t){const s=spirits[c.type],spin=c.matched?Math.sin(t/260)*.13:0;ctx.save();ctx.translate(c.x,c.y);ctx.rotate(spin);ctx.shadowColor=s.color;ctx.shadowBlur=20;ctx.font=`${Math.min(62,c.h*.48)}px sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s.icon,0,-5);if(c.type==="sun"){ctx.strokeStyle="#283251";ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(-28,-17,23,14,5);ctx.roundRect(5,-17,23,14,5);ctx.moveTo(-5,-10);ctx.lineTo(5,-10);ctx.stroke()}if(c.type==="moon"){ctx.fillStyle="#7183db";ctx.beginPath();ctx.moveTo(-8,-37);ctx.lineTo(15,-69);ctx.lineTo(27,-31);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(16,-67,7,0,Math.PI*2);ctx.fill()}if(c.type==="rain"){ctx.font="32px sans-serif";ctx.fillText("☂️",24,-25)}ctx.shadowBlur=0;ctx.fillStyle="#334274";ctx.font="900 14px sans-serif";ctx.fillText(s.name,0,c.h*.34);ctx.restore()}
function drawCard(c,i,t){const autoTarget=first?cards.findIndex(x=>x!==first&&!x.matched&&!x.faceUp&&x.type===first.type):cards.findIndex(x=>!x.matched&&!x.faceUp),hinted=(hintIndices.includes(i)&&t<hintUntil)||(t-lastAction>5000&&i===autoTarget),wobble=t<c.wobbleUntil?Math.sin(t*.08)*7:0;ctx.save();ctx.translate(wobble,0);if(c.faceUp||c.matched){cloudPath(c.x,c.y,c.w,c.h);ctx.fillStyle=c.matched?"rgba(255,255,255,.72)":"rgba(255,255,255,.94)";ctx.shadowColor=spirits[c.type].color;ctx.shadowBlur=c.matched?25:14;ctx.fill();ctx.strokeStyle="rgba(255,255,255,.9)";ctx.lineWidth=4;ctx.stroke();drawSpirit(c,t)}else{cloudPath(c.x,c.y,c.w,c.h);ctx.fillStyle="#effaff";ctx.shadowColor=hinted?"#fff189":"rgba(72,96,156,.26)";ctx.shadowBlur=hinted?28:12;ctx.fill();ctx.strokeStyle=hinted?"#fff3a3":"rgba(255,255,255,.9)";ctx.lineWidth=hinted?7:4;ctx.stroke();ctx.fillStyle="#8fcfe8";ctx.font=`900 ${Math.min(38,c.h*.3)}px sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("?",c.x,c.y+3)}ctx.restore()}
function drawWeather(t){if(t>weatherUntil)return;const age=Math.min(1,(t-weatherStart)/350),fade=Math.min(age,(weatherUntil-t)/350);ctx.save();ctx.globalAlpha=Math.max(0,fade*.5);if(weather==="sun"){ctx.fillStyle="#ffe178";ctx.fillRect(0,0,960,540);ctx.translate(480,250);ctx.strokeStyle="#fff4a9";ctx.lineWidth=14;for(let i=0;i<12;i++){ctx.rotate(Math.PI/6);ctx.beginPath();ctx.moveTo(160,0);ctx.lineTo(330,0);ctx.stroke()}}if(weather==="moon"){ctx.fillStyle="#26306f";ctx.fillRect(0,0,960,540);ctx.strokeStyle="#fff";ctx.lineWidth=5;const x=120+(t-weatherStart)*.5;ctx.beginPath();ctx.moveTo(x,75);ctx.lineTo(x+90,125);ctx.stroke()}if(weather==="rain"){ctx.fillStyle="#78c9ef";ctx.fillRect(0,0,960,540);ctx.strokeStyle="#dff8ff";ctx.lineWidth=4;for(let i=0;i<28;i++){const x=(i*83+t*.18)%1000,y=(i*47+t*.28)%520;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-12,y+28);ctx.stroke()}}if(weather==="rainbow"){ctx.strokeStyle="#ff7197";ctx.lineWidth=18;["#ff7197","#ffd568","#72d993","#66c9f3","#a47bea"].forEach((color,i)=>{ctx.strokeStyle=color;ctx.beginPath();ctx.arc(480,450,270-i*18,Math.PI,Math.PI*2);ctx.stroke()})}if(weather==="snow"){ctx.fillStyle="white";for(let i=0;i<35;i++){const x=(i*97+t*.05)%980,y=(i*53+t*.12)%550;ctx.beginPath();ctx.arc(x,y,3+i%4,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function draw(t){requestAnimationFrame(draw);if(paused)return;ctx.clearRect(0,0,960,540);if(bg.complete)ctx.drawImage(bg,0,0,960,540);else{ctx.fillStyle="#b9e9ff";ctx.fillRect(0,0,960,540)}drawWeather(t);cards.forEach((c,i)=>drawCard(c,i,t));particles.forEach(p=>{p.x+=p.vx/60;p.y+=p.vy/60;p.vy+=.75;p.life-=.018;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0)}
makePicker();setup();requestAnimationFrame(draw);
