import AnimalSnackGame from './AnimalSnackGame.js';
import {CloudGlideSession,CLOUD_GLIDE_CONFIG,CLOUD_GLIDE_PHASES} from '../data/CloudGlideData.js';

const RING_Y=[210,330,455,255,510,375,185,430,290,540,350,225];

export default class CloudGlideGame extends AnimalSnackGame {
    constructor(){super('CloudGlideGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new CloudGlideSession();this.holding=false;this.slow=true;this.helper=true;this.velocity=0;this.spawnClock=0;this.spawnIndex=0;this.invincible=0;this.flyers=[];
        this.drawSky();this.drawHud();this.player=this.drawPaperDollGlider(350,CLOUD_GLIDE_CONFIG.startY).setDepth(55);this.guideArrow=this.add.triangle(475,360,0,-16,32,0,0,16,0xffd860,.8).setDepth(54).setVisible(false);this.bindInput();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyDownHandler);this.input.keyboard?.off('keyup',this.keyUpHandler);this.stopTones();});
    }
    drawSky(){const g=this.add.graphics();g.fillGradientStyle(0x65b6df,0x8fd2eb,0xdff5f7,0xf7d9aa,1).fillRect(0,0,1280,720);g.fillStyle(0x9fc9d3,.55).fillTriangle(0,560,200,260,420,560).fillTriangle(830,560,1060,220,1280,560);g.fillStyle(0xffffff,.75).fillTriangle(145,342,200,260,260,342).fillTriangle(1000,310,1060,220,1125,310);g.fillStyle(0xe1f3e8).fillRect(0,610,1280,110);for(let i=0;i<18;i++){const x=(i*181+40)%1280,y=125+(i*79)%450;this.add.circle(x,y,3+i%4,0xffffff,.65).setDepth(2);}this.backClouds=[];for(let i=0;i<7;i++){const c=this.drawCloud(100+i*210,150+(i%3)*140,.22).setDepth(4);this.backClouds.push(c);}}
    drawHud(){this.panel(640,43,1248,66,0xf8fdff,0xcde9f2,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x4c8dac).setDepth(81);this.text(390,40,'雲端滑翔・幼童版',30,'#285d76').setDepth(81);this.phaseText=this.text(676,43,'第 1 段',17,'#62889a').setDepth(81);this.soundButton=this.button(925,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xdceff4,'#285d76').setDepth(81);this.button(1090,43,170,43,'暫停 / 說明',()=>this.pauseGame(),0xdceff4,'#285d76').setDepth(81);
        this.panel(142,335,235,430,0xf8fdff,0xcde9f2,23).setDepth(65);this.text(142,132,'天空小任務',22,'#285d76').setDepth(66);this.progressText=this.text(142,195,'0 / 12',35,'#285d76').setDepth(66);this.text(142,232,'穿過順風圈',17,'#66899a').setDepth(66);this.starText=this.text(142,283,'星星 0',22,'#9a7540').setDepth(66);this.tipText=this.text(142,340,'',16,'#66899a').setDepth(66);this.hintButton=this.button(142,420,190,48,'✨ 方向提示',()=>this.showHint(),0xe5bd65,'#5c4d2e').setDepth(67);this.slowButton=this.button(142,480,190,48,'慢速飛行：開',()=>this.toggleSlow(),0xdceff4,'#285d76').setDepth(67);this.helperButton=this.button(142,540,190,48,'箭頭提示：開',()=>this.toggleHelper(),0xdceff4,'#285d76').setDepth(67);this.feedback=this.text(690,104,'按住畫面上升，放開就會慢慢下降。',20,'#315f74').setDepth(81);this.text(720,692,'按住上升・放開下降｜穿過大雲圈｜碰到雲朵只會安全彈開',16,'#416f83').setDepth(70);this.refresh();}
    drawCloud(x,y,alpha=1){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0xffffff,alpha).fillEllipse(0,10,145,65).fillCircle(-47,-7,35).fillCircle(0,-25,49).fillCircle(49,-5,37);g.fillStyle(0xcfeaf1,alpha*.45).fillEllipse(5,28,126,27);c.add(g);return c;}
    drawPaperDollGlider(x,y){const c=this.add.container(x,y),wing=this.add.graphics(),body=this.add.graphics();wing.fillStyle(0xf4d46b).fillTriangle(-18,-4,-108,-45,-77,38).fillTriangle(18,-4,108,-45,77,38);wing.fillStyle(0x63b6cb).fillTriangle(-24,3,-91,-32,-68,25).fillTriangle(24,3,91,-32,68,25);body.fillStyle(0x5c4037).fillCircle(0,-34,27);body.fillStyle(0xf2c49c).fillCircle(0,-23,23);body.fillStyle(0x3f3333).fillCircle(-8,-26,3).fillCircle(8,-26,3);body.fillStyle(0x5aa6b8).fillRoundedRect(-22,0,44,54,15);body.fillStyle(0xf0a64e).fillTriangle(-18,12,-56,34,-17,27).fillTriangle(18,12,56,34,17,27);body.fillStyle(0x6b4c43).fillRoundedRect(-24,-54,48,15,7);body.fillStyle(0xa8e3ed,.75).fillRoundedRect(-18,-51,36,10,5);body.fillStyle(0xe05f56).fillTriangle(19,-5,57,4,20,13);const smile=this.add.arc(0,-17,8,7,20,160,false,0x5a4038).setStrokeStyle(2,0x5a4038);c.add([wing,body,smile]);return c;}
    drawRing(x,y){const c=this.add.container(x,y).setDepth(35),glow=this.add.circle(0,0,CLOUD_GLIDE_CONFIG.ringRadius+12,0xffe274,.18),g=this.add.graphics();g.lineStyle(18,0xffffff,.85).strokeCircle(0,0,CLOUD_GLIDE_CONFIG.ringRadius);g.lineStyle(9,0xffd45c,.95).strokeCircle(0,0,CLOUD_GLIDE_CONFIG.ringRadius);const star=this.add.star(0,0,5,15,32,0xffdd5e).setStrokeStyle(3,0xffffff);c.add([glow,g,star]);this.tweens.add({targets:glow,scale:1.15,alpha:.04,duration:700,yoyo:true,repeat:-1});c.kind='ring';c.resolved=false;c.star=star;return c;}
    spawnRing(){const y=RING_Y[this.spawnIndex%RING_Y.length],ring=this.drawRing(1360,y);this.flyers.push(ring);this.spawnIndex+=1;if(this.session.phaseIndex>0&&this.spawnIndex%2===0)this.spawnSoftCloud(y<350?500:215);}
    spawnSoftCloud(y){const cloud=this.drawCloud(1510,y,.92).setDepth(38);cloud.kind='cloud';cloud.resolved=false;cloud.setScale(1.05);this.flyers.push(cloud);}
    bindInput(){this.input.on('pointerdown',pointer=>{if(this.mode==='playing'&&pointer.y>85)this.holding=true;});this.input.on('pointerup',()=>{this.holding=false;});this.keyDownHandler=e=>{if(e.repeat)return;if(['Space','ArrowUp','KeyW'].includes(e.code)&&this.mode==='playing')this.holding=true;else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyS')this.toggleSlow();else if(e.code==='KeyA')this.toggleHelper();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.keyUpHandler=e=>{if(['Space','ArrowUp','KeyW'].includes(e.code))this.holding=false;};this.input.keyboard?.on('keydown',this.keyDownHandler);this.input.keyboard?.on('keyup',this.keyUpHandler);}
    update(_time,delta){if(this.mode!=='playing')return;const dt=Math.min(.04,delta/1000),speed=this.slow?CLOUD_GLIDE_CONFIG.slowSpeed:CLOUD_GLIDE_CONFIG.normalSpeed;this.velocity+=this.holding?-520*dt:330*dt;this.velocity=Phaser.Math.Clamp(this.velocity,-205,190);this.player.y+=this.velocity*dt;if(this.player.y<CLOUD_GLIDE_CONFIG.minY){this.player.y=CLOUD_GLIDE_CONFIG.minY;this.velocity=65;}if(this.player.y>CLOUD_GLIDE_CONFIG.maxY){this.player.y=CLOUD_GLIDE_CONFIG.maxY;this.velocity=-85;}this.player.angle=Phaser.Math.Clamp(this.velocity*.055,-10,10);this.invincible=Math.max(0,this.invincible-dt);this.spawnClock+=delta;if(this.spawnClock>(this.slow?1750:1450)&&this.flyers.filter(v=>v.kind==='ring').length<2){this.spawnClock=0;this.spawnRing();}this.flyers.forEach(view=>{view.x-=speed*dt;if(view.kind==='ring')this.checkRing(view);else this.checkCloud(view);});this.flyers=this.flyers.filter(view=>{if(view.x<-150){view.destroy();return false;}return view.active;});this.backClouds.forEach(c=>{c.x-=18*dt;if(c.x<-120)c.x=1400;});this.updateGuide();}
    checkRing(ring){if(ring.resolved)return;if(Math.abs(ring.x-this.player.x)<42&&Math.abs(ring.y-this.player.y)<72){ring.resolved=true;const result=this.session.passRing(true);ring.star.setVisible(false);this.tone('correct');this.feedback.setText('穿過順風圈，星星亮起來了！');this.sparkles(ring.x,ring.y);this.tweens.add({targets:ring,scale:1.35,alpha:0,duration:480,onComplete:()=>ring.destroy()});this.refresh();if(result==='complete'){this.mode='finishing';this.time.delayedCall(650,()=>this.finish());}}else if(ring.x<this.player.x-80){ring.resolved=true;this.session.missRing();this.feedback.setText('這個雲圈飛過去了，下一個會再來，不扣分～');this.tone('hint');this.refresh();}}
    checkCloud(cloud){if(cloud.resolved||this.invincible>0)return;if(Math.abs(cloud.x-this.player.x)<82&&Math.abs(cloud.y-this.player.y)<55){cloud.resolved=true;this.invincible=1;this.session.bumpCloud();this.velocity=cloud.y>this.player.y?-130:130;this.feedback.setText('噗啾！軟雲把小探險家安全彈開了。');this.tone('hint');this.tweens.add({targets:this.player,x:this.player.x-18,angle:-12,duration:120,yoyo:true,repeat:1});this.tweens.add({targets:cloud,scale:1.25,alpha:.25,duration:350,onComplete:()=>cloud.destroy()});this.refresh();}}
    updateGuide(){const ring=this.flyers.filter(v=>v.active&&v.kind==='ring'&&!v.resolved&&v.x>this.player.x).sort((a,b)=>a.x-b.x)[0];if(!this.helper||!ring){this.guideArrow.setVisible(false);return;}this.guideArrow.setVisible(true).setPosition(475,this.player.y);this.guideArrow.rotation=Phaser.Math.Angle.Between(475,this.player.y,ring.x,ring.y);}
    showHint(){if(this.mode!=='playing'||!this.session.hint())return;this.helper=true;this.helperButton.label.setText('箭頭提示：開');this.feedback.setText('看金色箭頭，對準最近的順風圈！');this.tone('hint');this.refresh();const ring=this.flyers.find(v=>v.kind==='ring'&&!v.resolved);if(ring)this.tweens.add({targets:ring,scale:1.12,duration:180,yoyo:true,repeat:3});}
    toggleSlow(){if(this.mode!=='playing')return;this.slow=!this.slow;this.slowButton.label.setText(this.slow?'慢速飛行：開':'慢速飛行：關');this.feedback.setText(this.slow?'雲圈慢下來了，慢慢飛。':'一般速度開啟，準備滑翔！');}
    toggleHelper(){if(this.mode!=='playing')return;this.helper=!this.helper;this.helperButton.label.setText(this.helper?'箭頭提示：開':'箭頭提示：關');this.feedback.setText(this.helper?'箭頭會指向最近的順風圈。':'箭頭收起來，自己看天空找方向！');}
    refresh(){this.progressText?.setText(`${this.session.rings} / ${CLOUD_GLIDE_CONFIG.targetRings}`);this.starText?.setText(`星星 ${this.session.stars}`);this.phaseText?.setText(`第 ${this.session.phaseIndex+1} / ${CLOUD_GLIDE_PHASES.length} 段・${this.session.phase.name}`);this.tipText?.setText(`${this.session.phase.guide}\n\n漏過 ${this.session.missed} 次\n碰軟雲 ${this.session.cloudBumps} 次`);}
    sparkles(x,y){for(let i=0;i<11;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd85d:0xffffff).setDepth(75),a=i/11*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*90,y:y+Math.sin(a)*70,alpha:0,angle:150,duration:520,onComplete:()=>s.destroy()});}}
    showIntro(){const o=this.makeOverlay('雲端滑翔準備起飛！','小探險家會自動向前飛。\n按住畫面會上升，放開後會慢慢下降；\n對準大大的順風圈，收集 12 顆天空星星。');o.add(this.text(640,410,'碰到軟雲或漏過雲圈都不失敗，下一個會再來。',19,'#66899a'));o.add(this.button(640,500,290,60,'展開滑翔翼！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();this.time.delayedCall(450,()=>this.spawnRing());},0x4c8dac));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.holding=false;this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('在雲朵上休息一下','按住畫面、空白鍵或方向鍵上可以上升，放開就下降。\n穿過大順風圈即可前進；碰軟雲與漏過都不扣分。\nH 顯示方向，S 切換速度，A 切換箭頭。');o.add(this.button(640,415,270,55,'繼續滑翔',()=>this.resumeGame(),0x4c8dac));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xdceff4,'#285d76'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    finish(){this.mode='finished';this.holding=false;this.tone('finish');const o=this.makeOverlay('十二個順風圈全部穿過！',`雲端滑翔完成！\n收集星星 ${this.session.stars} 顆　漏過 ${this.session.missed} 次\n碰到軟雲 ${this.session.cloudBumps} 次　使用提示 ${this.session.hints} 次`);o.add(this.text(640,400,'這是幼童試玩，不寫入正式獎勵、裝備或成就。',18,'#66899a'));o.add(this.button(500,490,230,58,'再飛一次',()=>this.restart(),0x4c8dac));o.add(this.button(780,490,230,58,'返回遊戲列表',()=>this.leave(),0xe5bd65,'#5c4d2e'));}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
