import AnimalSnackGame from './AnimalSnackGame.js';
import {DinosaurValleySession,DINOSAUR_RUN_CONFIG,DINOSAUR_RUN_PHASES} from '../data/DinosaurValleyData.js';

const PATTERN=['friend','egg','rock','footprint','friend','log','egg','friend','mud','footprint','friend','rock'];

export default class DinosaurValleyGame extends AnimalSnackGame {
    constructor(){super('DinosaurValleyGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new DinosaurValleySession();this.slow=true;this.helper=true;this.velocityY=0;this.grounded=true;this.spawnClock=0;this.spawnIndex=0;this.slowedLeft=0;this.invincible=0;this.objects=[];
        this.drawValley();this.drawHud();this.player=this.drawExplorer(330,DINOSAUR_RUN_CONFIG.groundY-63).setDepth(58);this.helperDino=this.drawDinosaur(242,DINOSAUR_RUN_CONFIG.groundY-38,0x69ae72).setDepth(56).setScale(.7).setAlpha(.85);this.guideArrow=this.add.triangle(455,430,0,-15,32,0,0,15,0xffd65c,.9).setDepth(57).setVisible(false);this.bindInput();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawValley(){const g=this.add.graphics();g.fillGradientStyle(0x79c7df,0xa8ddeb,0xf6d28a,0xc88055,1).fillRect(0,0,1280,720);g.fillStyle(0x7d7188,.55).fillTriangle(0,420,255,105,510,420).fillTriangle(720,425,1020,75,1280,425);g.fillStyle(0xe6d3ad,.8).fillTriangle(185,190,255,105,327,190).fillTriangle(947,160,1020,75,1095,160);g.fillStyle(0x78a85f).fillRect(0,475,1280,245);g.fillStyle(0x9e744e).fillRect(0,535,1280,135);g.fillStyle(0xc89a64).fillRect(0,575,1280,18);for(let i=0;i<27;i++)g.fillStyle(i%2?0x6b9655:0xd9b572,.5).fillCircle(30+(i*151)%1230,430+(i*67)%255,4+i%8);this.backTrees=[];for(let i=0;i<7;i++){const c=this.drawPalm(90+i*205,420-(i%2)*40).setDepth(6).setScale(.7+.1*(i%3));this.backTrees.push(c);}}
    drawHud(){this.panel(640,43,1248,66,0xfffae8,0xd8c49a,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x658b55).setDepth(81);this.text(410,40,'恐龍山谷・幼童版',30,'#43583d').setDepth(81);this.phaseText=this.text(690,43,'第 1 / 3 段',17,'#74806a').setDepth(81);this.soundButton=this.button(935,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xe9e5bf,'#43583d').setDepth(81);this.button(1093,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xe9e5bf,'#43583d').setDepth(81);
        this.panel(143,326,236,420,0xfffae8,0xd8c49a,23).setDepth(65);this.text(143,126,'山谷小任務',22,'#43583d').setDepth(66);this.progressText=this.text(143,187,'0 / 10',34,'#43583d').setDepth(66);this.text(143,225,'找到恐龍朋友',16,'#74806a').setDepth(66);this.collectText=this.text(143,287,'',18,'#8b6845').setDepth(66);this.tipText=this.text(143,348,'',15,'#74806a').setDepth(66);this.hintButton=this.button(143,430,190,48,'🦕 跳躍提示',()=>this.showHint(),0xe6b95e,'#5b4b2d').setDepth(67);this.slowButton=this.button(143,490,190,48,'慢速跑步：開',()=>this.toggleSlow(),0xe9e5bf,'#43583d').setDepth(67);this.helperButton=this.button(143,550,190,48,'箭頭提示：開',()=>this.toggleHelper(),0xe9e5bf,'#43583d').setDepth(67);this.feedback=this.text(690,104,'點一下畫面，跳過山谷障礙！',20,'#425f43').setDepth(81);this.text(730,692,'自動前進・點一下跳躍｜撞到障礙只會減速｜恐龍朋友會一直再出現',16,'#52694c').setDepth(70);this.refresh();}
    drawPalm(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.lineStyle(16,0x7e5a3c).beginPath().moveTo(0,40).lineTo(8,-70).strokePath();for(let i=0;i<6;i++){const a=-2.8+i*.58;g.fillStyle(0x5f9655,.9).fillEllipse(8+Math.cos(a)*48,-70+Math.sin(a)*32,88,25);}c.add(g);return c;}
    drawExplorer(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x5a4137).fillCircle(0,-38,25);g.fillStyle(0xf0c39c).fillCircle(0,-28,22);g.fillStyle(0x3b3330).fillCircle(-8,-31,3).fillCircle(8,-31,3);g.fillStyle(0xe7b74f).fillRoundedRect(-25,-56,50,14,7);g.fillStyle(0x67a46b).fillRoundedRect(-22,-2,44,50,14);g.fillStyle(0xf2d07b).fillRoundedRect(-31,7,17,34,7);g.fillStyle(0x6b4d3d).fillRoundedRect(14,42,15,35,7).fillRoundedRect(-29,42,15,35,7);g.fillStyle(0xdf5d4f).fillTriangle(18,-17,57,-5,20,2);const smile=this.add.arc(0,-22,8,7,20,160,false,0x5a4038).setStrokeStyle(2,0x5a4038);c.add([g,smile]);return c;}
    drawDinosaur(x,y,color=0x76b77a){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(color).fillEllipse(0,12,86,54).fillCircle(37,-12,31).fillTriangle(-36,4,-82,-18,-44,28);g.fillStyle(0xf0cf69).fillTriangle(-20,-15,-7,-39,5,-14).fillTriangle(5,-15,18,-41,29,-12);g.fillStyle(0xe8f5dc).fillEllipse(12,20,47,25);g.fillStyle(0xffffff).fillCircle(45,-19,10);g.fillStyle(0x344438).fillCircle(48,-19,4);g.fillStyle(color).fillRoundedRect(-20,29,15,30,7).fillRoundedRect(22,27,15,30,7);c.add(g);return c;}
    drawEgg(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0xfff1c9).fillEllipse(0,0,48,63);g.fillStyle(0xd8816e).fillCircle(-10,-8,6).fillCircle(9,10,7).fillCircle(8,-20,5);g.lineStyle(3,0xc59a74).strokeEllipse(0,0,48,63);c.add(g);return c;}
    drawFootprint(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x5f7950).fillEllipse(0,9,29,34).fillCircle(-14,-14,8).fillCircle(0,-21,8).fillCircle(14,-14,8);c.add(g);return c;}
    drawObstacle(type,x){const c=this.add.container(x,DINOSAUR_RUN_CONFIG.groundY-24),g=this.add.graphics();if(type==='rock'){g.fillStyle(0x6e6670).fillRoundedRect(-39,-42,78,66,22);g.fillStyle(0xa49a9e,.45).fillEllipse(-9,-27,35,14);}else if(type==='log'){g.fillStyle(0x83573d).fillRoundedRect(-55,-27,110,50,18);g.fillStyle(0xb27d50).fillCircle(50,-2,24);g.lineStyle(4,0x74462f).strokeCircle(50,-2,15);}else{g.fillStyle(0x745b48,.75).fillEllipse(0,13,125,37);g.fillStyle(0x9d7958,.6).fillCircle(-25,5,11).fillCircle(22,9,8);}c.add(g);return c;}
    spawnObject(){const type=PATTERN[this.spawnIndex%PATTERN.length],x=1370;let view;if(type==='friend'){const high=this.spawnIndex%3===1;view=this.drawDinosaur(x,high?DINOSAUR_RUN_CONFIG.groundY-155:DINOSAUR_RUN_CONFIG.groundY-42,[0x75b77a,0xe39a5b,0x6fa9bd][this.spawnIndex%3]);}else if(type==='egg')view=this.drawEgg(x,DINOSAUR_RUN_CONFIG.groundY-86-(this.spawnIndex%2)*55);else if(type==='footprint')view=this.drawFootprint(x,DINOSAUR_RUN_CONFIG.groundY-27);else view=this.drawObstacle(type,x);view.kind=type;view.resolved=false;view.setDepth(type==='friend'?45:40);this.objects.push(view);this.spawnIndex+=1;}
    bindInput(){this.input.on('pointerdown',pointer=>{if(this.mode==='playing'&&pointer.y>85)this.jump();});this.keyHandler=e=>{if(e.repeat)return;if(['Space','ArrowUp','KeyW'].includes(e.code))this.jump();else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyS')this.toggleSlow();else if(e.code==='KeyA')this.toggleHelper();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    jump(){if(this.mode!=='playing'||!this.grounded)return;this.grounded=false;this.velocityY=DINOSAUR_RUN_CONFIG.jumpVelocity;this.session.jump();this.feedback.setText('跳～越過前面的山谷小徑！');this.tone('send');}
    update(_time,delta){if(this.mode!=='playing')return;const dt=Math.min(.04,delta/1000);if(!this.grounded){this.velocityY+=DINOSAUR_RUN_CONFIG.gravity*dt;this.player.y+=this.velocityY*dt;if(this.player.y>=DINOSAUR_RUN_CONFIG.groundY-63){this.player.y=DINOSAUR_RUN_CONFIG.groundY-63;this.velocityY=0;this.grounded=true;}}this.player.angle=this.grounded?0:Phaser.Math.Clamp(this.velocityY*.025,-10,10);this.slowedLeft=Math.max(0,this.slowedLeft-dt);this.invincible=Math.max(0,this.invincible-dt);const speed=this.slowedLeft>0?DINOSAUR_RUN_CONFIG.slowedSpeed:(this.slow?DINOSAUR_RUN_CONFIG.slowSpeed:DINOSAUR_RUN_CONFIG.normalSpeed);this.spawnClock+=delta;if(this.spawnClock>(this.slow?1500:1250)&&this.objects.length<4){this.spawnClock=0;this.spawnObject();}this.objects.forEach(view=>{view.x-=speed*dt;this.checkObject(view);});this.objects=this.objects.filter(view=>{if(view.x<-140){if(view.active&&view.kind==='friend'&&!view.resolved)this.session.missFriend();view.destroy();this.refresh();return false;}return view.active;});this.backTrees.forEach(tree=>{tree.x-=speed*.09*dt;if(tree.x<-120)tree.x=1400;});this.updateGuide();}
    checkObject(view){if(view.resolved||Math.abs(view.x-this.player.x)>58)return;const dy=Math.abs(view.y-this.player.y);if(['friend','egg','footprint'].includes(view.kind)){if(dy<72){view.resolved=true;if(view.kind==='friend'){const result=this.session.meetFriend();this.feedback.setText('找到一位恐龍朋友，一起向前跑！');this.tone('correct');this.sparkles(view.x,view.y);this.tweens.add({targets:view,x:this.player.x-75,y:this.player.y+8,scale:.55,alpha:0,duration:500,onComplete:()=>view.destroy()});this.refresh();if(result==='complete'){this.mode='finishing';this.time.delayedCall(650,()=>this.finish());}}else{view.kind==='egg'?this.session.collectEgg():this.session.collectFootprint();this.feedback.setText(view.kind==='egg'?'找到一顆彩色恐龍蛋！':'發現一枚大腳印！');this.tone('correct');this.tweens.add({targets:view,y:view.y-65,alpha:0,angle:120,duration:400,onComplete:()=>view.destroy()});this.refresh();}}}else if(this.invincible<=0&&dy<70){view.resolved=true;this.invincible=1.1;this.slowedLeft=1.4;this.session.bumpObstacle();this.feedback.setText('碰到障礙只會慢一下，小恐龍來幫忙！');this.tone('hint');this.tweens.add({targets:this.player,x:this.player.x-18,angle:-12,duration:110,yoyo:true,repeat:2});this.tweens.add({targets:this.helperDino,x:this.helperDino.x+36,scale:.82,duration:180,yoyo:true,repeat:1});this.tweens.add({targets:view,alpha:.25,scale:.8,duration:430,onComplete:()=>view.destroy()});this.refresh();}}
    updateGuide(){const next=this.objects.filter(v=>v.active&&!v.resolved&&v.x>this.player.x).sort((a,b)=>a.x-b.x)[0];if(!this.helper||!next){this.guideArrow.setVisible(false);return;}this.guideArrow.setVisible(true).setPosition(455,this.player.y-90);const needJump=['rock','log','mud'].includes(next.kind)||next.y<this.player.y-45;this.guideArrow.setAngle(needJump?-90:0);}
    showHint(){if(this.mode!=='playing'||!this.session.hint())return;this.helper=true;this.helperButton.label.setText('箭頭提示：開');const next=this.objects.filter(v=>v.active&&!v.resolved).sort((a,b)=>a.x-b.x)[0];this.feedback.setText(next&&(['rock','log','mud'].includes(next.kind)||next.y<this.player.y-45)?'提示：前面要跳起來！':'提示：保持在地面，恐龍朋友就在前方。');if(next)this.tweens.add({targets:next,scale:1.15,duration:170,yoyo:true,repeat:3});this.tone('hint');this.refresh();}
    toggleSlow(){if(this.mode!=='playing')return;this.slow=!this.slow;this.slowButton.label.setText(this.slow?'慢速跑步：開':'慢速跑步：關');this.feedback.setText(this.slow?'山谷慢下來了，慢慢跳。':'一般速度開啟，準備跑酷！');}
    toggleHelper(){if(this.mode!=='playing')return;this.helper=!this.helper;this.helperButton.label.setText(this.helper?'箭頭提示：開':'箭頭提示：關');this.feedback.setText(this.helper?'箭頭會提醒前方是否需要跳躍。':'箭頭收起來，自己觀察山谷！');}
    refresh(){this.progressText?.setText(`${this.session.friends} / ${DINOSAUR_RUN_CONFIG.targetFriends}`);this.collectText?.setText(`恐龍蛋 ${this.session.eggs}\n大腳印 ${this.session.footprints}`);this.phaseText?.setText(`第 ${this.session.phaseIndex+1} / ${DINOSAUR_RUN_PHASES.length} 段・${this.session.phase.name}`);this.tipText?.setText(`${this.session.phase.guide}\n\n碰障礙 ${this.session.bumps} 次\n朋友再出現 ${this.session.missedFriends} 次`);}
    sparkles(x,y){for(let i=0;i<11;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd363:0xffffff).setDepth(75),a=i/11*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*82,y:y+Math.sin(a)*62,alpha:0,angle:140,duration:500,onComplete:()=>s.destroy()});}}
    showIntro(){const o=this.makeOverlay('恐龍山谷探險隊出發！','小探險家會自動向前跑。\n點一下畫面、空白鍵或方向鍵上就會跳躍；\n找到 10 位可愛恐龍朋友，就能完成山谷旅程。');o.add(this.text(640,410,'撞到石頭、倒木或泥巴只會減速，不扣生命。',19,'#6b7e62'));o.add(this.button(640,500,290,60,'跑進恐龍山谷！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();this.time.delayedCall(450,()=>this.spawnObject());},0x658b55));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('在山谷休息一下','角色會自動前進，點一下畫面即可跳躍。\n找到恐龍朋友是主要目標，恐龍蛋與腳印是額外收集。\n撞到障礙只會短暫減速，不會 Game Over。');o.add(this.button(640,415,270,55,'繼續探險',()=>this.resumeGame(),0x658b55));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xe9e5bf,'#43583d'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    finish(){this.mode='finished';this.tone('finish');const o=this.makeOverlay('十位恐龍朋友全部找到了！',`恐龍山谷探險完成！\n恐龍蛋 ${this.session.eggs} 顆　大腳印 ${this.session.footprints} 枚\n碰障礙 ${this.session.bumps} 次　使用提示 ${this.session.hints} 次`);o.add(this.text(640,400,'幼童版沒有失敗；每次跳躍與重新嘗試都算進步。',18,'#6b7e62'));o.add(this.button(500,490,230,58,'再跑一次',()=>this.restart(),0x658b55));o.add(this.button(780,490,230,58,'返回遊戲列表',()=>this.leave(),0xe6b95e,'#5b4b2d'));}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
