import AnimalSnackGame from './AnimalSnackGame.js';
import {SkySession,SKY_WEAPONS,SKY_DIFFICULTIES} from '../data/SkyRules.js';
import {SKY_LEVELS,SKY_CHAPTERS,SKY_BOSSES} from '../data/SkyLevels.js';
const BX=320,BY=82,W=640,H=620,PALETTE=[0xdaeddb,0xf1dfc7,0xdce4f2,0xf3d8cc,0xdcece9],KINDS={scout:1,diver:2,sniper:3,carrier:4,guard:4};
export default class ForestSkyGame extends AnimalSnackGame{
 constructor(){super('ForestSkyGame');}
 preload(){for(const name of ['units','bosses','worlds'])if(!this.textures.exists(`sky_${name}`))this.load.spritesheet(`sky_${name}`,`assets/forest-sky/${name}.png`,{frameWidth:512,frameHeight:512});}
 art(x,y,frame,size=70,key='units'){return this.add.image(x,y,`sky_${key}`,frame).setDisplaySize(size,size);}
 create(){
  this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.records=this.records||{};this.difficulty=this.difficulty||'rookie';this.loadout=this.loadout??0;this.session=null;this.mode='select';this.overlay=null;this.held=new Set();this.touchCharge=new Set();this.drag=null;this.target=null;this.dashRequest=false;this.bombRequest=false;this.effects=[];
  const extra=Math.max(0,3-(this.input.manager?.pointersTotal??1));if(extra)this.input.addPointer?.(extra);
  if(['units','bosses','worlds'].some(n=>!this.textures.exists(`sky_${n}`))){this.dialog('素材還沒載入','請完整複製 assets/forest-sky，\n再返回遊戲列表重新進入。').add(this.button(640,530,300,60,'返回遊戲列表',()=>this.leave()));return;}
  this.showSelection();if(!this.seenIntro)this.showIntro();
  this.onDown=(p,objects=[])=>{if(this.mode!=='playing'||objects.length||this.drag||p.button>0||!this.inField(p))return;this.drag={id:p.id,x:p.x,y:p.y,px:this.session.player.x,py:this.session.player.y};this.target={x:this.session.player.x,y:this.session.player.y};};
  this.onMove=p=>{if(this.mode!=='playing'||this.drag?.id!==p.id)return;this.target={x:Math.max(22,Math.min(618,this.drag.px+p.x-this.drag.x)),y:Math.max(175,Math.min(590,this.drag.py+p.y-this.drag.y))};};
  this.onUp=p=>{this.touchCharge.delete(p.id);if(this.drag?.id===p.id){this.drag=null;this.target=null;}};
  this.input.on('pointerdown',this.onDown);this.input.on('pointermove',this.onMove);this.input.on('pointerup',this.onUp);this.input.on('pointerupoutside',this.onUp);
  this.keyDown=e=>{if(e.repeat)return;if(['Escape','KeyP'].includes(e.code)){if(this.mode==='paused')this.resumeGame();else this.pauseGame();return;}if(this.mode!=='playing')return;this.held.add(e.code);
   if(/^Digit[1234]$/.test(e.code))this.changeWeapon(Number(e.code.at(-1))-1);if(e.code==='KeyQ')this.changeWeapon((this.session.player.weapon+1)%4);if(['ShiftLeft','ShiftRight','KeyX'].includes(e.code))this.dashRequest=true;if(e.code==='KeyB')this.bombRequest=true;
   if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){this.drag=null;this.target=null;}
  };this.keyUp=e=>this.held.delete(e.code);this.input.keyboard?.on('keydown',this.keyDown);this.input.keyboard?.on('keyup',this.keyUp);this.input.keyboard?.addCapture?.(['UP','DOWN','LEFT','RIGHT','SPACE']);
  this.visibilityHandler=()=>{if(document.hidden)this.pauseGame();};this.blurHandler=()=>this.pauseGame();document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);
  this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyDown);this.input.keyboard?.off('keyup',this.keyUp);this.input.keyboard?.removeCapture?.(['UP','DOWN','LEFT','RIGHT','SPACE']);for(const [n,f]of [['pointerdown',this.onDown],['pointermove',this.onMove],['pointerup',this.onUp],['pointerupoutside',this.onUp]])this.input.off(n,f);this.clearInput();this.stopTones();this.worldMask?.destroy();this.worldMask=null;this.session=null;this.effects=[];});
 }
 clearInput(){this.held?.clear();this.touchCharge?.clear();this.drag=null;this.target=null;this.dashRequest=false;this.bombRequest=false;this.session?.cancelCharge();}
 clear(){this.clearInput();this.tweens.killAll();this.worldMask?.destroy();this.worldMask=null;this.children.removeAll(true);this.overlay=null;this.effects=[];this.enemyViews=new Map();this.pickupViews=new Map();this.bossView=null;this.world=null;}
 inField(p){return p.x>=BX&&p.x<=BX+W&&p.y>=BY&&p.y<=BY+H;}
 backdrop(){this.add.rectangle(640,360,1280,720,0xe6eee2);this.art(640,360,5,1280,'worlds').setAlpha(.2);}
 topbar(label){this.panel(640,33,1260,56,0xf6ffeb,0x9caf91,15);this.button(100,33,168,40,'← 遊戲列表',()=>this.leave());this.text(380,33,'森林天空守衛隊',26);this.text(711,33,label,18);
  this.soundButton=this.button(1033,33,110,40,this.soundOn?'音效：開':'音效：關',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xdbe7c9,'#355440');this.button(1175,33,142,40,this.mode==='select'?'飛行教室':'暫停 / 說明',()=>this.mode==='select'?this.showIntro():this.pauseGame(),0xdbe7c9,'#355440');}
 showSelection(){
  if(this.session)this.session.setPaused(true);this.clear();this.mode='select';this.backdrop();this.topbar('15 關 · 五大空域 · 四種武器');const stars=Object.entries(this.records).filter(([k])=>k.endsWith(`:${this.difficulty}`)).reduce((n,[,r])=>n+r.stars,0);
  this.text(486,87,`選擇航段　｜　${SKY_DIFFICULTIES[this.difficulty].name}紀錄 ★ ${stars} / 45`,23);
  this.button(1060,88,291,39,`難度：${SKY_DIFFICULTIES[this.difficulty].name}　點此切換`,()=>{if(this.mode==='select'){this.difficulty=this.difficulty==='rookie'?'brave':'rookie';this.showSelection();}},0x70948a);
  SKY_CHAPTERS.forEach((name,row)=>{const y=156+row*100;this.text(50,y-39,`${row+1}　${name}`,16,'#4e6c5d',0).setOrigin(0,.5);for(let col=0;col<3;col++){const index=row*3+col,l=SKY_LEVELS[index],r=this.records[`${l.id}:${this.difficulty}`],c=this.add.container(270+col*370,y+7);c.add([this.panel(0,0,344,74,PALETTE[row],0xa6bea7,17),this.text(-142,-3,String(l.id).padStart(2,'0'),25),this.text(19,-15,l.title,22),this.text(19,17,r?'★'.repeat(r.stars)+'☆'.repeat(3-r.stars):({patrol:'突破編隊',rescue:'空中救援',escort:'護送補給',defend:'守衛防線',boss:'多階段頭目'})[l.type],17)]);c.setSize(344,74).setInteractive({useHandCursor:true}).on('pointerdown',()=>{if(this.mode==='select')this.startLevel(index);});}});
  this.text(640,621,'選擇起飛武器　｜　航行中也能切換；撿取 P 會升級全部武器',18);SKY_WEAPONS.forEach((w,i)=>this.button(265+i*250,669,235,48,`${this.loadout===i?'✓ ':''}${i+1} ${w.name}`,()=>{if(this.mode==='select'){this.loadout=i;this.showSelection();}},this.loadout===i?0x4d8270:0xc6d6bb,this.loadout===i?'#ffffff':'#355440'));
 }
 startLevel(index){if(!Number.isInteger(index)||!SKY_LEVELS[index])return;this.index=index;this.session=new SkySession(SKY_LEVELS[index],{difficulty:this.difficulty,weapon:this.loadout});this.renderLevel();const p=this.sound.context?.resume?.();p?.catch?.(()=>{});}
 renderLevel(){
  this.clear();this.mode='playing';this.session.setPaused(false);const s=this.session,l=s.level;this.backdrop();this.topbar(`${SKY_CHAPTERS[l.theme]} · 第 ${l.id} 關 · ${SKY_DIFFICULTIES[this.difficulty].name}`);
  this.panel(640,392,658,630,0x264d51,0x75957e,15);this.world=this.add.container(BX,BY);const mask=this.add.graphics();mask.fillStyle(0xffffff,1).fillRect(BX,BY,W,H);mask.setVisible(false);this.worldMask=mask.createGeometryMask();this.world.setMask(this.worldMask);
  this.backTiles=[this.art(0,0,l.theme,640,'worlds').setOrigin(0),this.art(0,-640,l.theme,640,'worlds').setOrigin(0)];this.world.add(this.backTiles);this.world.add(this.add.rectangle(320,310,640,620,l.theme===2?0x081424:0x0c2631,l.theme===2?.07:.17));
  this.flow=this.add.graphics();this.world.add(this.flow);this.hazardGraphics=this.add.graphics();this.world.add(this.hazardGraphics);this.entityLayer=this.add.container(0,0);this.world.add(this.entityLayer);this.bulletGraphics=this.add.graphics();this.world.add(this.bulletGraphics);this.playerView=this.art(s.player.x,s.player.y,0,67);this.world.add(this.playerView);this.heroGraphics=this.add.graphics();this.world.add(this.heroGraphics);this.effectGraphics=this.add.graphics();this.world.add(this.effectGraphics);
  if(s.escort){this.escortView=this.art(s.escort.x,s.escort.y,5,82);this.entityLayer.add(this.escortView);}else this.escortView=null;
  this.bossBar=this.add.graphics();this.world.add(this.bossBar);this.bossTitle=this.text(320,18,'',18,'#ffffff');this.world.add(this.bossTitle);this.battleNotice=this.text(320,286,'',28,'#fff2ae').setDepth(40);this.world.add(this.battleNotice);this.noticeTime=2.5;this.battleNotice.setText('青葉戰機，出發！');
  this.panel(157,260,284,359,0xf5fbea,0xaac0a2);this.text(157,110,l.title,25);this.missionText=this.text(157,166,'',21).setWordWrapWidth(246,true);this.healthText=this.text(157,234,'',24,'#b45d62');this.shieldText=this.text(157,275,'',20);this.scoreText=this.text(157,319,'',21);this.progressText=this.text(157,366,'',19).setWordWrapWidth(246,true);this.timeText=this.text(157,409,'',18);
  this.panel(157,574,284,253,0xf5fbea,0xaac0a2);this.text(157,470,'切換武器　1～4 / Q',20);this.weaponButtons=SKY_WEAPONS.map((w,i)=>this.button(89+(i%2)*136,519+Math.floor(i/2)*58,126,48,`${i+1} ${w.short}`,()=>this.changeWeapon(i),0xc5dcbc,'#345946'));
  this.weaponInfo=this.text(157,619,'',19).setWordWrapWidth(245,true);this.weaponHint=this.text(157,652,'',15).setWordWrapWidth(245,true);this.text(157,680,'P 升級　◇ 護盾　B 炸彈補給',16);
  this.panel(1123,249,280,336,0xf5fbea,0xaac0a2);this.text(1123,110,'飛行小提示',23);this.tipText=this.text(1123,179,l.tip,18).setWordWrapWidth(243,true);this.text(1123,270,'本關三星',21);this.starText=this.text(1123,337,'',18).setWordWrapWidth(245,true);
  this.panel(1123,566,280,270,0xf5fbea,0xaac0a2);this.energyText=this.text(1123,448,'',18);this.chargeButton=this.button(1123,502,240,60,'按住蓄力 · C',()=>{},0x628b9c);this.chargeButton.on('pointerdown',p=>{if(this.mode==='playing')this.touchCharge.add(p.id);});this.chargeButton.on('pointerup',p=>this.touchCharge.delete(p.id));this.chargeButton.on('pointerout',p=>this.touchCharge.delete(p.id));
  this.dashButton=this.button(1123,574,240,57,'衝刺 · Shift / X',()=>{if(this.mode==='playing')this.dashRequest=true;},0x779975);this.bombButton=this.button(1123,643,240,60,'森林炸彈 · B',()=>{if(this.mode==='playing')this.bombRequest=true;},0xb58b5d);
  this.energyBar=this.add.graphics();this.text(640,72,'自動連射　｜　WASD / 方向鍵移動　｜　觸控按住戰場拖曳　｜　空白鍵慢速',16,'#385b49');this.soundCooldown=0;this.drawState(0);
 }
 changeWeapon(i){if(this.mode!=='playing')return false;return this.session.setWeapon(i);}
 controls(){const k=this.held;return {xAxis:Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),yAxis:Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW')),target:this.target,focus:k.has('Space'),charge:k.has('KeyC')||this.touchCharge.size>0,dash:this.dashRequest,bomb:this.bombRequest};}
 update(_time,delta){if(this.mode!=='playing'||!this.session)return;const dt=Math.max(0,Math.min(.1,delta/1000));this.soundCooldown=Math.max(0,this.soundCooldown-dt);const before=this.session.time;this.session.advance(dt,this.controls());if(this.session.time>before||this.session.status!=='playing'){this.dashRequest=false;this.bombRequest=false;}
  for(const e of this.session.events.splice(0)){if(e.type==='kill'||e.type==='rescue'||e.type==='bossDown')this.effects.push({x:e.x,y:e.y,age:0,type:e.type});if(e.type==='bomb')this.effects.push({x:320,y:310,age:0,type:'bomb'});
   if(e.type==='boss'){this.notice(SKY_BOSSES[this.session.level.boss],2.5);this.tone('hint');}if(e.type==='phase')this.notice(`第 ${e.phase} 階段　留意新招式！`,1.5);if(e.type==='part')this.notice('武器部位擊破！',1.3);if(e.type==='hurt')this.tone('hint');
   if(['kill','power','shield','charge','rescue','bomb'].includes(e.type)&&this.soundCooldown<=0){this.tone(e.type==='kill'?'send':'correct');this.soundCooldown=.15;}if(e.type==='weapon')this.tone('hint');
  }this.drawState(dt);if(this.session.status!=='playing')this.finishLevel();
 }
 notice(text,time=2){this.battleNotice.setText(text);this.noticeTime=time;}
 drawState(dt){
  const s=this.session,p=s.player,l=s.level,scroll=(s.time*(l.theme===2?36:46))%640;this.backTiles[0].y=scroll;this.backTiles[1].y=scroll-640;
  this.flow.clear();for(let i=0;i<15;i++){const x=(i*137)%640,y=(i*91+s.time*100)%620;this.flow.lineStyle(1,0xffffff,.17).lineBetween(x,y,x,y+11);}
  this.hazardGraphics.clear();for(const h of s.hazards){const active=h.age>=h.warn;this.hazardGraphics.fillStyle(active?0xffe1b1:0xf08496,active?.67:.15).fillRect(h.x-h.w/2,0,h.w,620).lineStyle(active?6:2,h.kind==='lava'?0xffb565:0xff9ece,active?.95:.55).lineBetween(h.x,0,h.x,620);if(!active)for(let y=25;y<620;y+=70)this.hazardGraphics.lineStyle(2,0xffe7c0,.7).lineBetween(h.x-9,y,h.x,y+13).lineBetween(h.x,y+13,h.x+9,y);}
  const live=new Set();for(const e of s.enemies){live.add(e.id);let view=this.enemyViews.get(e.id);if(!view){const c=this.add.container(e.x,e.y);c.add(this.art(0,0,KINDS[e.kind],e.r*2.8).setTint(e.kind==='guard'?0xc0d8f4:0xffffff));const g=this.add.graphics();c.add(g);view={c,g};this.entityLayer.add(c);this.enemyViews.set(e.id,view);}view.c.x=e.x;view.c.y=e.y;view.c.setAlpha(e.flash>0?.55:1);view.g.clear();if(e.hp<e.maxHp)view.g.fillStyle(0x20394d,.7).fillRect(-21,-e.r-9,42,4).fillStyle(0xffb08f,1).fillRect(-21,-e.r-9,42*Math.max(0,e.hp/e.maxHp),4);if(e.kind==='guard')view.g.lineStyle(2,0xb8eeff,.55).strokeCircle(0,0,e.r+4);if(e.aim)this.hazardGraphics.lineStyle(2,0xff8bae,.75).lineBetween(e.x,e.y,e.aim.x,e.aim.y);}
  for(const [id,v]of this.enemyViews)if(!live.has(id)){v.c.destroy();this.enemyViews.delete(id);}
  const pickups=new Set();for(const o of s.pickups){pickups.add(o.id);let c=this.pickupViews.get(o.id);if(!c){c=this.add.container(o.x,o.y);if(o.kind==='bird')c.add(this.art(0,0,5,60,'bosses'));else{const fill={power:0xcff384,shield:0x9ee8ff,bomb:0xffd397}[o.kind];c.add([this.add.circle(0,0,16,fill).setStrokeStyle(2,0xffffff),this.text(0,0,{power:'P',shield:'◇',bomb:'B'}[o.kind],20,'#2b5161')]);}this.entityLayer.add(c);this.pickupViews.set(o.id,c);}c.x=o.x;c.y=o.y;}
  for(const [id,c]of this.pickupViews)if(!pickups.has(id)){c.destroy();this.pickupViews.delete(id);}
  if(this.escortView){this.escortView.x=s.escort.x;this.escortView.y=s.escort.y;this.escortView.setAlpha(s.escort.invuln>0?.55:1);}
  const b=s.boss;this.bossBar.clear();if(b&&b.hp>0){if(!this.bossView){this.bossView=this.art(b.x,b.y,l.boss,210,'bosses');this.entityLayer.add(this.bossView);}this.bossView.x=b.x;this.bossView.y=b.y;this.bossView.setAlpha(b.flash>0?.65:1);
   this.bossBar.fillStyle(0x153142,.9).fillRoundedRect(110,38,420,12,6).fillStyle(0xf49ca2,1).fillRoundedRect(110,38,420*Math.max(0,b.hp/b.maxHp),12,6);
   for(const part of b.parts){const x=b.x+part.side*65,y=b.y+18;if(part.hp>0){this.bossBar.lineStyle(3,0xffd699,.9).strokeCircle(x,y,25).fillStyle(0xffb76d,1).fillRect(x-23,y+31,46*part.hp/part.maxHp,4);}else{this.bossBar.fillStyle(0x263b43,.7).fillCircle(x,y,18).lineStyle(4,0x8faaa8,.9).lineBetween(x-10,y-10,x+10,y+10).lineBetween(x+10,y-10,x-10,y+10);}}
   if(b.guard>0||b.y<100)this.bossBar.lineStyle(3,0xa9e7ff,.7).strokeCircle(b.x,b.y,86);this.bossTitle.setText(`${SKY_BOSSES[l.boss]}　階段 ${b.phase} / 3`);
  }else{this.bossTitle.setText('');if(this.bossView)this.bossView.setVisible(false);}
  const g=this.bulletGraphics;g.clear();for(const q of s.shots){const color=q.kind==='petal'?0xffe287:q.kind==='seed'?0xc8b6ff:q.kind==='laser'?0x9ceeff:q.kind==='charge'?0xffefa3:0xb0ffac;
   if(q.kind==='laser'||q.kind==='charge')g.lineStyle(q.r*1.5,color,.7).lineBetween(q.x,q.y,q.x,q.y+Math.min(q.kind==='charge'?75:46,Math.max(0,p.y-q.y))).lineStyle(2,0xffffff,1).lineBetween(q.x,q.y,q.x,q.y+24);else g.fillStyle(color,1).fillCircle(q.x,q.y,q.r).fillStyle(0xffffff,.8).fillCircle(q.x-1,q.y-1,2);
  }for(const q of s.bullets)g.fillStyle(0xa93361,1).fillCircle(q.x,q.y,q.r+2).fillStyle(0xffa6cf,1).fillCircle(q.x,q.y,q.r).fillStyle(0xfff0ed,1).fillCircle(q.x-1.5,q.y-1.5,2);
  this.playerView.x=p.x;this.playerView.y=p.y;this.playerView.setAngle(p.dash>0?p.lastX*15:0).setAlpha(p.invuln>0?.48+.32*Math.abs(Math.sin(s.time*17)):1);this.heroGraphics.clear();
  if(p.shield>0)this.heroGraphics.lineStyle(2,0x92eaff,.45).strokeCircle(p.x,p.y,31);this.heroGraphics.fillStyle(0x183c46,1).fillCircle(p.x,p.y,9).fillStyle(0xbefff7,1).fillCircle(p.x,p.y,5).lineStyle(1,0xffffff,1).strokeCircle(p.x,p.y,8);
  if(p.charge>0){this.heroGraphics.lineStyle(4,p.energy>=35?0xffe697:0xc7948e,.9).strokeCircle(p.x,p.y,18+Math.min(1,p.charge/1.2)*20);this.heroGraphics.fillStyle(0xffecaa,.35).fillCircle(p.x,p.y,8+p.charge*12);}
  if(p.dash>0)this.heroGraphics.lineStyle(18,0xa5ffe3,.35).lineBetween(p.x,p.y,p.x-p.dashX*70,p.y-p.dashY*70);
  this.effectGraphics.clear();for(const f of this.effects){f.age+=dt;const u=f.age/(f.type==='bomb'?.75:.48);if(f.type==='bomb'){this.effectGraphics.fillStyle(0xfff2b2,Math.max(0,.28*(1-u))).fillRect(0,0,640,620).lineStyle(9,0xf8ffe1,Math.max(0,1-u)).strokeCircle(f.x,f.y,40+u*600);}else{for(let n=0;n<8;n++){const a=n*Math.PI/4;this.effectGraphics.fillStyle(f.type==='rescue'?0xa5ffc8:0xffd08a,Math.max(0,1-u)).fillCircle(f.x+Math.cos(a)*u*42,f.y+Math.sin(a)*u*42,Math.max(1,5*(1-u)));}}}this.effects=this.effects.filter(f=>f.age<(f.type==='bomb'?.75:.48));
  this.noticeTime=Math.max(0,this.noticeTime-dt);this.battleNotice.setVisible(this.noticeTime>0);this.healthText.setText('♥'.repeat(p.hp)+'♡'.repeat(s.settings.hp-p.hp));this.shieldText.setText(`護盾 ${p.shield}　能量 ${Math.floor(p.energy)} / 100`);this.scoreText.setText(`${String(s.stats.score).padStart(6,'0')}　分`);
  this.missionText.setText(l.type==='rescue'?`救援任務\n小鳥 ${s.stats.rescued} / ${l.rescueGoal}`:l.type==='escort'?`護送補給艇\n裝甲 ${s.escort.hp} / ${s.escort.maxHp}`:l.type==='defend'?`守衛防線\n耐久 ${s.beacon} / 10`:l.type==='boss'?`大型頭目戰\n部位 ${s.stats.parts} / 2`:`突破巡邏編隊\n擊退 ${s.stats.kills} / ${l.killGoal}`);
  this.progressText.setText(`擊退 ${s.stats.kills} 架　受擊 ${s.stats.damage} 次\n連擊 ${s.comboTime>0?s.combo:0}　最高 ${s.stats.maxCombo}`);this.timeText.setText(l.type==='boss'?(s.bossSpawned?`頭目交戰 ${Math.floor(s.time-l.duration)} 秒`:`頭目接近：${Math.ceil(l.duration-s.time)} 秒`):`航段剩餘 ${Math.max(0,Math.ceil(l.duration+8-s.time))} 秒`);
  this.weaponButtons.forEach((v,i)=>v.setAlpha(i===p.weapon?1:.5));this.weaponInfo.setText(`${SKY_WEAPONS[p.weapon].name}　Lv.${s.weaponLevel}`);this.weaponHint.setText(`${SKY_WEAPONS[p.weapon].tip}（P ${p.power}/6）`);this.starText.setText(`☆ 完成本關任務\n${s.stats.damage<=l.damageStar?'☆':'○'} 受擊不超過 ${l.damageStar} 次\n${s.challengeMet()?'★':'☆'} ${l.challenge.label}`);
  this.energyText.setText(p.charge>0?`蓄力 ${Math.round(Math.min(1,p.charge/1.2)*100)}%　放開發射`:'蓄力耗能 35 · 按住至少 0.6 秒');this.energyBar.clear().fillStyle(0xcadbd2,1).fillRect(1006,464,234,5).fillStyle(0x6cb7af,1).fillRect(1006,464,234*p.energy/100,5);
  this.chargeButton.setAlpha(p.energy>=35?1:.55);this.dashButton.label.setText(p.dashCooldown>0?`衝刺冷卻 ${p.dashCooldown.toFixed(1)} 秒`:'衝刺 · Shift / X');this.bombButton.label.setText(`森林炸彈 ${p.bombs} · B`);this.bombButton.setAlpha(p.bombs>0?1:.5);
 }
 dialog(title,body){this.overlay?.destroy();const o=this.add.container(0,0).setDepth(100);this.overlay=o;o.add([this.add.rectangle(640,360,1280,720,0x142c36,.86).setInteractive(),this.panel(640,360,1010,595,0xf8fff0,0xb3c5a6),this.text(640,111,title,31),this.text(640,184,body,22).setWordWrapWidth(900,true)]);return o;}
 showIntro(){if(this.mode!=='select')return;this.mode='intro';const o=this.dialog('青葉戰機，準備起飛！','飛機會自動連射，你專心移動、閃避與完成任務。\n機身中央的青色小圓才是判定範圍；紅紫色圓彈是敵彈。');
  const entries=[['移動與精準閃避','WASD / 方向鍵移動\n空白鍵按住慢速\n觸控：按住戰場拖曳'],['四種武器與升級','1～4 或 Q 切換武器\n收集 P，全部武器一起升級\n連射、散彈、雷射、追蹤'],['危急時的三個工具','C 按住蓄力、放開發射\nShift / X 衝刺，短暫無敵\nB 森林炸彈，清除敵彈']];entries.forEach(([title,body],i)=>{const x=332+i*308;o.add([this.panel(x,354,287,208,PALETTE[i],0xadbea8),this.text(x,281,title,22),this.text(x,365,body,20)]);});
  o.add(this.text(640,499,'先試「見習」：護盾較多、敵彈較慢；熟悉後可挑戰「勇敢」。\n任務包含救援、護送、防守與頭目戰。所有關卡都能自由選擇。',20));o.add(this.button(640,588,326,57,'選擇第一段航程',()=>{this.seenIntro=true;this.overlay.destroy();this.overlay=null;this.mode='select';}));
 }
 pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.session.setPaused(true);this.clearInput();this.stopTones();const o=this.dialog('暫停飛行','子彈、敵機與任務時間都已停下。\nWASD / 方向鍵移動，空白鍵慢速；觸控按住戰場拖曳。');
  o.add(this.text(640,293,'1～4 / Q 換武器　C 按住蓄力、放開發射\nShift / X 衝刺（短暫無敵）　B 森林炸彈（清除敵彈）\nP 升級全部武器　◇ 補護盾並修補護送艇　綠傘小鳥靠近救援',21));o.add(this.text(640,408,this.session.level.tip,20).setWordWrapWidth(870,true));o.add(this.button(640,492,294,55,'繼續飛行',()=>this.resumeGame()));o.add(this.button(462,572,294,55,'本關重新開始',()=>this.confirmRestart(),0xa58e60));o.add(this.button(818,572,294,55,'返回選關',()=>this.showSelection(),0x819b78));
 }
 resumeGame(){if(this.mode!=='paused')return;this.overlay.destroy();this.overlay=null;this.clearInput();this.session.setPaused(false);this.mode='playing';}
 confirmRestart(){if(this.mode!=='paused')return;this.mode='confirm';const o=this.dialog('重新開始這段航程？','本關武器升級、護盾與任務會重新計算。\n已獲得的本次最佳星星與分數會保留。');o.add(this.button(472,474,286,60,'繼續目前航程',()=>{this.mode='paused';this.resumeGame();}));o.add(this.button(808,474,286,60,'重新起飛',()=>this.startLevel(this.index),0xa58e60));}
 finishLevel(){const s=this.session,won=s.status==='won',medals=s.medals(),stars=medals.filter(Boolean).length;this.mode='finished';this.clearInput();if(won){const key=`${s.level.id}:${this.difficulty}`,old=this.records[key];this.records[key]={stars:Math.max(stars,old?.stars||0),score:Math.max(s.stats.score,old?.score||0)};this.tone('finish');}
  const o=this.dialog(won?'任務完成，平安返航！':'整備一下，再次起飛',won?`${'★'.repeat(stars)}${'☆'.repeat(3-stars)}　${s.stats.score} 分\n擊退 ${s.stats.kills} 架　救援 ${s.stats.rescued} 隻　受擊 ${s.stats.damage} 次`:`${s.reason}\n可以換一種武器、保留炸彈，或先練習另一段航程。`);
  o.add(this.art(640,324,0,144));o.add(this.text(640,421,won?`${medals[1]?'✓':'○'} 受擊 ≤ ${s.level.damageStar} 次　　${medals[2]?'✓':'○'} ${s.level.challenge.label}`:'護盾先承受傷害，受擊後有短暫無敵。',21));o.add(this.button(343,535,254,61,'再飛一次',()=>this.startLevel(this.index),0xa58e60));o.add(this.button(640,535,254,61,'返回選關',()=>this.showSelection(),0x819b78));o.add(this.button(937,535,254,61,this.index<14?'下一關 →':'查看所有紀錄',()=>this.index<14?this.startLevel(this.index+1):this.showSelection()));o.add(this.text(640,611,'紀錄保留於本次開啟；不影響主遊戲存檔與愛心。',18));
 }
 leave(){this.clearInput();this.stopTones();this.session?.setPaused(true);if(this.scene.manager.keys[this.returnScene])this.scene.start(this.returnScene);}
}
