import AnimalSnackGame from './AnimalSnackGame.js';
import {StarflightSession,StarflightTouch,STAR_ACTS,STAR_UPGRADES,STAR_CONTROLS} from '../data/StarflightRules.js';
import {preferences} from '../systems/AdventurePreferences.js';
const TOP=82,H=480;
// Generated atlas frames are intentionally mapped individually (not a uniform grid).
const FRAMES={hero:[0,174,348,456],owl:[344,262,295,312],balloon:[620,100,323,521],beetle:[938,249,316,376],wolf:[0,713,357,374],snail:[354,805,278,285],fairy:[632,794,224,334],boss:[842,645,412,514]};
const KINDS=['owl','balloon','beetle','wolf','snail','fairy'];
export default class ForestStarflightGame extends AnimalSnackGame{
 constructor(){super('ForestStarflightGame');}
 preload(){for(const key of ['crew','sky'])if(!this.textures.exists('star_'+key))this.load.image('star_'+key,`assets/forest-starflight/${key}.png`);}
 create(){this.mode='title';this.session=null;this.touch=new StarflightTouch();this.held=new Set();this.requests={};this.views=new Map();this.effects=[];this.audioNodes=new Set();this.soundOn=preferences.value.sfx;this.autoFire=true;this.difficulty='normal';this.overlay=null;
  if(this.textures.exists('star_crew')){const t=this.textures.get('star_crew'),im=t.getSourceImage();for(const [k,[x,y,w,h]]of Object.entries(FRAMES))if(!t.has(k))t.add(k,0,Math.round(x*im.width/1254),Math.round(y*im.height/1254),Math.round(w*im.width/1254),Math.round(h*im.height/1254));}
  this.input.addPointer(Math.max(0,4-(this.input.manager.pointersTotal||1)));const canvas=this.game.canvas,old=canvas.style.touchAction;canvas.style.touchAction='none';
  this.down=p=>{this.sound.context?.resume?.()?.catch?.(()=>{});if(this.mode==='playing')this.touch.down(p);};this.move=p=>{if(this.mode==='playing')this.touch.move(p);};this.up=p=>this.touch.up(p);this.cancel=()=>this.clearInput();
  this.keydown=e=>{if(e.repeat)return;if(['Escape','KeyP'].includes(e.code)){this.mode==='paused'?this.resumeGame():this.pauseGame();return;}if(this.mode!=='playing')return;this.held.add(e.code);if(e.code==='Space')this.requests.upgrade=true;if(e.code==='KeyK')this.requests.bomb=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')this.requests.dash=true;};this.keyup=e=>this.held.delete(e.code);
  this.input.on('pointerdown',this.down);this.input.on('pointermove',this.move);this.input.on('pointerup',this.up);this.input.on('pointerupoutside',this.up);this.input.on('gameout',this.cancel);this.input.keyboard?.on('keydown',this.keydown);this.input.keyboard?.on('keyup',this.keyup);this.input.keyboard?.addCapture(['SPACE','UP','DOWN','LEFT','RIGHT']);
  this.blur=()=>this.pauseGame();this.hidden=()=>{if(document.hidden)this.pauseGame();};this.resize=()=>{if(this.portrait())this.pauseGame();};this.game.events.on('blur',this.blur);document.addEventListener('visibilitychange',this.hidden);window.addEventListener('resize',this.resize);window.addEventListener('pointercancel',this.cancel);
  this.events.once('shutdown',()=>{canvas.style.touchAction=old;this.input.off('pointerdown',this.down);this.input.off('pointermove',this.move);this.input.off('pointerup',this.up);this.input.off('pointerupoutside',this.up);this.input.off('gameout',this.cancel);this.input.keyboard?.off('keydown',this.keydown);this.input.keyboard?.off('keyup',this.keyup);this.input.keyboard?.removeCapture(['SPACE','UP','DOWN','LEFT','RIGHT']);this.game.events.off('blur',this.blur);document.removeEventListener('visibilitychange',this.hidden);window.removeEventListener('resize',this.resize);window.removeEventListener('pointercancel',this.cancel);this.clearInput();this.stopTones();this.maskShape?.destroy();this.fieldMask?.destroy();});
  if(['crew','sky'].some(k=>!this.textures.exists('star_'+k))){this.add.rectangle(640,360,1280,720,0x173f43);this.text(640,260,'星航素材尚未載入\n請完整覆蓋 assets/forest-starflight 資料夾',32);this.b(640,450,340,80,'返回遊戲列表',()=>this.leave());return;}this.showTitle();
 }
 text(x,y,t,size=24,color='#fff3d2',origin=.5){return super.text(x,y,t,size,color,origin);}
 b(x,y,w,h,t,fn,color=0x31686b){const c=super.button(x,y,w,h,t,fn,color,'#fff7df');c.label.setFontSize(25);return c;}
 portrait(){return window.innerHeight>window.innerWidth;}
 clearInput(){this.touch?.reset();this.held?.clear();this.requests={};if(this.session){this.session.last={};this.session.pending={};}}
 clear(){this.clearInput();this.tweens.killAll();this.fieldMask?.destroy();this.maskShape?.destroy();this.fieldMask=null;this.maskShape=null;this.children.removeAll(true);this.views.clear();this.effects=[];this.overlay=null;}
 art(x,y,frame,size,parent=null){const im=this.add.image(x,y,'star_crew',frame);im.setScale(size/Math.max(im.width,im.height));parent?.add(im);return im;}
 showTitle(){this.clear();this.mode='title';this.add.image(640,360,'star_sky').setDisplaySize(1280,854);this.add.rectangle(640,360,1280,720,0x173f4c,.22);this.panel(838,347,808,654,0x153e4d,0xcab887,28);
  this.art(222,344,'hero',326);this.text(219,550,'阿晨晨，向雲端出發！',25,'#214e55');this.text(837,97,'森林星航瘋狂隊',49);this.text(837,157,'第一章  ·  糖果雲端嘉年華',28,'#f7d49d');
  this.text(837,254,'橫向飛行 × 編隊射擊 × 六格循環強化\n穿過雲海、市集與拱門，挑戰熊船長！',27);
  this.text(837,357,'金色能量 → 移動選取格 → 按「強化」兌換\n雙重與雷射擇一，飛彈、精靈與護盾可疊加。',24,'#c9e5dc');
  this.diffButton=this.b(653,449,332,60,'難度：標準',()=>{this.difficulty=this.difficulty==='normal'?'challenge':'normal';this.diffButton.label.setText(`難度：${this.difficulty==='normal'?'標準':'挑戰'}`);});
  this.autoButton=this.b(1014,449,332,60,'自動射擊：開',()=>{this.autoFire=!this.autoFire;this.autoButton.label.setText(`自動射擊：${this.autoFire?'開':'關'}`);});
  this.text(837,511,'一關約 7–11 分鐘 · 每段可重試 · 手機請橫放',22,'#d9d9ba');
  this.b(662,594,350,78,'← 遊戲列表',()=>this.leave());this.b(1022,594,333,78,'開始飛行',()=>this.start(),0xa87535);
 }
 start(checkpoint=null){if(this.portrait()){this.showMessage('請把手機橫放','左手移動，右手控制星爆、衝刺與強化。',()=>{this.overlay?.destroy();this.overlay=null;},'知道了');return;}
  this.session=new StarflightSession({difficulty:this.difficulty,checkpoint});this.renderGame();this.sound.context?.resume?.()?.catch?.(()=>{});if(!checkpoint)this.pauseGame(true);
 }
 renderGame(){this.clear();this.mode='playing';this.session.setPaused(false);this.soundCD=0;this.add.rectangle(640,360,1280,720,0x153d49);this.world=this.add.container(0,TOP);
  this.maskShape=this.add.graphics().fillStyle(0xffffff).fillRect(0,TOP,1280,H).setVisible(false);this.fieldMask=this.maskShape.createGeometryMask();this.world.setMask(this.fieldMask);
  this.background=[];for(let i=0;i<2;i++){const im=this.add.image(i*1280,0,'star_sky').setOrigin(0).setDisplaySize(1280,854);this.world.add(im);this.background.push(im);}
  this.scenery=this.add.graphics();this.world.add(this.scenery);this.entities=this.add.container(0,0);this.world.add(this.entities);this.fx=this.add.graphics();this.world.add(this.fx);
  this.add.rectangle(640,41,1280,82,0x173e48);this.hp=this.text(140,24,'',24);this.scoreLabel=this.text(438,24,'',24,'#ffdd94');this.stageLabel=this.text(745,24,'',25);this.meta=this.text(430,60,'',20,'#bddfd8');
  this.autoButton=this.b(1029,41,155,59,this.autoFire?'連射：開':'連射：關',()=>{this.autoFire=!this.autoFire;this.autoButton.label.setText(this.autoFire?'連射：開':'連射：關');},0x285863);this.b(1199,41,139,59,'暫停',()=>this.pauseGame());
  this.noticeText=this.text(640,TOP+32,'',25,'#fff1b1').setStroke('#254a56',5);this.bossText=this.text(640,TOP+68,'',23,'#ffdaae').setStroke('#254a56',4);
  this.add.rectangle(640,642,1280,156,0x173e48);this.control=this.add.graphics();this.powerLabels=[];for(let i=0;i<6;i++)this.powerLabels.push(this.text(248+i*102,603,'',22));this.instruction=this.text(378,675,'',19,'#c9e4db');this.upgradeLabel=this.text(698,678,'強化 · 空白鍵',24);this.fireLabel=this.text(1173,638,'按住\n射擊 J',26);this.dashLabel=this.text(909,668,'衝刺',24);this.bombLabel=this.text(1010,613,'星爆',23);this.text(101,709,'移動 / WASD',16,'#c5ddd4');this.drawState(0);
 }
 controlState(){const t=this.touch.read(),k=this.held;return {...t,x:t.x+Number(k.has('KeyD')||k.has('ArrowRight'))-Number(k.has('KeyA')||k.has('ArrowLeft')),y:t.y+Number(k.has('KeyS')||k.has('ArrowDown'))-Number(k.has('KeyW')||k.has('ArrowUp')),fire:this.autoFire||t.fire||k.has('KeyJ'),dash:t.dash||this.requests.dash,bomb:t.bomb||this.requests.bomb,upgrade:t.upgrade||this.requests.upgrade};}
 update(t,delta){if(this.mode!=='playing'||!this.session)return;const dt=Math.min(.1,delta/1000);if(this.session.advance(dt,this.controlState())){this.requests={};this.touch.consume();}
  this.soundOn=preferences.value.sfx;this.soundCD-=dt;for(const e of this.session.events.splice(0)){if(e.type!=='shot')this.effects.push({...e,age:0});if(this.soundCD<=0){this.tone(e.type==='shot'?'send':e.type==='hurt'?'hint':['end','boss','stage'].includes(e.type)?'finish':'correct');this.soundCD=e.type==='shot'?.22:.16;}}
  this.effects=this.effects.map(e=>({...e,age:e.age+dt})).filter(e=>e.age<.8).slice(-70);this.drawState(dt);if(this.session.status!=='playing')this.finish();
 }
 entity(id,x,y,frame,size){let v=this.views.get(id);if(!v){v=this.art(x,y,frame,size,this.entities);this.views.set(id,v);}v.setPosition(x,y);return v;}
 star(g,x,y,r,color,alpha=1){g.fillStyle(color,alpha);const pts=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.45:r;pts.push({x:x+Math.cos(a)*rr,y:y+Math.sin(a)*rr});}g.fillPoints(pts,true);}
 drawState(dt){const s=this.session,p=s.player,g=this.scenery,f=this.fx;g.clear();f.clear();for(let i=0;i<2;i++)this.background[i].setPosition(i*1280-(s.time*24)%1280,-170).setFlipX((Math.floor(s.time*24/1280)+i)%2===1).setTint(s.stage===2?0xddd7ff:s.stage===3?0xd6e2ff:0xffffff);
  // Procedural foreground layers and collidable arches remain sharp at mobile sizes.
  for(let i=0;i<9;i++){const x=((i*190-s.time*(42+i%2*14))%1710+1710)%1710-180,y=440+(i%3)*12;g.fillStyle(0xfff4dd,.65).fillEllipse(x,y,230,80);g.fillStyle(0xf5d7e5,.4).fillEllipse(x+70,y+25,240,70);}
  if(s.stage===1)for(let i=0;i<5;i++){const x=((i*320-s.time*62)%1600+1600)%1600-100;g.lineStyle(2,0xffefd6,.55).lineBetween(x,0,x,63);g.fillStyle(i%2?0xf1bbcd:0xb7dcd1,.5).fillEllipse(x,60,65,80);g.fillStyle(0x997346,.5).fillRoundedRect(x-16,109,32,18,4);}
  for(const gate of s.gates){const top=gate.gapY-gate.gap/2,bottom=gate.gapY+gate.gap/2;g.fillStyle(0x6f527c,.25).fillRect(gate.x-gate.w/2+10,0,gate.w,top+6).fillRect(gate.x-gate.w/2+10,bottom+6,gate.w,H-bottom);g.fillStyle(s.stage===2?0xb69ac8:0xd4ad8c).fillRoundedRect(gate.x-gate.w/2, -20,gate.w,top+20,14).fillRoundedRect(gate.x-gate.w/2,bottom,gate.w,H-bottom+20,14);g.lineStyle(4,0xffe8af).strokeRoundedRect(gate.x-gate.w/2,-20,gate.w,top+20,14).strokeRoundedRect(gate.x-gate.w/2,bottom,gate.w,H-bottom+20,14);for(let y=22;y<top;y+=40)g.lineStyle(2,0xffe7cf,.6).lineBetween(gate.x-30,y,gate.x+30,y);for(let y=bottom+25;y<480;y+=40)g.lineStyle(2,0xffe7cf,.6).lineBetween(gate.x-30,y,gate.x+30,y);g.lineStyle(2,0xffffff,.32).lineBetween(gate.x,top+22,gate.x,bottom-22);}
  const live=new Set();for(const e of s.enemies){const v=this.entity(e.id,e.x,e.y,KINDS[e.kind],e.kind===1?116:96);v.setFlipX(e.pattern==='rear').setAlpha(e.flash>0?.5:1);live.add(e.id);if(e.hp<e.maxHp){f.fillStyle(0x274a51,.5).fillRect(e.x-27,e.y-47,54,5);f.fillStyle(0xffedac).fillRect(e.x-27,e.y-47,54*e.hp/e.maxHp,5);}}
  const hero=this.entity('hero',p.x,p.y,'hero',118);hero.setRotation(this.controlState().y*.09).setAlpha(p.invuln>0?.55+Math.sin(s.time*28)*.25:1);live.add('hero');f.fillStyle(0xffffff,.9).fillCircle(p.x,p.y,4);f.lineStyle(2,0x2c8078).strokeCircle(p.x,p.y,6);
  if(p.shield>0)f.lineStyle(3,0x9cfff0,.65).strokeCircle(p.x,p.y,48+Math.sin(s.time*4)*3);if(p.dashing>0)f.lineStyle(14,0xffffff,.5).lineBetween(p.x-95,p.y,p.x-22,p.y);
  for(let i=0;i<s.upgrades[4];i++){const x=p.x-38*(i+1),y=p.y+(i%2?-36:36);this.star(f,x,y,18,0xffe295);f.fillStyle(0xffffff).fillCircle(x-4,y-3,3);}
  for(const item of s.pickups){if(item.kind==='rescue'){this.entity(item.id,item.x,item.y,'fairy',70);live.add(item.id);f.lineStyle(3,0xa2f4e9,.7).strokeCircle(item.x,item.y,40);}else{const col=item.kind==='energy'?0xffd16f:item.kind==='heart'?0xff95b6:0xa8f5ef;f.fillStyle(0x31596a,.85).fillCircle(item.x,item.y,21);this.star(f,item.x,item.y,17,col);if(item.kind==='energy')f.fillStyle(0xffffff).fillCircle(item.x,item.y,5);if(item.kind==='heart')f.lineStyle(4,0xffffff).lineBetween(item.x-8,item.y,item.x+8,item.y).lineBetween(item.x,item.y-8,item.x,item.y+8);}}
  if(s.boss){const b=s.boss;this.entity('boss',b.x,b.y,'boss',315);live.add('boss');g.fillStyle(0x233f50,.6).fillRoundedRect(405,8,470,14,7);g.fillStyle(0xf5b7d1).fillRoundedRect(405,8,470*Math.max(0,b.hp/b.maxHp),14,7);this.bossText.setText(`熊船長 · 第 ${b.phase} 階段`);if(b.beam>0){f.fillStyle(b.beam>.65?0xf094b9:0xfff1ce,b.beam>.65?.25:.9).fillRect(0,b.beamY-31,b.x,62);f.lineStyle(3,0xffc6e0).lineBetween(0,b.beamY-31,b.x,b.beamY-31).lineBetween(0,b.beamY+31,b.x,b.beamY+31);}}
  else this.bossText.setText('');for(const [id,v]of this.views)if(!live.has(id)){v.destroy();this.views.delete(id);}
  for(const a of s.shots){f.lineStyle(a.kind==='laser'?9:a.kind==='missile'?8:6,a.kind==='laser'?0xb8fff2:a.kind==='missile'?0xffc583:0xfff3a9,.95).lineBetween(a.x-(a.kind==='laser'?66:20),a.y,a.x,a.y);f.lineStyle(2,0xffffff).lineBetween(a.x-20,a.y,a.x,a.y);}
  for(const a of s.bullets){f.fillStyle(0x684678).fillCircle(a.x,a.y,10);f.fillStyle(0xf6aad6).fillCircle(a.x,a.y,7);f.fillStyle(0xffffff).fillCircle(a.x-2,a.y-2,3);}
  for(const w of s.warnings){const x=w.side==='left'?43:w.x,y=w.side==='top'?36:w.side==='bottom'?445:w.y;f.fillStyle(0xa83f5d,.85).fillTriangle(x-20,y+18,x,y-20,x+20,y+18);f.lineStyle(4,0xfff0b0).lineBetween(x,y-10,x,y+3).fillStyle(0xfff0b0).fillCircle(x,y+11,2);}
  for(const e of this.effects){if(e.type==='bomb'){f.fillStyle(0xfff8c9,(1-e.age/.8)*.35).fillRect(0,0,1280,H);f.lineStyle(14,0xfff3b0,1-e.age/.8).strokeCircle(e.x,e.y,40+e.age*1500);}else if(['pop','hurt','upgrade','energy','rescue','spark','end'].includes(e.type)){const color=e.type==='hurt'?0xff9bb8:e.type==='rescue'?0xa4f7df:0xffe39a;for(let i=0;i<8;i++){const a=i*Math.PI/4+e.age,x=e.x+Math.cos(a)*e.age*130,y=e.y+Math.sin(a)*e.age*110;this.star(f,x,y,Math.max(1,9-e.age*10),color,1-e.age/.8);}}}
  this.hp.setText(`生命 ${p.hp}/${p.maxHp}　盾 ${p.shield}`);this.scoreLabel.setText(`分數 ${s.score.toLocaleString()}　×${1+Math.min(3,Math.floor(s.chain/8))}`);this.stageLabel.setText(STAR_ACTS[s.stage]);this.meta.setText(`航程 ${Math.min(100,Math.floor(s.time/360*100))}%　·　救援 ${s.stats.rescued}　·　${s.weapon==='laser'?'貫穿雷射':s.weapon==='double'?'雙重射擊':'青葉連射'}`);this.noticeText.setText(s.noticeLife>0?s.notice:'');this.drawControls();
 }
 drawControls(){const s=this.session,g=this.control,p=s.player;g.clear();const j=this.touch.owner===null?STAR_CONTROLS.joystick:this.touch.origin;g.fillStyle(0x285760,.95).fillCircle(j.x,j.y,61).lineStyle(3,0xb1dacc).strokeCircle(j.x,j.y,61).fillStyle(0xb8dfcf).fillCircle(j.x+this.touch.axis.x*40,j.y+this.touch.axis.y*40,28);
  for(let i=0;i<6;i++){const x=201+i*102,selected=s.cursor===i;g.fillStyle(selected?0xc59143:0x28545e).fillRoundedRect(x,574,94,58,12).lineStyle(selected?3:1,selected?0xffedac:0x547b7b).strokeRoundedRect(x,574,94,58,12);this.powerLabels[i].setText(`${STAR_UPGRADES[i]}\n${i===5?p.shield:s.upgrades[i]}`).setFontSize(21);}
  const u=STAR_CONTROLS.upgrade;g.fillStyle(s.cursor>=0?0xa97838:0x30545a).fillRoundedRect(u.x-u.w/2,u.y-u.h/2,u.w,u.h,15);this.upgradeLabel.setText(s.cursor<0?'拾取能量後強化':`兌換${STAR_UPGRADES[s.cursor]} · 空白`);this.instruction.setText('金色能量：前進一格\n雙重／雷射擇一，其他可疊加');
  for(const key of ['fire','dash','bomb']){const c=STAR_CONTROLS[key];g.fillStyle(key==='fire'?0xa77a3e:key==='bomb'?0x705878:0x366b76).fillCircle(c.x,c.y,c.r).lineStyle(3,key==='fire'?0xffe5a2:0xc4d9d5).strokeCircle(c.x,c.y,c.r);}this.fireLabel.setText(this.autoFire?'自動\n射擊中':'按住\n射擊 J');this.dashLabel.setText(p.dashCD>0?`${p.dashCD.toFixed(1)}`:'衝刺\nShift');this.bombLabel.setText(`星爆 ${s.bombs}\nK`);
 }
 showMessage(title,body,fn,label='繼續飛行'){this.overlay?.destroy();const o=this.add.container(0,0).setDepth(100);this.overlay=o;o.add([this.add.rectangle(640,360,1280,720,0x102e3b,.78).setInteractive(),this.panel(640,350,960,570,0x193f4c,0xc8bc8d,28),this.text(640,133,title,38),this.text(640,296,body,26)]);o.add(this.b(640,534,390,72,label,fn,0x9c743c));return o;}
 pauseGame(help=false){if(this.mode!=='playing')return;this.mode='paused';this.session.setPaused(true);this.clearInput();this.stopTones();const o=this.showMessage(help?'飛行員小抄':'暫停飛行',help?'左手搖桿 / WASD：自由飛行　J：射擊\n金色能量讓選取格前進，空白鍵兌換強化\nShift：短暫無敵衝刺　K：清彈星爆\n星精靈可救援回血；粉紅彈、積木柱要避開。':'進度停在這裡，準備好再繼續。\n每段開始會補給；失敗可從當前段落重試。',()=>this.resumeGame());o.add(this.b(640,619,390,52,'返回遊戲列表',()=>this.leave(),0x315c65));}
 resumeGame(){if(this.mode!=='paused'||this.portrait())return;this.clearInput();this.overlay?.destroy();this.overlay=null;this.session.setPaused(false);this.mode='playing';}
 finish(){this.mode='finished';this.clearInput();this.tone('finish');const s=this.session,won=s.status==='won';const o=this.showMessage(won?'嘉年華挑戰成功！':'先回補給站休息一下',`分數 ${s.score.toLocaleString()}　·　救援 ${s.stats.rescued} 位星精靈\n擊退 ${s.stats.cleared} 位對手　·　強化 ${s.stats.upgrades} 次\n${won?'熊船長送來滿天星光，謝謝你的精彩飛行！':'重試會回到本段起點，恢復生命並保留段首裝備。'}`,()=>this.start(won?null:s.checkpoint),won?'再飛一次':'從本段起點重試');o.add(this.b(640,620,390,52,'返回遊戲列表',()=>this.leave()));}
 leave(){this.stopTones();this.clearInput();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
