import AnimalSnackGame from './AnimalSnackGame.js';
import {COUNTING_FRUITS,FRUIT_COUNTING_LEVELS,FruitCountingSession,buildFruitCountingItems} from '../data/FruitCountingData.js';

const BOARD_SPOTS=[{x:430,y:240},{x:650,y:225},{x:865,y:250},{x:405,y:420},{x:640,y:405},{x:875,y:430},{x:500,y:565},{x:765,y:565}];

export default class FruitCountingGame extends AnimalSnackGame {
    constructor(){super('FruitCountingGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new FruitCountingSession();this.busy=false;this.items=[];this.levelItems=[];this.basketFruitItems=[];
        this.drawOrchard();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawOrchard(){const g=this.add.graphics();g.fillGradientStyle(0xbfe3e6,0xe8efc7,0x8fc179,0x73aa68,1).fillRect(0,0,1280,720);g.fillStyle(0xffefae,.8).fillCircle(1110,125,60);g.fillStyle(0x6f9f5d).fillRect(0,580,1280,140);for(let i=0;i<7;i++){const x=300+i*155;g.fillStyle(0x70513c).fillRoundedRect(x-14,275,28,330,13);g.fillStyle(i%2?0x4f9662:0x5da064).fillCircle(x-65,260,95).fillCircle(x+55,250,105).fillCircle(x,185,105);g.fillStyle(0xffffff,.14).fillCircle(x-25,205,38);}for(let i=0;i<25;i++)g.fillStyle(i%2?0xfff5d0:0xf4c464,.55).fillCircle(290+(i*157)%780,135+(i*83)%430,3+i%5);}
    drawHud(){this.panel(640,43,1248,66,0xfff9e9,0xdacb9e,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x5a8660).setDepth(81);this.text(384,40,'水果數數・幼童版',30,'#3e664b').setDepth(81);this.levelText=this.text(662,43,'第 1 / 5 關',18,'#6c7f70').setDepth(81);this.soundButton=this.button(930,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xe6ead7,'#3e664b').setDepth(81);this.button(1090,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xe6ead7,'#3e664b').setDepth(81);
        this.panel(145,355,240,490,0xfff9e9,0xdacb9e,23).setDepth(60);this.text(145,122,'今天摘什麼？',22,'#3e664b').setDepth(61);this.targetFruit=this.add.container(145,205).setDepth(62);this.targetText=this.text(145,286,'',23,'#3e664b').setDepth(62);this.guideText=this.text(145,333,'',17,'#6c7f70').setWordWrapWidth(202,true).setDepth(62);this.progressText=this.text(145,411,'',31,'#3e664b').setDepth(62);this.statText=this.text(145,459,'',16,'#6c7f70').setDepth(62);this.hintButton=this.button(145,532,188,50,'✨ 水果提示',()=>this.hint(),0xe7bf63,'#5c4c28').setDepth(62);
        this.panel(1090,376,250,500,0xfff9e9,0xdacb9e,23).setDepth(60);this.text(1090,145,'數數小果籃',22,'#3e664b').setDepth(62);this.basketBack=this.drawBasket(1090,450).setDepth(62);this.countWord=this.text(1090,585,'準備開始',22,'#3e664b').setDepth(64);this.feedback=this.text(650,106,'看看左邊，找到今天要摘的水果。',20,'#355d45').setDepth(81);this.text(675,694,'點指定水果放進籃子｜點到別種水果不扣分，會告訴你再找找',16,'#355d45').setDepth(70);
    }
    drawLevel(){this.levelItems.forEach(item=>item.destroy());this.levelItems=[];this.items=[];this.basketFruitItems.forEach(item=>item.destroy());this.basketFruitItems=[];this.busy=false;const level=this.session.level,friend=COUNTING_FRUITS.find(f=>f.id===level.fruit);this.levelText.setText(`第 ${this.session.levelIndex+1} / ${FRUIT_COUNTING_LEVELS.length} 關`);this.targetFruit.removeAll(true);this.targetFruit.add(this.drawFruitShape(friend,0,0,.95));this.targetText.setText(`找 ${level.target} 顆${friend.name}`);this.guideText.setText(level.guide);
        const raw=buildFruitCountingItems(this.session.levelIndex),shift=(this.session.levelIndex*2+1)%raw.length,ordered=raw.slice(shift).concat(raw.slice(0,shift));ordered.forEach((data,index)=>{const view=this.drawBoardFruit(data,BOARD_SPOTS[index],index);this.items.push(view);this.levelItems.push(view.container);});this.refresh();
    }
    drawFruitShape(friend,x=0,y=0,scale=1){const c=this.add.container(x,y).setScale(scale),g=this.add.graphics();if(friend.id==='apple'){g.fillStyle(friend.color).fillCircle(-17,5,33).fillCircle(17,5,33).fillEllipse(0,18,69,61);g.fillStyle(0x6f4b30).fillRoundedRect(-4,-40,8,29,4);g.fillStyle(friend.leaf).fillEllipse(16,-31,31,14);}else if(friend.id==='orange'){g.fillStyle(friend.color).fillCircle(0,5,42);g.fillStyle(0xffc766,.45).fillCircle(-14,-10,12);g.fillStyle(friend.leaf).fillEllipse(12,-38,31,14);g.fillStyle(0x6b4b2c).fillRoundedRect(-3,-37,6,14,3);}else if(friend.id==='pear'){g.fillStyle(friend.color).fillCircle(0,18,39).fillEllipse(0,-4,48,68);g.fillStyle(0xe1ed91,.45).fillCircle(-12,7,10);g.fillStyle(0x65492f).fillRoundedRect(-4,-48,8,22,4);g.fillStyle(friend.leaf).fillEllipse(15,-41,29,13);}else{g.fillStyle(friend.color).fillTriangle(-42,-18,42,-18,0,53);g.fillCircle(0,-13,42);g.fillStyle(friend.leaf).fillTriangle(-36,-27,-9,-45,-3,-17).fillTriangle(-7,-22,8,-49,14,-18).fillTriangle(8,-20,38,-37,27,-11);g.fillStyle(0xffe49b);for(let i=0;i<7;i++)g.fillEllipse(-22+(i*17)%48,-4+Math.floor(i/3)*18,5,9);}c.add(g);return c;}
    drawBoardFruit(data,spot,index){const friend=COUNTING_FRUITS.find(f=>f.id===data.fruit),c=this.add.container(spot.x,spot.y).setDepth(35),shadow=this.add.ellipse(0,60,112,28,0x244a35,.2),halo=this.add.circle(0,0,67,0xfff4a8,.08),fruit=this.drawFruitShape(friend,0,0,1),label=this.text(0,78,String(index+1),15,'#fff7d6'),hit=this.add.circle(0,5,68,0xffffff,.001).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.choose(data.id));c.add([shadow,halo,fruit,label,hit]);this.tweens.add({targets:c,y:spot.y-6,duration:800+index*70,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});return{...data,container:c,halo,friend};}
    drawBasket(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.lineStyle(11,0x8a5e36).strokeEllipse(0,-38,178,152);g.fillStyle(0xc98a48).fillRoundedRect(-100,-25,200,135,26);g.lineStyle(5,0x9b6638);for(let i=-70;i<=70;i+=35)g.lineBetween(i,-19,i,103);for(let y2=5;y2<=82;y2+=26)g.lineBetween(-94,y2,94,y2);g.fillStyle(0xe0a45d,.55).fillRoundedRect(-88,-15,176,23,10);c.add(g);return c;}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-8]$/.test(e.code))this.choose(this.items[Number(e.code.slice(-1))-1]?.id);else if(e.code==='KeyH')this.hint();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    choose(id){if(this.mode!=='playing'||this.busy)return;const item=this.items.find(v=>v.id===id),result=this.session.choose(item);if(!item||result.result==='ignored')return;if(result.result==='retry'){this.feedback.setText(`這是${item.friend.name}，今天要找的是${COUNTING_FRUITS.find(f=>f.id===this.session.level.fruit).name}喔！`);this.tone('hint');this.tweens.add({targets:item.container,x:item.container.x+10,duration:65,yoyo:true,repeat:3});this.refresh();return;}this.busy=true;this.feedback.setText(result.result==='complete'?`${result.count}！剛剛好，果籃裝好了！`:`${result.count}！放進一顆，還差 ${result.remaining} 顆。`);this.countWord.setText(`${result.count}！`);this.tone('correct');const startX=item.container.x,startY=item.container.y;this.tweens.killTweensOf(item.container);this.tweens.addCounter({from:0,to:1,duration:580,ease:'Sine.easeInOut',onUpdate:t=>{const p=t.getValue();item.container.setPosition(Phaser.Math.Linear(startX,1090,p),Phaser.Math.Linear(startY,405,p)-Math.sin(p*Math.PI)*90).setScale(1-p*.55).setAngle(p*220);},onComplete:()=>{item.container.setVisible(false);this.addBasketFruit(item.friend,this.session.collected-1);this.sparkles(1090,405);this.busy=false;this.refresh();if(result.result==='complete'){this.busy=true;this.time.delayedCall(650,()=>this.finishLevel());}}});}
    addBasketFruit(friend,index){const cols=3,x=1040+(index%cols)*50,y=394+Math.floor(index/cols)*52,item=this.drawFruitShape(friend,x,y,.42).setDepth(65);this.basketFruitItems.push(item);this.tweens.add({targets:item,scale:.5,duration:180,yoyo:true});}
    hint(){if(this.mode!=='playing'||this.busy)return;const id=this.session.hint(this.items),item=this.items.find(v=>v.id===id);if(!item)return;this.feedback.setText(`提示：會發光的${item.friend.name}可以放進籃子。`);this.tone('hint');this.tweens.add({targets:item.halo,alpha:.95,scale:1.35,duration:230,yoyo:true,repeat:3});this.refresh();}
    refresh(){const level=this.session.level;this.progressText.setText(`${this.session.collected} / ${level.target} 顆`);this.statText.setText(`還差 ${this.session.remaining} 顆\n溫暖提醒 ${this.session.wrong} 次\n提示 ${this.session.hints} 次`);if(!this.session.collected)this.countWord.setText(`要裝 ${level.target} 顆`);}
    sparkles(x,y){for(let i=0;i<10;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd75f:0xffffff).setDepth(72),a=i/10*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*78,y:y+Math.sin(a)*62,alpha:0,angle:140,duration:500,onComplete:()=>s.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===FRUIT_COUNTING_LEVELS.length-1;this.mode='levelComplete';this.busy=false;this.tone('finish');const o=this.makeOverlay(last?'水果數數派對完成！':'小果籃裝好了！',last?`從 1 數到 5，五個果籃全部完成！\n共放進 ${this.session.totalCollected} 顆水果　溫暖提醒 ${this.session.wrong} 次`:`${this.session.level.name}完成！\n一顆一顆放進去，就能看見數字變大。`);if(last){o.add(this.button(500,485,230,58,'再數一次',()=>this.restart(),0x5a8660));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe7bf63,'#5c4c28'));}else o.add(this.button(640,485,270,58,'下一個果籃',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('看看新的水果和數字，再一顆一顆找。');},0x5a8660));}
    showIntro(){const o=this.makeOverlay('一起到果園數水果！','看看左邊今天要找哪種水果、要找幾顆。\n點對的水果會飛進籃子，數字也會一顆一顆增加。\n點到別種水果不扣分，會告訴你再找找。');o.add(this.text(640,410,'沒有倒數與生命；看不出來時可以按水果提示。',19,'#687f79'));o.add(this.button(640,500,290,60,'開始摘水果！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0x5a8660));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('在果樹下休息一下','看左邊指定的水果與數量，再點果樹上的大水果。\n點錯不扣分；水果提示會讓下一顆正確水果發光。\n數字鍵 1～8 選擇，H 顯示提示。');o.add(this.button(640,415,270,55,'繼續數水果',()=>this.resumeGame(),0x5a8660));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xe6ead7,'#3e664b'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
