import AnimalSnackGame from './AnimalSnackGame.js';
import {COUNTING_FRUITS,FRUIT_COUNTING_LEVELS,FruitCountingSession,buildFruitCountingItems} from '../data/FruitCountingData.js';

const BOARD_SPOTS=Array.from({length:12},(_,i)=>({x:350+(i%4)*155,y:210+Math.floor(i/4)*160}));
const fruitInfo=id=>COUNTING_FRUITS.find(f=>f.id===id);
const icons=counts=>Object.entries(counts||{}).map(([id,n])=>`${fruitInfo(id)?.icon||'●'} × ${n}`).join('　');

export default class FruitCountingGame extends AnimalSnackGame {
    constructor(){super('FruitCountingGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new FruitCountingSession();this.busy=false;this.items=[];this.levelItems=[];this.basketFruitItems=[];this.timeRemaining=0;this.memoryRemaining=0;this.orderHidden=false;this.squirrelClock=0;
        this.drawOrchard();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    update(_time,delta){
        if(this.mode!=='playing')return;const dt=Math.min(.05,Math.max(0,delta/1000)),level=this.session.level;
        if(level.timeLimit){this.timeRemaining=Math.max(0,this.timeRemaining-dt);this.timerText.setText(`⏳ ${Math.ceil(this.timeRemaining)} 秒`);if(this.timeRemaining<=0){this.failLevel('時間到了！森林朋友會保留訂單，準備好再挑戰一次。');return;}}
        if(level.memorySeconds&&!this.orderHidden){this.memoryRemaining-=dt;if(this.memoryRemaining<=0){this.orderHidden=true;this.refreshOrder();this.feedback.setText('訂單藏起來了，靠記憶完成吧！');this.tone('hint');}}
        if(level.squirrel){this.squirrelClock-=dt;if(this.squirrelClock<=0){this.squirrelClock=5.2;this.squirrelRaid();}}
    }
    drawOrchard(){const g=this.add.graphics();g.fillGradientStyle(0x9fd5d5,0xeaf0c4,0x4f8d65,0x2f694e,1).fillRect(0,0,1280,720);g.fillStyle(0xffe995,.75).fillCircle(1115,118,55);for(let i=0;i<7;i++){const x=255+i*160;g.fillStyle(0x684a37).fillRoundedRect(x-12,270,24,350,12);g.fillStyle(i%2?0x408b5c:0x52975e).fillCircle(x-55,250,87).fillCircle(x+49,245,94).fillCircle(x,185,94);}g.fillStyle(0x285a43,.55).fillRect(0,610,1280,110);for(let i=0;i<36;i++)g.fillStyle(i%3?0xffe78c:0xffffff,.45).fillCircle(240+(i*149)%840,125+(i*71)%470,3+i%5);}
    drawHud(){
        this.panel(640,43,1248,66,0xfff9e9,0xd7c895,19).setDepth(80);this.button(98,43,148,43,'← 遊戲列表',()=>this.leave(),0x477b64).setDepth(81);this.text(365,40,'魔法果園・訂單大作戰',27,'#315e48').setDepth(81);this.levelText=this.text(650,43,'第 1 / 10 關',18,'#65786b').setDepth(81);this.timerText=this.text(790,43,'',19,'#a75d3e').setDepth(81);this.soundButton=this.button(932,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xe2ead8,'#315e48').setDepth(81);this.button(1091,43,165,43,'暫停 / 說明',()=>this.pauseGame(),0xe2ead8,'#315e48').setDepth(81);
        this.panel(155,360,260,500,0xfffae9,0xd7c895,23).setDepth(60);this.customerText=this.text(155,126,'',19,'#805c37').setDepth(62);this.orderTitle=this.text(155,165,'今日訂單',25,'#315e48').setDepth(62);this.orderText=this.text(155,255,'',23,'#315e48').setWordWrapWidth(224,true).setDepth(62);this.guideText=this.text(155,355,'',16,'#62786d').setWordWrapWidth(222,true).setDepth(62);this.progressText=this.text(155,430,'',27,'#315e48').setDepth(62);this.hintButton=this.button(155,525,200,50,'✨ 魔法提示',()=>this.hint(),0xe8c15f,'#5c4b28').setDepth(62);
        this.panel(1110,365,245,490,0xfffae9,0xd7c895,23).setDepth(60);this.text(1110,133,'魔法果籃',23,'#315e48').setDepth(62);this.basketBack=this.drawBasket(1110,420).setDepth(62);this.countWord=this.text(1110,555,'準備接單',21,'#315e48').setDepth(65);this.comboText=this.text(1110,600,'',19,'#a65c36').setDepth(65);
        this.feedback=this.text(650,105,'閱讀訂單，找出正確水果。',19,'#315e48').setDepth(81);this.scoreText=this.text(1100,682,'分數 0',18,'#fff8d6').setDepth(82);
    }
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.items=[];this.basketFruitItems.forEach(v=>v.destroy());this.basketFruitItems=[];this.busy=false;this.orderHidden=false;const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${FRUIT_COUNTING_LEVELS.length} 關`);this.customerText.setText(`委託人：${level.customer}`);this.guideText.setText(level.guide);this.timeRemaining=level.timeLimit||0;this.memoryRemaining=level.memorySeconds||0;this.squirrelClock=4.5;this.timerText.setText(level.timeLimit?`⏳ ${level.timeLimit} 秒`:'');
        const raw=buildFruitCountingItems(this.session.levelIndex),shift=(this.session.levelIndex*3+1)%raw.length,ordered=raw.slice(shift).concat(raw.slice(0,shift));ordered.forEach((data,index)=>{const view=this.drawBoardFruit(data,BOARD_SPOTS[index],index);this.items.push(view);this.levelItems.push(view.container);});this.refreshOrder();this.refresh();
    }
    startLevel(){this.mode='playing';this.sound.context?.resume?.();this.feedback.setText(this.session.level.memorySeconds?`先記住訂單！${this.session.level.memorySeconds} 秒後會隱藏。`:'訂單開始！連續選對可以提高連擊分數。');}
    refreshOrder(){const level=this.session.level;if(this.orderHidden){this.orderText.setText('🌙 訂單已隱藏\n靠記憶完成');return;}if(level.type==='sequence'){this.orderText.setText((level.headline?`${level.headline}\n`:'')+level.sequence.map((id,i)=>`${i+1}.${fruitInfo(id).icon}`).join('  '));}else this.orderText.setText(`${level.headline?level.headline+'\n':''}${icons(level.requirements)}`);}
    drawFruitShape(friend,x=0,y=0,scale=1,data={}){const c=this.add.container(x,y).setScale(scale),g=this.add.graphics();
        if(friend.id==='apple'){g.fillStyle(friend.color).fillCircle(-17,5,33).fillCircle(17,5,33).fillEllipse(0,18,69,61);g.fillStyle(0x6f4b30).fillRoundedRect(-4,-40,8,29,4);g.fillStyle(friend.leaf).fillEllipse(16,-31,31,14);}
        else if(friend.id==='orange'){g.fillStyle(friend.color).fillCircle(0,5,42);g.fillStyle(0xffcc79,.5).fillCircle(-14,-10,12);g.fillStyle(friend.leaf).fillEllipse(12,-38,31,14);}
        else if(friend.id==='pear'){g.fillStyle(data.ripe===false?0x73805d:friend.color).fillCircle(0,18,39).fillEllipse(0,-4,48,68);g.fillStyle(0x65492f).fillRoundedRect(-4,-48,8,22,4);g.fillStyle(friend.leaf).fillEllipse(15,-41,29,13);}
        else if(friend.id==='strawberry'){g.fillStyle(friend.color).fillTriangle(-42,-18,42,-18,0,53);g.fillCircle(0,-13,42);g.fillStyle(friend.leaf).fillTriangle(-36,-27,-9,-45,-3,-17).fillTriangle(-7,-22,8,-49,14,-18).fillTriangle(8,-20,38,-37,27,-11);g.fillStyle(0xffe49b);for(let i=0;i<7;i++)g.fillEllipse(-22+(i*17)%48,-4+Math.floor(i/3)*18,5,9);}
        else if(friend.id==='grape'){g.fillStyle(friend.color);[[-18,-18],[10,-20],[27,3],[-28,7],[0,8],[20,30],[-10,34],[2,56]].forEach(([a,b])=>g.fillCircle(a,b,19));g.fillStyle(friend.leaf).fillEllipse(9,-45,39,18);}
        else {g.fillStyle(friend.color).fillEllipse(0,5,82,55);g.fillStyle(0xffffff,.24).fillEllipse(-17,-7,25,10);g.fillStyle(friend.leaf).fillEllipse(22,-31,31,13);}
        if(data.special==='rainbow'){g.lineStyle(7,0xff6688,.9).strokeCircle(0,5,54);g.lineStyle(5,0x55c9ff,.9).strokeCircle(0,5,62);}
        c.add(g);return c;
    }
    drawBoardFruit(data,spot,index){const friend=fruitInfo(data.fruit),c=this.add.container(spot.x,spot.y).setDepth(35),shadow=this.add.ellipse(0,58,105,25,0x173c2c,.25),halo=this.add.circle(0,3,65,data.ripe?0xffdf62:0xffffff,data.ripe?.22:.05),fruit=this.drawFruitShape(friend,0,0,.86,data),badge=data.special==='rainbow'?this.text(0,-66,'彩虹果',14,'#fff5c8'):this.text(0,-66,'',14),hit=this.add.circle(0,4,67,0xffffff,.001).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.choose(data.id));c.add([shadow,halo,fruit,badge,hit]);this.tweens.add({targets:c,y:spot.y-5,duration:760+index*47,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});return{...data,container:c,halo,friend,visible:true};}
    drawBasket(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.lineStyle(10,0x805631).strokeEllipse(0,-38,168,145);g.fillStyle(0xc98a48).fillRoundedRect(-94,-20,188,130,25);g.lineStyle(4,0x996336);for(let i=-65;i<=65;i+=32)g.lineBetween(i,-14,i,102);for(let y2=8;y2<=82;y2+=25)g.lineBetween(-88,y2,88,y2);c.add(g);return c;}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-9]$/.test(e.code))this.choose(this.items[Number(e.code.slice(-1))-1]?.id);else if(e.code==='Digit0')this.choose(this.items[9]?.id);else if(e.code==='KeyH')this.hint();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    choose(id){if(this.mode!=='playing'||this.busy)return;const item=this.items.find(v=>v.id===id);if(!item||!item.visible)return;const result=this.session.choose(item);if(result.result==='ignored')return;
        if(result.result==='retry'||result.result==='failed'){this.feedback.setText(result.reason==='unripe'?'這顆還沒成熟，找帶金色光圈的果實！':'這顆不符合訂單，重新觀察條件。');this.tone('hint');this.tweens.add({targets:item.container,x:item.container.x+10,duration:60,yoyo:true,repeat:3});this.refresh();if(result.result==='failed')this.time.delayedCall(450,()=>this.failLevel('精準果籃的失誤次數用完了，再看清楚訂單試一次。'));return;}
        this.busy=true;this.feedback.setText(result.result==='complete'?`訂單完成！本顆 +${result.points} 分`:`選對了！本顆 +${result.points} 分，還差 ${result.remaining} 顆。`);this.tone('correct');const startX=item.container.x,startY=item.container.y;this.tweens.killTweensOf(item.container);this.tweens.addCounter({from:0,to:1,duration:520,ease:'Sine.easeInOut',onUpdate:t=>{const p=t.getValue();item.container.setPosition(Phaser.Math.Linear(startX,1110,p),Phaser.Math.Linear(startY,390,p)-Math.sin(p*Math.PI)*85).setScale(1-p*.52).setAngle(p*210);},onComplete:()=>{item.visible=false;item.container.setVisible(false);this.addBasketFruit(item.friend,this.session.collected-1,item);this.sparkles(1110,390);this.busy=false;this.refresh();if(this.mode!=='playing')return;if(result.result==='complete'){this.busy=true;this.time.delayedCall(650,()=>{if(this.mode==='playing')this.finishLevel();});}}});
    }
    addBasketFruit(friend,index,data){const x=1055+(index%3)*53,y=360+Math.floor(index/3)*47,item=this.drawFruitShape(friend,x,y,.34,data).setDepth(65);this.basketFruitItems.push(item);this.tweens.add({targets:item,scale:.43,duration:170,yoyo:true});}
    hint(){if(this.mode!=='playing'||this.busy)return;const id=this.session.hint(this.items.filter(i=>i.visible)),item=this.items.find(v=>v.id===id);if(!item)return;this.feedback.setText('魔法提示：發光的水果符合下一步訂單。');this.tone('hint');this.tweens.add({targets:item.halo,alpha:.95,scale:1.35,duration:220,yoyo:true,repeat:3});this.refresh();}
    refresh(){this.progressText.setText(`${this.session.collected} / ${this.session.target} 顆`);this.countWord.setText(this.session.collected?`已裝 ${this.session.collected} 顆`:`要裝 ${this.session.target} 顆`);this.comboText.setText(this.session.combo>=2?`🔥 ${this.session.combo} 連擊`:`失誤 ${this.session.levelWrong}${this.session.level.mistakeLimit?' / '+this.session.level.mistakeLimit:''}`);this.scoreText.setText(`分數 ${this.session.totalScore}`);if(this.session.level.type==='sequence'&&!this.orderHidden)this.progressText.setText(`順序 ${this.session.collected} / ${this.session.target}`);}
    squirrelRaid(){if(this.busy)return;const candidates=this.items.filter(i=>i.visible&&!this.session.taken.has(i.id));if(!candidates.length)return;const victim=candidates[Math.floor((this.timeRemaining+this.session.collected)%candidates.length)];victim.visible=false;victim.container.setVisible(false);const s=this.text(980,155,'🐿️',48,'#fff').setDepth(90);this.feedback.setText(`松鼠暫時藏起一顆${victim.friend.name}！`);this.tweens.add({targets:s,x:victim.container.x,y:victim.container.y,duration:450,yoyo:true,hold:450,onComplete:()=>s.destroy()});this.time.delayedCall(1800,()=>{if(!this.session.taken.has(victim.id)){victim.visible=true;victim.container.setVisible(true);}});}
    sparkles(x,y){for(let i=0;i<12;i++){const s=this.add.star(x,y,5,3,8,i%3?0xffd75f:0xffffff).setDepth(72),a=i/12*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*82,y:y+Math.sin(a)*66,alpha:0,angle:150,duration:480,onComplete:()=>s.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===FRUIT_COUNTING_LEVELS.length-1;this.mode='levelComplete';this.busy=false;this.tone('finish');const bonus=Math.max(0,500-this.session.levelWrong*100);this.session.totalScore+=bonus;this.scoreText.setText(`分數 ${this.session.totalScore}`);const o=this.makeOverlay(last?'魔法豐收節完成！':'森林訂單完成！',last?`十張魔法訂單全部完成！\n總分 ${this.session.totalScore}　採收 ${this.session.totalCollected} 顆　失誤 ${this.session.wrong} 次`:`${this.session.level.name} 完成\n關卡獎勵 +${bonus} 分　連續正確最高可獲得更多採收分數。`);if(last){o.add(this.button(500,485,230,58,'重新開園',()=>this.restart(),0x477b64));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe8c15f,'#5c4b28'));}else o.add(this.button(640,485,270,58,'接下一張訂單',()=>{o.destroy();this.overlay=null;this.session.advance();this.drawLevel();this.startLevel();},0x477b64));}
    failLevel(message){if(this.mode!=='playing')return;this.mode='failed';this.busy=false;this.stopTones();const o=this.makeOverlay('訂單還沒有完成',message);o.add(this.button(640,470,270,58,'重新挑戰這一關',()=>{o.destroy();this.overlay=null;this.session.load();this.drawLevel();this.startLevel();},0x477b64));}
    showIntro(){const o=this.makeOverlay('歡迎來到魔法果園！','十張訂單包含混合數量、加減法、順序記憶、成熟度與限時挑戰。\n連續選對可提高連擊分數；彩虹果能代替一顆尚缺的水果。\n松鼠偶爾會把水果藏起來，但稍後就會放回。');o.add(this.text(640,415,'沒有生命歸零；失敗的訂單可以立即重新挑戰。',19,'#687f79'));o.add(this.button(640,505,300,60,'開始接訂單！',()=>{o.destroy();this.overlay=null;this.startLevel();},0x477b64));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('果園暫停營業','閱讀左側訂單，再選取中央果樹上的水果。\n金色光圈代表成熟果實；彩虹果可以補上一顆缺少的水果。\n鍵盤可用 1～0 選擇，H 顯示提示。');o.add(this.button(640,420,270,55,'繼續接訂單',()=>this.resumeGame(),0x477b64));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xe2ead8,'#315e48'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
