import AnimalSnackGame from './AnimalSnackGame.js';
import {HotSpringCapybaraSession,HOT_SPRING_LEVELS,CAPYBARA_STYLES} from '../data/HotSpringCapybaraData.js';

export default class HotSpringCapybaraGame extends AnimalSnackGame {
    constructor(){super('HotSpringCapybaraGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new HotSpringCapybaraSession();this.slow=true;this.busy=false;this.pools=[];this.levelItems=[];this.previewTimer=null;
        this.drawValley();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&['playing','preview','feedback'].includes(this.mode))this.pauseGame();};this.blurHandler=()=>{if(['playing','preview','feedback'].includes(this.mode))this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.previewTimer?.remove(false);this.stopTones();});
    }
    drawValley(){const g=this.add.graphics();g.fillGradientStyle(0x754658,0xbd6b61,0xf3a666,0x543548,1).fillRect(0,0,1280,720);g.fillStyle(0x5a3e48).fillTriangle(0,400,240,95,500,400).fillTriangle(790,405,1055,80,1280,405);g.fillStyle(0xf1784e).fillTriangle(198,150,240,95,285,150).fillTriangle(1012,135,1055,80,1097,135);g.fillStyle(0x786256).fillEllipse(640,620,1450,440);for(let i=0;i<35;i++)g.fillStyle(i%2?0xffd28a:0xffffff,.35).fillCircle(24+(i*151)%1230,90+(i*73)%575,3+i%5);}
    drawHud(){this.panel(640,43,1248,66,0xfff1dc,0xe5af75,19).setDepth(80);this.button(105,43,160,43,'← 備選小島',()=>this.leave(),0x99505a).setDepth(81);this.text(425,40,'溫泉水豚躲貓貓',30,'#713942').setDepth(81);this.levelText=this.text(690,43,'第 1 / 5 關',18,'#9a5f55').setDepth(81);this.soundButton=this.button(940,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xf2d9ad,'#713942').setDepth(81);this.button(1098,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xf2d9ad,'#713942').setDepth(81);this.feedback=this.text(650,103,'水豚準備從溫泉裡探頭囉！',20,'#ffe7bc').setDepth(81);}
    drawLevel(){
        this.previewTimer?.remove(false);this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.pools=[];const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${HOT_SPRING_LEVELS.length} 關`);
        const side=this.panel(145,375,245,510,0xfff2dd,0xd7a56f,24).setDepth(40);this.levelItems.push(side,this.text(145,145,level.name,23,'#713942').setDepth(41));
        this.levelItems.push(this.text(145,195,level.guide,16,'#976250').setDepth(41));this.targetBadge=this.makeTargetBadge(145,292);this.levelItems.push(this.targetBadge);
        this.progressText=this.text(145,380,'',22,'#713942').setDepth(41);this.statText=this.text(145,442,'',15,'#976250').setDepth(41);this.hintButton=this.button(145,510,195,48,'👀 再看一次',()=>this.showHint(),0xd48a68,'#fff8e8').setDepth(42);this.slowButton=this.button(145,570,195,48,'慢慢看：開',()=>this.toggleSlow(),0xf0cf8d,'#6c4038').setDepth(42);this.levelItems.push(this.progressText,this.statText,this.hintButton,this.slowButton);
        const positions=this.poolPositions(level.poolCount);this.session.board.forEach((tile,index)=>this.makePool(tile,positions[index],index));this.refresh();
    }
    poolPositions(count){if(count===3)return[[440,360],[675,360],[910,360]];if(count===4)return[[500,285],[800,285],[500,515],[800,515]];if(count===5)return[[430,285],[650,285],[870,285],[540,515],[760,515]];return[[430,285],[650,285],[870,285],[430,515],[650,515],[870,515]];}
    makeTargetBadge(x,y){const c=this.add.container(x,y).setDepth(43),bg=this.add.circle(0,0,70,0xffdfab).setStrokeStyle(4,CAPYBARA_STYLES[this.session.target].color),capy=this.drawCapybara(this.session.target).setScale(.72),label=this.text(0,87,`找「${CAPYBARA_STYLES[this.session.target].short}」`,18,'#713942');c.add([bg,capy,label]);return c;}
    makePool(tile,[x,y],index){const c=this.add.container(x,y).setDepth(25),steam=this.add.container(),stones=this.add.graphics(),water=this.add.ellipse(0,22,190,83,0x83d7d5,.92).setStrokeStyle(5,0xd7eee2),capy=tile.style?this.drawCapybara(tile.style):null,cover=this.add.ellipse(0,27,155,51,0x6fc5c7,.96),number=this.text(0,82,String(index+1),16,'#fff2d1');for(let i=0;i<3;i++){const puff=this.add.circle(-45+i*45,-54-i%2*12,18+i*3,0xffffff,.25);steam.add(puff);this.tweens.add({targets:puff,y:puff.y-28,alpha:.05,duration:1300+i*170,yoyo:true,repeat:-1});}for(let i=0;i<12;i++){const a=i/12*Math.PI*2;stones.fillStyle(i%2?0xb89a7b:0xd0b38f).fillCircle(Math.cos(a)*94,22+Math.sin(a)*44,20);}if(capy){capy.y=24;capy.setVisible(false).setAlpha(0);}c.add([steam,stones,water]);if(capy)c.add(capy);c.add([cover,number]);c.setSize(215,175).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.choosePool(index));const view={c,steam,water,capy,cover,number,tile,index};this.pools.push(view);this.levelItems.push(c);}
    drawCapybara(style){const c=this.add.container(0,-6),g=this.add.graphics();g.fillStyle(0xb68160).fillEllipse(0,25,106,82).fillCircle(0,-16,50);g.fillStyle(0x9b684f).fillCircle(-37,-44,15).fillCircle(37,-44,15);g.fillStyle(0xd3a17b).fillEllipse(0,-2,63,42);g.fillStyle(0x3f3434).fillCircle(-17,-20,5).fillCircle(17,-20,5).fillCircle(0,-2,7);g.lineStyle(3,0x5b3e3a).beginPath().arc(0,5,15,.3,2.84).strokePath();if(style==='orange'){g.fillStyle(0xf28c3d).fillCircle(0,-70,20);g.fillStyle(0x62a458).fillEllipse(13,-87,20,10);}else if(style==='flower'){for(let i=0;i<5;i++){const a=i/5*Math.PI*2;g.fillStyle(0xf58caf).fillCircle(Math.cos(a)*13,-69+Math.sin(a)*13,9);}g.fillStyle(0xffd65f).fillCircle(0,-69,8);}else if(style==='towel'){g.fillStyle(0x8bd5df).fillRoundedRect(-31,-82,62,25,8);g.fillStyle(0xdff7f6,.65).fillRect(-18,-78,36,7);}else if(style==='leaf'){g.fillStyle(0x68aa65).fillEllipse(0,-70,42,18);g.lineStyle(3,0x3e7545).lineBetween(-17,-70,18,-70);}c.add(g);return c;}
    setCapyVisible(view,visible){if(!view.capy)return;if(visible){view.capy.setVisible(true);this.tweens.killTweensOf(view.capy);this.tweens.add({targets:view.capy,y:-22,alpha:1,duration:330,ease:'Back.easeOut'});}else{this.tweens.killTweensOf(view.capy);this.tweens.add({targets:view.capy,y:25,alpha:0,duration:260,onComplete:()=>view.capy?.setVisible(false)});}}
    startPreview(fromHint=false){if(this.session.complete)return;this.previewTimer?.remove(false);this.mode='preview';this.busy=true;this.session.preview();this.pools.forEach(v=>this.setCapyVisible(v,true));this.feedback.setText(fromHint?'再看一次：記住每隻水豚的位置！':'水豚一起探頭了，記住牠們的裝飾！');this.tone('hint');this.refresh();this.previewTimer=this.time.delayedCall(this.slow?3100:2100,()=>{this.pools.forEach(v=>this.setCapyVisible(v,false));this.previewTimer=this.time.delayedCall(300,()=>{this.busy=false;this.mode='playing';this.feedback.setText(`水豚躲好了！找出${CAPYBARA_STYLES[this.session.target].name}。`);});});}
    choosePool(index){if(this.mode!=='playing'||this.busy)return;const result=this.session.choose(index);if(result.result==='ignored')return;const view=this.pools[index];if(result.result==='retry'){this.busy=true;this.mode='feedback';this.setCapyVisible(view,true);this.tone('hint');const found=result.chosen?CAPYBARA_STYLES[result.chosen].short:'空溫泉';this.feedback.setText(`這裡是${found}，沒關係，大家再露臉一次！`);this.refresh();this.previewTimer=this.time.delayedCall(900,()=>this.startPreview(true));return;}this.busy=true;this.mode='feedback';this.setCapyVisible(view,true);this.tone('correct');this.sparkles(view.c.x,view.c.y-35);this.feedback.setText(`找到了！是${CAPYBARA_STYLES[result.style].name}！`);this.refresh();this.previewTimer=this.time.delayedCall(900,()=>{if(result.result==='complete')this.finishLevel();else{this.session.nextRound();this.drawLevel();this.startPreview();}});}
    showHint(){if(this.mode!=='playing'||this.busy)return;this.session.hint();this.startPreview(true);}
    toggleSlow(){if(!['playing','preview'].includes(this.mode))return;this.slow=!this.slow;this.slowButton.label.setText(this.slow?'慢慢看：開':'慢慢看：關');this.feedback.setText(this.slow?'水豚會多停留一秒，慢慢記。':'一般速度開啟，準備挑戰！');}
    refresh(){this.progressText?.setText(`本關 ${this.session.correct} / ${this.session.level.targets.length}`);this.statText?.setText(`再找 ${this.session.mistakes} 次\n重看 ${this.session.hints} 次`);}
    sparkles(x,y){for(let i=0;i<12;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffda6f:0xffffff).setDepth(70),a=i/12*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*82,y:y+Math.sin(a)*65,alpha:0,angle:150,duration:550,onComplete:()=>s.destroy()});}}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-6]$/.test(e.code))this.choosePool(Number(e.code.slice(-1))-1);else if(e.code==='KeyH'||e.code==='Space')this.showHint();else if(e.code==='KeyS')this.toggleSlow();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('水豚溫泉躲貓貓！','水豚會先從溫泉探頭，記住牠們的位置；\n等熱氣遮住後，依題目找出戴指定裝飾的水豚。\n找錯不扣分，所有水豚會再露臉一次。');o.add(this.text(640,410,'前兩關保留空溫泉，之後才增加角色與裝飾。',19,'#8f5f50'));o.add(this.button(640,500,290,60,'開始看水豚！',()=>{o.destroy();this.overlay=null;this.startPreview();this.sound.context?.resume?.();},0xa65b5e));}
    pauseGame(){if(!['playing','preview','feedback'].includes(this.mode))return;this.previousMode=this.mode;this.mode='paused';this.tweens.pauseAll();if(this.previewTimer)this.previewTimer.paused=true;this.stopTones();const o=this.makeOverlay('水豚泡湯休息一下','先看水豚露臉並記住位置，等牠們躲好後再找指定裝飾。\n按「再看一次」可以重新觀察；找錯不扣分。\n鍵盤可用 1～6，H 重看，S 切換速度。');o.add(this.button(640,415,270,55,'繼續躲貓貓',()=>this.resumeGame(),0xa65b5e));o.add(this.button(640,500,270,51,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c4038'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode=this.previousMode||'playing';this.previewTimer&&(this.previewTimer.paused=false);this.tweens.resumeAll();}
    finishLevel(){this.mode='levelComplete';this.busy=false;this.tone('finish');const last=this.session.levelIndex===HOT_SPRING_LEVELS.length-1,o=this.makeOverlay(last?'水豚溫泉派對完成！':'這區水豚都找到了！',last?`五關全部完成！\n找對 ${this.session.totalCorrect} 次　重新尋找 ${this.session.totalMistakes} 次`:`${this.session.level.name}完成！\n找錯也會重新露臉，每次都能再記一次。`);if(last){o.add(this.button(500,485,230,58,'再玩一次',()=>this.restart(),0xa65b5e));o.add(this.button(780,485,230,58,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c4038'));}else o.add(this.button(640,485,270,58,'下一區溫泉',()=>{o.destroy();this.overlay=null;this.session.advance();this.drawLevel();this.startPreview();},0xa65b5e));}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.previewTimer?.remove(false);this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'VolcanoBonusMap');}
}
