import AnimalSnackGame from './AnimalSnackGame.js';
import {JellySeaBridgeSession,JELLY_BRIDGE_LEVELS,FLOAT_STONES} from '../data/JellySeaBridgeData.js';

export default class JellySeaBridgeGame extends AnimalSnackGame {
    constructor(){super('JellySeaBridgeGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new JellySeaBridgeSession();this.helper=true;this.busy=false;this.views=new Map();this.slots=[];this.levelItems=[];
        this.drawJellySea();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawJellySea(){const g=this.add.graphics();g.fillGradientStyle(0x573044,0x9a4a50,0xf29b5a,0x44273a,1).fillRect(0,0,1280,720);g.fillStyle(0x49343d).fillTriangle(0,360,225,90,450,360).fillTriangle(840,360,1060,75,1280,360);g.fillStyle(0xff7e48).fillTriangle(185,142,225,90,269,142).fillTriangle(1018,130,1060,75,1104,130);g.fillStyle(0xef6352).fillRoundedRect(-30,345,1340,375,90);g.fillStyle(0xff9b62,.78).fillRoundedRect(-20,430,1320,270,100);for(let i=0;i<24;i++)g.fillStyle(i%2?0xffd27b:0xff6d64,.55).fillCircle(20+(i*157)%1240,365+(i*73)%330,9+i%17);}
    drawHud(){this.panel(640,43,1248,66,0xfff0d9,0xe5aa67,19).setDepth(80);this.button(105,43,160,43,'← 備選小島',()=>this.leave(),0x9e493d).setDepth(81);this.text(417,40,'造橋過果凍海',30,'#743329').setDepth(81);this.levelText=this.text(680,43,'第 1 / 5 關',18,'#9c5c43').setDepth(81);this.soundButton=this.button(930,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xf3d5a5,'#743329').setDepth(81);this.button(1093,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xf3d5a5,'#743329').setDepth(81);this.feedback=this.text(640,105,'把浮石從大到小排成安全階梯。',20,'#ffe4b1').setDepth(81);}
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.views.clear();this.slots=[];this.busy=false;const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${JELLY_BRIDGE_LEVELS.length} 關`);
        const islands=this.add.graphics().setDepth(18);islands.fillStyle(0x66544a).fillEllipse(270,430,300,195).fillEllipse(1050,405,300,205);islands.fillStyle(0x8f754f).fillEllipse(270,390,280,105).fillEllipse(1050,365,280,105);islands.fillStyle(0x6c9a5f).fillEllipse(270,369,245,62).fillEllipse(1050,344,245,62);this.levelItems.push(islands);
        this.levelItems.push(this.text(650,143,`${level.name}｜${level.guide}`,19,'#ffe2ad').setDepth(55));this.bear=this.drawBear(285,330).setDepth(52);this.levelItems.push(this.bear);
        const count=level.sizes.length,start=430,end=900;level.sizes.forEach((size,index)=>{const t=count===1?0:index/(count-1),x=start+(end-start)*t,y=420-index*12,info=FLOAT_STONES[size],glow=this.add.ellipse(x,y,info.width+22,info.height+18,0xffe07b,this.helper&&index===0 ? .28 : .08).setStrokeStyle(3,0xffd37a,.65).setDepth(24);this.slots.push({x,y,size,glow});this.levelItems.push(glow);});
        this.trayPanel=this.panel(650,620,735,150,0x533842,0xc47d5d,27).setDepth(35);this.levelItems.push(this.trayPanel,this.text(650,558,'浮石區｜點一下或拖到下一個發光位置',17,'#ffe2ad').setDepth(55));
        const gap=Math.min(145,650/level.sizes.length),base=650-gap*(level.sizes.length-1)/2;this.session.tray.forEach((size,index)=>this.makeStone(size,base+index*gap,625,index));
        this.progressText=this.text(650,694,'',17,'#ffe6b3').setDepth(70);this.hintButton=this.button(1090,575,205,47,'✨ 下一塊提示',()=>this.showHint(),0xc18055,'#fff5dc').setDepth(71);this.helperButton=this.button(1090,635,205,47,'小熊提示：開',()=>this.toggleHelper(),0xf0cf8d,'#6c3028').setDepth(71);this.resetButton=this.button(1090,691,205,42,'↺ 本關重來',()=>this.resetLevel(),0xe8b881,'#6c3028').setDepth(71);this.levelItems.push(this.progressText,this.hintButton,this.helperButton,this.resetButton);this.refresh();
    }
    drawBear(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0xb78355).fillEllipse(0,35,92,105).fillCircle(0,-25,53);g.fillStyle(0x9a6848).fillCircle(-39,-57,18).fillCircle(39,-57,18);g.fillStyle(0xd4aa79).fillEllipse(0,-8,61,43);g.fillStyle(0x3e3432).fillCircle(-17,-31,5).fillCircle(17,-31,5).fillCircle(0,-11,7);g.fillStyle(0x3f6f86).fillRoundedRect(-43,-46,86,27,12);g.fillStyle(0x9fe3ee,.72).fillRoundedRect(-37,-42,31,18,8).fillRoundedRect(6,-42,31,18,8);g.lineStyle(5,0x3f6f86).lineBetween(-58,-33,-42,-33).lineBetween(42,-33,58,-33);g.fillStyle(0xe1644f).fillTriangle(-46,23,-70,42,-43,49);c.add(g);return c;}
    makeStone(size,x,y,index){const info=FLOAT_STONES[size],c=this.add.container(x,y).setDepth(60),ring=this.add.ellipse(0,0,info.width+18,info.height+18,0xffe17c,0),g=this.add.graphics();g.fillStyle(0x564751).fillEllipse(0,8,info.width,info.height);g.fillStyle(info.color).fillEllipse(0,0,info.width,info.height);g.fillStyle(0xffffff,.2).fillEllipse(-info.width*.15,-info.height*.17,info.width*.42,info.height*.2);g.lineStyle(4,0x4f4147,.8).strokeEllipse(0,0,info.width,info.height);const label=this.text(0,3,info.short,16,'#fff2d1'),key=this.text(0,info.height/2+18,String(index+1),14,'#ffe2ad');c.add([ring,g,label,key]).setSize(Math.max(120,info.width+12),105).setInteractive({useHandCursor:true,draggable:true});c.home={x,y};c.sizeId=size;c.ring=ring;c.on('pointerdown',()=>{if(this.mode==='playing'&&!this.busy)c.wasDragged=false;});c.on('dragstart',()=>{if(this.mode!=='playing'||this.busy)return;c.wasDragged=true;c.setDepth(75);});c.on('drag',(_p,dx,dy)=>{if(this.mode==='playing'&&!this.busy)c.setPosition(dx,dy);});c.on('dragend',()=>{if(this.mode!=='playing'||this.busy)return;c.setDepth(60);this.dropStone(c);});c.on('pointerup',()=>{if(this.mode==='playing'&&!this.busy&&!c.wasDragged&&c.active)this.tryPlace(c);});this.input.setDraggable(c);this.views.set(size,c);this.levelItems.push(c);}
    dropStone(view){const slot=this.slots[this.session.index];if(slot&&Phaser.Math.Distance.Between(view.x,view.y,slot.x,slot.y)<125)this.tryPlace(view);else this.returnStone(view,'把浮石拖到下一個發光位置～');}
    tryPlace(view){if(this.mode!=='playing'||this.busy||!view?.active)return;const result=this.session.place(view.sizeId);if(result==='ignored')return;if(result==='retry'){this.feedback.setText(`小熊搖搖頭：下一塊要比它更大，是「${FLOAT_STONES[this.session.expected].short}」！`);this.tone('hint');this.shakeBear();this.flashExpected();this.returnStone(view);return;}const slot=this.slots[this.session.index-1];this.busy=true;view.disableInteractive();view.ring.setVisible(false);view.list[view.list.length-1]?.setVisible(false);this.tweens.add({targets:view,x:slot.x,y:slot.y,scale:1,duration:360,ease:'Back.easeOut',onComplete:()=>{view.setDepth(45);slot.glow.setAlpha(.06);this.sparkles(slot.x,slot.y);this.tone('correct');this.busy=false;this.feedback.setText(`${FLOAT_STONES[view.sizeId].name}放好了！下一塊要再小一點。`);this.refresh();if(result==='complete'){this.busy=true;this.time.delayedCall(550,()=>this.walkBear());}else this.updateSlotGlow();}});}
    returnStone(view,message){if(message)this.feedback.setText(message);this.busy=true;this.tweens.add({targets:view,x:view.home.x,y:view.home.y,scale:1,angle:0,duration:300,ease:'Back.easeOut',onComplete:()=>{if(this.mode==='playing')this.busy=false;}});}
    updateSlotGlow(){this.slots.forEach((slot,index)=>slot.glow.setFillStyle(0xffe07b,this.helper&&index===this.session.index ? .3 : .08));}
    flashExpected(){const view=this.views.get(this.session.expected),slot=this.slots[this.session.index];if(view)this.tweens.add({targets:view,scale:1.14,duration:180,yoyo:true,repeat:3});if(slot)this.tweens.add({targets:slot.glow,scale:1.18,duration:180,yoyo:true,repeat:3});}
    showHint(){if(this.mode!=='playing'||this.busy)return;const size=this.session.hint();if(!size)return;this.feedback.setText(`提示：接下來放「${FLOAT_STONES[size].name}」。`);this.flashExpected();this.tone('hint');this.refresh();}
    toggleHelper(){if(this.mode!=='playing'||this.busy)return;this.helper=!this.helper;this.helperButton.label.setText(this.helper?'小熊提示：開':'小熊提示：關');this.updateSlotGlow();this.feedback.setText(this.helper?'下一個位置會發出金色亮光。':'亮光收起來，自己從大排到小！');}
    resetLevel(){if(this.mode!=='playing'||this.busy)return;this.session.reset();this.drawLevel();this.feedback.setText('浮石回到岸邊，重新從最大的開始。');this.tone('hint');}
    refresh(){this.progressText?.setText(`已鋪 ${this.session.placed.length} / ${this.session.level.sizes.length} 塊　｜　再試 ${this.session.mistakes} 次　提示 ${this.session.hints} 次`);}
    shakeBear(){this.tweens.add({targets:this.bear,x:this.bear.x-9,angle:-5,duration:80,yoyo:true,repeat:3});}
    sparkles(x,y){for(let i=0;i<9;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd666:0xffffff).setDepth(70),a=i/9*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*65,y:y+Math.sin(a)*48,alpha:0,angle:120,duration:460,onComplete:()=>s.destroy()});}}
    walkBear(){this.mode='crossing';this.feedback.setText('橋完成了！防風鏡小熊要跳過果凍海！');this.tone('finish');const path=this.slots.map(slot=>({x:slot.x,y:slot.y-72})).concat([{x:1045,y:285}]);const step=index=>{if(index>=path.length){this.sparkles(this.bear.x,this.bear.y);this.time.delayedCall(450,()=>this.finishLevel());return;}const target=path[index],startY=this.bear.y;this.tweens.add({targets:this.bear,x:target.x,y:target.y,duration:320,ease:'Linear',onUpdate:tween=>{const p=tween.progress;this.bear.y=startY+(target.y-startY)*p-Math.sin(p*Math.PI)*45;},onComplete:()=>{this.bear.setPosition(target.x,target.y);step(index+1);}});};step(0);}
    finishLevel(){const last=this.session.levelIndex===JELLY_BRIDGE_LEVELS.length-1;this.mode='levelComplete';const o=this.makeOverlay(last?'果凍海大小橋全部完成！':'小熊安全到達下一座島！',last?`火山備選五款全部完成！\n共放好 ${this.session.totalPlaced} 塊浮石　提示 ${this.session.hints} 次`:`${this.session.level.name}完成！\n排錯不扣分，願意再比較大小就是成功。`);if(last){o.add(this.button(500,485,230,58,'再造一次',()=>this.restart(),0xa9503b));o.add(this.button(780,485,230,58,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}else o.add(this.button(640,485,270,58,'下一座果凍橋',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('新的浮石來了，先找最大的！');},0xa9503b));}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-5]$/.test(e.code)){const size=this.session.tray[Number(e.code.slice(-1))-1];this.tryPlace(this.views.get(size));}else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyR')this.resetLevel();else if(e.code==='KeyB')this.toggleHelper();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('防風鏡小熊要過果凍海！','把下方浮石依照「從大到小」的順序鋪到海面。\n可以點一下石頭自動放置，也可以直接拖到亮光位置。\n順序錯了不扣分，小熊會告訴你下一塊。');o.add(this.text(640,410,'第一關只有兩塊，之後慢慢增加到五種大小。',19,'#8a5b42'));o.add(this.button(640,500,295,60,'開始造橋！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0xa9503b));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('小熊休息一下','浮石必須從大到小依序鋪好。\n點一下或拖曳都可以；H 顯示下一塊，R 本關重來。\n排錯不扣分，石頭會回到岸邊。');o.add(this.button(640,415,270,55,'繼續造橋',()=>this.resumeGame(),0xa9503b));o.add(this.button(640,500,270,51,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'VolcanoBonusMap');}
}
