import AnimalSnackGame from './AnimalSnackGame.js';
import {JumpClimbSession,JUMP_CLIMB_LEVELS} from '../data/JumpClimbData.js';

const ROUTE_X=[430,680,900,610,850];

export default class JumpClimbGame extends AnimalSnackGame {
    constructor(){super('JumpClimbGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new JumpClimbSession();this.helper=true;this.holding=false;this.charge=0;this.busy=false;this.levelItems=[];this.platforms=[];
        this.drawMountains();this.drawHud();this.drawLevel();this.bindInput();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyDownHandler);this.input.keyboard?.off('keyup',this.keyUpHandler);this.stopTones();});
    }
    drawMountains(){const g=this.add.graphics();g.fillGradientStyle(0x6aaac5,0xa2d2dc,0xead8b6,0x806b78,1).fillRect(0,0,1280,720);g.fillStyle(0x728697,.75).fillTriangle(-80,590,250,95,560,590).fillTriangle(470,590,820,65,1130,590).fillTriangle(875,590,1130,180,1380,590);g.fillStyle(0xf5f0dc,.8).fillTriangle(184,194,250,95,317,194).fillTriangle(750,170,820,65,892,170).fillTriangle(1080,260,1130,180,1182,260);g.fillStyle(0x668866).fillRect(0,565,1280,155);for(let i=0;i<28;i++)g.fillStyle(i%2?0xffffff:0xffe6a7,.4).fillCircle(25+(i*149)%1230,90+(i*83)%580,3+i%6);}
    drawHud(){this.panel(640,43,1248,66,0xfffbec,0xd8cfaa,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x557f76).setDepth(81);this.text(392,40,'跳躍登頂・幼童版',30,'#355f5c').setDepth(81);this.levelText=this.text(670,43,'第 1 / 5 關',18,'#6d8581').setDepth(81);this.soundButton=this.button(930,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xe8ead2,'#355f5c').setDepth(81);this.button(1092,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xe8ead2,'#355f5c').setDepth(81);
        this.panel(150,350,250,480,0xfffbec,0xd8cfaa,23).setDepth(60);this.text(150,125,'登頂小任務',22,'#355f5c').setDepth(61);this.taskText=this.text(150,182,'',18,'#627c78').setWordWrapWidth(210,true).setDepth(61);this.progressText=this.text(150,273,'',28,'#355f5c').setDepth(61);this.statText=this.text(150,333,'',16,'#6d8581').setDepth(61);this.hintButton=this.button(150,422,195,48,'✨ 力量提示',()=>this.showHint(),0xe3bc61,'#594c2d').setDepth(62);this.helperButton=this.button(150,482,195,48,'綠色範圍：開',()=>this.toggleHelper(),0xe8ead2,'#355f5c').setDepth(62);this.resetButton=this.button(150,542,195,48,'↺ 本關重來',()=>this.resetLevel(),0xe8ead2,'#355f5c').setDepth(62);this.feedback=this.text(695,104,'按住蓄力，進入綠色範圍後放開！',20,'#3f6662').setDepth(81);this.text(730,692,'按住畫面蓄力・放開跳躍｜力量太少或太多，都由彈力葉安全接回',16,'#4e716d').setDepth(70);
        this.chargePanel=this.panel(1090,370,220,335,0xfffbec,0xd8cfaa,24).setDepth(60);this.text(1090,225,'跳躍力量',22,'#355f5c').setDepth(61);this.chargeTrack=this.add.rectangle(1090,380,42,220,0xd8ded0).setDepth(62);this.safeBand=this.add.rectangle(1090,420,52,80,0x7acb7b,.45).setDepth(63);this.chargeFill=this.add.rectangle(1090,490,30,1,0xe2a94d).setOrigin(.5,1).setDepth(64);this.chargeLabel=this.text(1090,515,'按住畫面',17,'#627c78').setDepth(64);this.text(1090,565,'也可按住空白鍵',15,'#6d8581').setDepth(64);}
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.platforms=[];this.holding=false;this.charge=0;this.busy=false;const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${JUMP_CLIMB_LEVELS.length} 關`);this.taskText.setText(`${level.name}\n${level.guide}`);
        const count=level.powers.length+1;for(let i=0;i<count;i++){const x=ROUTE_X[i],y=565-i*(335/(count-1)),width=205-i*9,p=this.drawPlatform(x,y,width,i).setDepth(28);this.platforms.push(p);this.levelItems.push(p);}this.goal=this.drawGoal(this.platforms[count-1].x,this.platforms[count-1].y-66).setDepth(38);this.levelItems.push(this.goal);
        this.player=this.drawClimber(this.platforms[0].x,this.platforms[0].y-61).setDepth(48);this.rescueLeaf=this.drawLeaf(650,625).setDepth(45).setVisible(false);this.levelItems.push(this.player,this.rescueLeaf);this.refresh();this.updateMeter();
    }
    drawPlatform(x,y,width,index){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x5f5961).fillRoundedRect(-width/2,-18,width,52,22);g.fillStyle(index%2?0x789463:0x6f8b5c).fillRoundedRect(-width/2+6,-24,width-12,27,13);g.fillStyle(0xffffff,.18).fillRoundedRect(-width/2+20,-18,width*.42,8,4);const n=this.text(0,17,String(index+1),14,'#fff4d0');c.add([g,n]);return c;}
    drawGoal(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.lineStyle(6,0x76523f).lineBetween(0,30,0,-45);g.fillStyle(0xffd358).fillTriangle(0,-44,62,-24,0,-5);g.fillStyle(0xffffff,.8).fillCircle(27,-25,7);const star=this.add.star(0,-67,5,10,22,0xffe074);c.add([g,star]);this.tweens.add({targets:star,scale:1.25,angle:25,duration:650,yoyo:true,repeat:-1});return c;}
    drawClimber(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x5a4138).fillCircle(0,-32,24);g.fillStyle(0xf0c39c).fillCircle(0,-23,21);g.fillStyle(0x3d3430).fillCircle(-7,-26,3).fillCircle(7,-26,3);g.fillStyle(0xe9b84e).fillRoundedRect(-25,-50,50,13,6);g.fillStyle(0x5d9b83).fillRoundedRect(-21,0,42,47,14);g.fillStyle(0xd06a55).fillRoundedRect(15,5,24,38,9);g.fillStyle(0x6b4c3d).fillRoundedRect(-25,39,14,29,7).fillRoundedRect(11,39,14,29,7);g.fillStyle(0xf0c39c).fillCircle(-29,14,8).fillCircle(29,14,8);c.add(g);return c;}
    drawLeaf(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x70b86d).fillEllipse(0,0,190,70);g.lineStyle(6,0x418654).lineBetween(-75,0,75,0);g.fillStyle(0x9bd486,.5).fillEllipse(-26,-12,65,18);const label=this.text(0,55,'彈力葉會接住你',16,'#efffdc');c.add([g,label]);return c;}
    bindInput(){this.input.on('pointerdown',pointer=>{if(this.mode==='playing'&&!this.busy&&pointer.x>285&&pointer.y>90)this.startCharge();});this.input.on('pointerup',()=>{if(this.holding)this.releaseJump();});this.keyDownHandler=e=>{if(e.repeat)return;if(['Space','ArrowUp','KeyW'].includes(e.code))this.startCharge();else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyG')this.toggleHelper();else if(e.code==='KeyR')this.resetLevel();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.keyUpHandler=e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)&&this.holding)this.releaseJump();};this.input.keyboard?.on('keydown',this.keyDownHandler);this.input.keyboard?.on('keyup',this.keyUpHandler);}
    startCharge(){if(this.mode!=='playing'||this.busy||this.holding)return;this.holding=true;this.charge=Math.max(.05,this.charge);this.chargeLabel.setText('蓄力中…');this.feedback.setText('力量正在上升，看到綠色就放開！');this.tone('send');}
    update(_time,delta){if(this.mode!=='playing'||!this.holding)return;this.charge=Math.min(1,this.charge+delta/1700);this.updateMeter();if(this.charge>=1){this.chargeLabel.setText('力量滿滿！');}}
    releaseJump(){if(!this.holding||this.busy)return;this.holding=false;const power=this.charge,result=this.session.jump(power);this.charge=0;this.updateMeter();if(result.result==='ignored')return;if(result.result==='retry_low'||result.result==='retry_high'){this.failedJump(result);return;}this.successJump(result);}
    successJump(result){this.busy=true;const from=this.platforms[this.session.step-1],to=this.platforms[this.session.step],startX=from.x,startY=from.y-61;this.feedback.setText(result.result==='complete'?'最後一跳成功，登上山頂！':'力量剛剛好，穩穩落在寬平台！');this.tone('correct');this.tweens.addCounter({from:0,to:1,duration:650,ease:'Sine.easeInOut',onUpdate:t=>{const p=t.getValue();this.player.setPosition(Phaser.Math.Linear(startX,to.x,p),Phaser.Math.Linear(startY,to.y-61,p)-Math.sin(p*Math.PI)*105).setAngle(Math.sin(p*Math.PI)*8);},onComplete:()=>{this.player.setPosition(to.x,to.y-61).setAngle(0);this.sparkles(to.x,to.y-65);this.busy=false;this.refresh();this.updateMeter();if(result.result==='complete'){this.busy=true;this.time.delayedCall(600,()=>this.finishLevel());}}});}
    failedJump(result){this.busy=true;const current=this.platforms[this.session.step],tooHigh=result.result==='retry_high',startX=current.x,startY=current.y-61,targetX=tooHigh?Math.min(1010,current.x+260):Math.max(360,current.x+110);this.feedback.setText(tooHigh?'力量太多了一點，彈力葉會接你回來～':'力量還差一點，彈力葉會把你送回平台～');this.tone('hint');this.rescueLeaf.setVisible(true).setPosition(targetX,610).setScale(.2);this.tweens.add({targets:this.rescueLeaf,scale:1,duration:260,ease:'Back.easeOut'});this.tweens.addCounter({from:0,to:1,duration:520,onUpdate:t=>{const p=t.getValue();this.player.setPosition(Phaser.Math.Linear(startX,targetX,p),startY+Math.sin(p*Math.PI)*-80+p*115).setAngle(p*35);},onComplete:()=>{this.tweens.add({targets:this.rescueLeaf,scaleY:.55,duration:130,yoyo:true});this.tweens.addCounter({from:0,to:1,duration:520,onUpdate:t=>{const p=t.getValue();this.player.setPosition(Phaser.Math.Linear(targetX,startX,p),Phaser.Math.Linear(610,startY,p)-Math.sin(p*Math.PI)*90).setAngle((1-p)*-20);},onComplete:()=>{this.player.setPosition(startX,startY).setAngle(0);this.rescueLeaf.setVisible(false);this.busy=false;this.refresh();this.updateMeter();}});}});}
    updateMeter(){const range=this.session.safeRange,bottom=490,height=220;if(range){const bandH=(range.max-range.min)*height,centerY=bottom-range.max*height+bandH/2;this.safeBand.setPosition(1090,centerY).setDisplaySize(52,bandH).setVisible(this.helper);}else this.safeBand.setVisible(false);this.chargeFill.setPosition(1090,bottom).setDisplaySize(30,Math.max(1,this.charge*height));if(!this.holding)this.chargeLabel.setText('按住畫面');}
    showHint(){if(this.mode!=='playing'||this.busy)return;const range=this.session.hint();if(!range)return;this.helper=true;this.helperButton.label.setText('綠色範圍：開');this.updateMeter();this.feedback.setText(`提示：蓄力到中間約 ${Math.round(range.center*100)}% 時放開。`);this.tone('hint');this.tweens.add({targets:this.safeBand,scaleX:1.25,alpha:.8,duration:180,yoyo:true,repeat:4});this.refresh();}
    toggleHelper(){if(this.mode!=='playing'||this.busy)return;this.helper=!this.helper;this.helperButton.label.setText(this.helper?'綠色範圍：開':'綠色範圍：關');this.updateMeter();this.feedback.setText(this.helper?'綠色區會顯示安全蓄力範圍。':'綠色區收起來，自己抓放開時機！');}
    resetLevel(){if(this.mode!=='playing'||this.busy)return;this.session.reset();this.drawLevel();this.feedback.setText('回到山腳，重新練習蓄力。');this.tone('hint');}
    refresh(){this.progressText.setText(`跳上 ${this.session.landed} / ${this.session.level.powers.length} 階`);this.statText.setText(`嘗試 ${this.session.attempts} 次\n彈力葉接住 ${this.session.rescues} 次\n提示 ${this.session.hints} 次`);}
    sparkles(x,y){for(let i=0;i<10;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd45c:0xffffff).setDepth(72),a=i/10*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*78,y:y+Math.sin(a)*58,alpha:0,angle:140,duration:500,onComplete:()=>s.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===JUMP_CLIMB_LEVELS.length-1;this.mode='levelComplete';this.busy=false;this.tone('finish');const o=this.makeOverlay(last?'星光最高峰登頂成功！':'這座山峰登頂成功！',last?`五條登頂路線全部完成！\n成功跳上 ${this.session.totalLanded} 階　彈力葉救援 ${this.session.rescues} 次`:`${this.session.level.name}完成！\n力量太少或太多都能安全回來，再試就會進步。`);if(last){o.add(this.button(500,485,230,58,'再爬一次',()=>this.restart(),0x557f76));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe3bc61,'#594c2d'));}else o.add(this.button(640,485,270,58,'下一座山峰',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('新的寬平台，按住蓄力再放開！');},0x557f76));}
    showIntro(){const o=this.makeOverlay('小小登山隊準備出發！','按住畫面或空白鍵，力量會慢慢增加；\n進入綠色安全範圍後放開，就會跳上寬平台。\n力量太少或太多都不失敗，彈力葉會安全接住。');o.add(this.text(640,410,'幼童版沒有移動平台、風力或步數限制。',19,'#687f79'));o.add(this.button(640,500,290,60,'開始蓄力跳！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0x557f76));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.holding=false;this.charge=0;this.updateMeter();this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('在山腰休息一下','按住畫面、空白鍵、方向鍵上或 W 蓄力，放開即可跳躍。\n綠色區是安全力量；太少或太多由彈力葉接回。\nH 顯示力量提示，G 切換綠色範圍，R 重來。');o.add(this.button(640,415,270,55,'繼續登頂',()=>this.resumeGame(),0x557f76));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xe8ead2,'#355f5c'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
