import AnimalSnackGame from './AnimalSnackGame.js';
import {LavaBubblePopSession,LAVA_BUBBLE_COLORS,LAVA_BUBBLE_CONFIG} from '../data/LavaBubblePopData.js';

export default class LavaBubblePopGame extends AnimalSnackGame {
    constructor(){super('LavaBubblePopGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new LavaBubblePopSession();this.bubbles=new Set();this.spawnClock=0;this.babyMode=true;this.drawLavaPlayground();this.drawHud();this.bindBubbleInput();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawLavaPlayground(){
        const g=this.add.graphics();g.fillGradientStyle(0x4a2850,0x7b3845,0xe9763c,0x47283f,1).fillRect(0,0,1280,720);g.fillStyle(0x352637).fillTriangle(0,420,255,115,505,420).fillTriangle(760,420,1035,75,1280,420);g.fillStyle(0xf06a36).fillTriangle(198,182,255,115,315,182).fillTriangle(970,155,1035,75,1100,155);g.fillStyle(0x4a2d3d).fillRect(0,430,1280,290);
        this.lava=g;g.fillStyle(0xed5b36).fillRoundedRect(-50,530,1380,230,70);g.fillStyle(0xff9a45,.92).fillRoundedRect(-20,585,1320,115,55);g.fillStyle(0xffcf69,.55).fillRoundedRect(40,620,1200,45,22);for(let i=0;i<28;i++)g.fillStyle(i%2?0xffd56f:0xff7a45,.48).fillCircle(25+(i*173)%1230,95+(i*79)%520,3+i%5);
        this.tapZone=this.add.rectangle(640,365,1280,590,0xffffff,.001).setInteractive({useHandCursor:true}).setDepth(5);this.tapZone.on('pointerdown',pointer=>{if(this.mode!=='playing')return;const spec=this.session.emptyTap();this.spawnBubble(spec,pointer.x,Math.max(180,Math.min(535,pointer.y)),true);this.feedback.setText('噗嚕！這裡也冒出一顆泡泡。');this.tone('send');this.refreshHud();});
    }
    drawHud(){
        this.panel(640,43,1248,66,0xfff0d9,0xf0b15e,19).setDepth(60);this.button(105,43,160,43,'← 備選小島',()=>this.leave(),0xa44b39).setDepth(61);this.text(447,40,'啵啵彩色岩漿泡泡',30,'#743329').setDepth(61);this.text(699,44,'點一下・星星啵啵',17,'#a25c42').setDepth(61);
        this.soundButton=this.button(956,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xf4d6a5,'#743329').setDepth(61);this.button(1106,43,150,43,'暫停 / 說明',()=>this.pauseGame(),0xf4d6a5,'#743329').setDepth(61);
        this.panel(150,302,250,370,0xfff0dc,0xeab068,25).setDepth(45);this.text(150,145,'今天的啵啵',23,'#743329').setDepth(46);this.countText=this.text(150,205,'0 / 24',38,'#743329').setDepth(46);this.progressTrack=this.add.rectangle(55,251,190,13,0xe4c9ad).setOrigin(0,.5).setDepth(46);this.progressFill=this.add.rectangle(55,251,1,13,0xed7c54).setOrigin(0,.5).setDepth(47);this.stageText=this.text(150,294,'暖暖大泡泡',19,'#9a5d43').setDepth(46);this.rainbowText=this.text(150,337,'彩虹泡泡 0 顆',17,'#9a5d43').setDepth(46);this.babyButton=this.button(150,403,198,51,'👶 寶寶模式：開',()=>this.toggleBaby(),0x79b897,'#214a37').setDepth(47);this.text(150,465,'漏掉也沒關係\n泡泡會再回來',16,'#a27658').setDepth(46);
        this.feedback=this.text(735,112,'看看果凍岩漿冒出什麼！',21,'#fff0c6').setDepth(61);this.text(730,685,'直接點泡泡｜點空白處也會冒泡泡｜空白鍵可啵掉最近一顆',16,'#ffe0a2').setDepth(61);
    }
    bindBubbleInput(){this.keyHandler=e=>{if(e.repeat)return;if(e.code==='Space')this.popNearest();else if(e.code==='KeyB')this.toggleBaby();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('彩色岩漿泡泡冒出來了！','直接點大泡泡，就會「啵」一聲變成星星和彩帶。\n點到空白處也沒關係，那裡會再冒出一顆新泡泡。\n沒有倒數、沒有失敗，漏掉的泡泡還會從下面回來。');o.add(this.text(640,407,'每啵掉 6 顆，會出現一顆彩虹大泡泡！',20,'#8a5b42'));o.add(this.button(640,505,285,60,'開始啵泡泡！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();for(let i=0;i<4;i++)this.time.delayedCall(i*220,()=>this.spawnBubble());},0xb9573e));}
    spawnBubble(spec=null,x=null,y=null,fromTap=false){if(!['playing','intro'].includes(this.mode)||this.session.complete)return;spec=spec||this.session.spawn();const color=LAVA_BUBBLE_COLORS[spec.colorIndex],size=spec.rainbow?(this.babyMode?112:94):(this.babyMode?Phaser.Math.Between(72,108):Phaser.Math.Between(54,88));x=x??Phaser.Math.Between(285,1180);y=y??Phaser.Math.Between(570,660);const c=this.add.container(x,y).setDepth(20),glow=this.add.circle(0,0,size*.62,spec.rainbow?0xffe581:color.shine,.18),body=this.add.circle(0,0,size/2,color.fill,.9).setStrokeStyle(4,spec.rainbow?0xffef9f:color.shine,.95),shine=this.add.ellipse(-size*.16,-size*.18,size*.22,size*.14,0xffffff,.72).setAngle(-25);c.add([glow,body,shine]);if(spec.rainbow){const ring=this.add.circle(0,0,size*.38,0xffffff,.02).setStrokeStyle(7,0xffe46f,.9);c.add(ring);this.tweens.add({targets:ring,angle:360,duration:1200,repeat:-1});}c.setSize(size+24,size+24).setInteractive(new Phaser.Geom.Circle(0,0,size*.66),Phaser.Geom.Circle.Contains);const bubble={view:c,glow,spec,size,speed:(this.babyMode?25:42)+Phaser.Math.Between(0,16),wave:Math.random()*6.28,baseX:x,popped:false};c.on('pointerdown',(_p,_x,_y,event)=>{event?.stopPropagation?.();this.popBubble(bubble);});this.bubbles.add(bubble);this.tweens.add({targets:glow,scale:1.18,alpha:.08,duration:700+size*3,yoyo:true,repeat:-1});if(fromTap)c.setScale(.15),this.tweens.add({targets:c,scale:1,duration:280,ease:'Back.easeOut'});}
    popBubble(bubble){if(this.mode!=='playing'||bubble.popped||!this.bubbles.has(bubble))return;bubble.popped=true;this.bubbles.delete(bubble);const result=this.session.pop(bubble.spec.rainbow),x=bubble.view.x,y=bubble.view.y,size=bubble.size;bubble.view.disableInteractive();this.tweens.killTweensOf(bubble.view);this.tweens.add({targets:bubble.view,scale:1.32,alpha:0,duration:150,onComplete:()=>bubble.view.destroy()});this.popConfetti(x,y,size,bubble.spec.rainbow);this.tone(bubble.spec.rainbow?'finish':'correct');this.refreshHud();if(result==='complete'){this.mode='celebrating';this.feedback.setText('二十四顆全部啵完，火山彩帶派對！');this.grandParty();this.time.delayedCall(1400,()=>this.finish());}else if(bubble.spec.rainbow)this.feedback.setText('彩虹大泡泡！好多星星跑出來了！');else this.feedback.setText(['啵！變成星星了！','啵啵！好漂亮！','抓到了，下一顆在哪裡？'][this.session.popped%3]);}
    popConfetti(x,y,size,rainbow){const colors=[0xffd65d,0xff7b83,0x7bd8ed,0x9ce17f,0xc495e8];for(let i=0;i<(rainbow?22:10);i++){const item=i%3===0?this.add.star(x,y,5,3,8,colors[i%colors.length]):this.add.rectangle(x,y,8,14,colors[i%colors.length]).setAngle(i*37);item.setDepth(45);const a=i/(rainbow?22:10)*Math.PI*2,dist=size*.7+(i%4)*16;this.tweens.add({targets:item,x:x+Math.cos(a)*dist,y:y+Math.sin(a)*dist+25,angle:180+i*30,alpha:0,duration:520+(i%5)*45,onComplete:()=>item.destroy()});}}
    update(_time,delta){if(this.mode!=='playing')return;const dt=Math.min(delta/1000,.05);this.spawnClock+=dt;const interval=this.babyMode?1.18:.78;if(this.spawnClock>=interval&&this.bubbles.size<(this.babyMode?7:10)){this.spawnClock=0;this.spawnBubble();}for(const bubble of this.bubbles){bubble.wave+=dt*1.8;bubble.view.y-=bubble.speed*dt;bubble.view.x=bubble.baseX+Math.sin(bubble.wave)*24;if(bubble.view.y<-bubble.size){this.session.escape();bubble.view.y=650;bubble.baseX=Phaser.Math.Between(280,1180);bubble.view.setAlpha(.35);this.tweens.add({targets:bubble.view,alpha:1,duration:300});}}}
    popNearest(){if(this.mode!=='playing'||!this.bubbles.size){if(this.mode==='playing')this.spawnBubble();return;}const bubble=[...this.bubbles].sort((a,b)=>a.view.y-b.view.y)[0];this.popBubble(bubble);}
    toggleBaby(){this.babyMode=!this.babyMode;this.babyButton.label.setText(this.babyMode?'👶 寶寶模式：開':'🎈 活潑模式：開');this.bubbles.forEach(b=>{b.speed=this.babyMode?Math.min(b.speed,36):Math.max(b.speed,45);});this.feedback.setText(this.babyMode?'泡泡變大、變慢了。':'泡泡會多一點、活潑一點。');}
    refreshHud(){this.countText.setText(`${this.session.popped} / ${LAVA_BUBBLE_CONFIG.goal}`);this.progressFill.width=Math.max(1,190*this.session.popped/LAVA_BUBBLE_CONFIG.goal);this.stageText.setText(['暖暖大泡泡','星星彩帶泡泡','火山啵啵派對'][this.session.stage]);this.rainbowText.setText(`彩虹泡泡 ${this.session.rainbows} 顆`);}
    grandParty(){for(let i=0;i<42;i++)this.time.delayedCall((i%7)*90,()=>{const x=240+(i*97)%990,y=170+(i*53)%420;this.popConfetti(x,y,70,i%6===0);});}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('泡泡在岩漿裡等你','直接點泡泡就會啵開；點空白處也會冒出新泡泡。\n寶寶模式會讓泡泡更大、更慢。\n漏掉不扣分，泡泡會從下方重新回來。');o.add(this.button(640,415,270,55,'繼續啵泡泡',()=>this.resumeGame(),0xb9573e));o.add(this.button(640,500,270,51,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    finish(){this.mode='finished';this.tone('finish');const o=this.makeOverlay('火山泡泡派對完成！',`啵掉 ${this.session.popped} 顆泡泡\n找到 ${this.session.rainbows} 顆彩虹泡泡\n漏掉的 ${this.session.escaped} 顆都有安全回來`);o.add(this.text(640,392,'小手點得又快又準，所有泡泡都變成星星了！',18,'#8a5b42'));o.add(this.button(500,485,230,58,'再啵一次',()=>this.restart(),0xb9573e));o.add(this.button(780,485,230,58,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'VolcanoBonusMap');}
}
