import AnimalSnackGame from './AnimalSnackGame.js';
import {FIREFLY_FRIENDS,STARLIGHT_FIREFLY_LEVELS,StarlightFireflySession} from '../data/StarlightFireflyData.js';

const SPOTS=[{x:475,y:410},{x:680,y:515},{x:880,y:410},{x:680,y:305}];

export default class StarlightFireflyGame extends AnimalSnackGame {
    constructor(){super('StarlightFireflyGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new StarlightFireflySession();this.slow=true;this.busy=false;this.views=[];this.levelItems=[];
        this.drawNight();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawNight(){const g=this.add.graphics();g.fillGradientStyle(0x172c59,0x2d4774,0x17294e,0x101b3b,1).fillRect(0,0,1280,720);g.fillStyle(0xfff3b3,.9).fillCircle(1100,130,72);g.fillStyle(0x2d4774,1).fillCircle(1074,111,68);for(let i=0;i<48;i++)g.fillStyle(i%3?0xffffff:0xffe68a,.35+(i%4)*.12).fillCircle(300+(i*193)%940,92+(i*79)%400,2+i%3);g.fillStyle(0x183f57).fillEllipse(740,600,920,250);g.fillStyle(0x2d6f79,.85).fillEllipse(740,588,820,190);g.fillStyle(0x80c2bb,.18).fillEllipse(740,565,650,95);g.fillStyle(0x244f42).fillEllipse(170,675,480,230).fillEllipse(1150,680,430,220);for(let i=0;i<18;i++){const x=300+(i*137)%860,y=575+(i%4)*25;g.fillStyle(i%2?0x4a8d68:0x65a873,.8).fillEllipse(x,y,70,22);}}
    drawHud(){this.panel(640,43,1248,66,0xf8f3df,0xe0cf9d,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x4c6f73).setDepth(81);this.text(407,40,'星光湖畔・螢火蟲追蹤',29,'#355466').setDepth(81);this.levelText=this.text(730,43,'第 1 / 5 關',18,'#6f7881').setDepth(81);this.soundButton=this.button(947,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xe3e4d7,'#355466').setDepth(81);this.button(1100,43,158,43,'暫停 / 說明',()=>this.pauseGame(),0xe3e4d7,'#355466').setDepth(81);
        this.panel(150,360,250,500,0xf8f3df,0xe0cf9d,23).setDepth(60);this.text(150,126,'星光小任務',22,'#355466').setDepth(61);this.taskText=this.text(150,181,'',18,'#667b86').setWordWrapWidth(210,true).setDepth(61);this.modeText=this.text(150,275,'',25,'#4b6573').setDepth(61);this.progressText=this.text(150,325,'',25,'#355466').setDepth(61);this.statText=this.text(150,371,'',16,'#6f7881').setDepth(61);this.replayButton=this.button(150,444,194,48,'▶ 再看一次',()=>this.replay(),0xe4b959,'#58491f').setDepth(62);this.hintButton=this.button(150,503,194,48,'✨ 下一隻提示',()=>this.hint(),0x7eb9a4,'#173f3d').setDepth(62);this.slowButton=this.button(150,562,194,48,'慢速閃光：開',()=>this.toggleSlow(),0xe3e4d7,'#355466').setDepth(62);this.feedback=this.text(740,105,'先看星光順序，再輪到你。',20,'#eaf6ff').setDepth(81);this.text(760,694,'點螢火蟲照順序回答｜點錯不扣分，會重新慢速示範',16,'#eaf6ff').setDepth(70);
    }
    drawLevel(){this.levelItems.forEach(item=>item.destroy());this.levelItems=[];this.views=[];this.busy=false;const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${STARLIGHT_FIREFLY_LEVELS.length} 關`);this.taskText.setText(`${level.name}\n${level.guide}`);this.modeText.setText(level.mode==='reverse'?'↩ 倒著點回去':'→ 照順序點回去');
        FIREFLY_FRIENDS.forEach((friend,index)=>{const view=this.drawFirefly(friend,SPOTS[index],index);this.views.push(view);this.levelItems.push(view.container);});this.refresh();this.time.delayedCall(350,()=>{if(this.mode==='playing')this.playSequence();});
    }
    drawFirefly(friend,spot,index){const c=this.add.container(spot.x,spot.y).setDepth(35),halo=this.add.circle(0,0,64,friend.color,.12),pad=this.add.ellipse(0,53,152,54,0x397a61,.95).setStrokeStyle(3,0x70ab7d),wingL=this.add.ellipse(-31,-8,50,29,0xe9ffff,.65).setAngle(-28),wingR=this.add.ellipse(31,-8,50,29,0xe9ffff,.65).setAngle(28),body=this.add.ellipse(0,0,38,62,0x403a32),glow=this.add.circle(0,16,18,friend.color,.95).setStrokeStyle(3,0xffffff,.75),face=this.add.circle(0,-21,22,0x53493e),eyes=this.add.graphics();eyes.fillStyle(0xffffff).fillCircle(-7,-24,4).fillCircle(7,-24,4).fillStyle(0x24303a).fillCircle(-7,-24,2).fillCircle(7,-24,2);const icon=this.text(0,16,friend.icon,16,'#ffffff'),label=this.text(0,93,`${index+1}・${friend.name}`,17,'#f5f0d5'),hit=this.add.circle(0,7,76,0xffffff,.001).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.choose(friend.id));c.add([pad,halo,wingL,wingR,body,glow,face,eyes,icon,label,hit]);this.tweens.add({targets:[wingL,wingR],scaleX:.72,duration:260+index*30,yoyo:true,repeat:-1});return{container:c,halo,glow,wingL,wingR,friend};}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1234]$/.test(e.code))this.choose(FIREFLY_FRIENDS[Number(e.code.slice(-1))-1].id);else if(e.code==='Space')this.replay();else if(e.code==='KeyH')this.hint();else if(e.code==='KeyS')this.toggleSlow();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    async playSequence(){if(!this.session.level||this.mode==='paused'||this.mode==='levelComplete')return;this.busy=true;this.mode='showing';this.feedback.setText('小眼睛看這裡：螢火蟲要開始閃囉！');this.setDim(true);const gap=this.slow?720:480;for(const id of this.session.level.sequence){if(this.mode!=='showing')return;await this.flash(id,gap);}if(this.mode!=='showing')return;this.setDim(false);this.session.step=0;this.busy=false;this.mode='playing';this.feedback.setText(this.session.level.mode==='reverse'?'輪到你：從最後一隻倒著點！':'輪到你：照剛才的順序點！');this.refresh();}
    flash(id,duration=600){return new Promise(resolve=>{const v=this.views.find(item=>item.friend.id===id);if(!v){resolve();return;}this.tone('hint');this.tweens.add({targets:[v.halo,v.glow],scale:1.8,alpha:1,duration:duration*.3,yoyo:true,hold:duration*.25,onComplete:resolve});this.tweens.add({targets:v.container,y:v.container.y-22,duration:duration*.3,yoyo:true,hold:duration*.25});});}
    setDim(dim){this.views.forEach(v=>v.container.setAlpha(dim?.58:1));}
    choose(id){if(this.mode!=='playing'||this.busy)return;const result=this.session.choose(id),view=this.views.find(v=>v.friend.id===id);if(result.result==='ignored')return;if(result.result==='retry'){this.feedback.setText('順序不一樣也沒關係，再看一次就會記住！');this.tone('hint');this.tweens.add({targets:view.container,x:view.container.x+10,duration:70,yoyo:true,repeat:3,onComplete:()=>this.time.delayedCall(380,()=>this.playSequence())});this.busy=true;this.refresh();return;}this.feedback.setText(result.result==='complete'?'整段星光順序都答對了！':'答對了，找下一隻螢火蟲！');this.tone('correct');this.sparkles(view.container.x,view.container.y);this.tweens.add({targets:[view.halo,view.glow],scale:1.55,alpha:1,duration:160,yoyo:true});this.refresh();if(result.result==='complete'){this.busy=true;this.time.delayedCall(650,()=>this.finishLevel());}}
    replay(){if(this.mode!=='playing'||this.busy||!this.session.replay())return;this.refresh();this.playSequence();}
    hint(){if(this.mode!=='playing'||this.busy)return;const id=this.session.hint();if(!id)return;const view=this.views.find(v=>v.friend.id===id);this.feedback.setText(`下一隻是${view.friend.name}，看看牠在發光！`);this.tone('hint');this.tweens.add({targets:[view.halo,view.glow],scale:1.8,alpha:1,duration:220,yoyo:true,repeat:2});this.refresh();}
    toggleSlow(){if(!['playing','intro'].includes(this.mode)||this.busy)return;this.slow=!this.slow;this.slowButton.label.setText(this.slow?'慢速閃光：開':'慢速閃光：關');this.feedback.setText(this.slow?'會用慢速度示範星光。':'星光會用一般速度示範。');}
    refresh(){const len=this.session.answer.length;this.progressText.setText(`答對 ${this.session.step} / ${len} 閃`);this.statText.setText(`重新觀看 ${this.session.replays} 次\n溫暖提醒 ${this.session.mistakes} 次\n提示 ${this.session.hints} 次`);}
    sparkles(x,y){for(let i=0;i<10;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffe36e:0xb8f3ff).setDepth(72),a=i/10*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*82,y:y+Math.sin(a)*65,alpha:0,angle:130,duration:520,onComplete:()=>s.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===STARLIGHT_FIREFLY_LEVELS.length-1;this.mode='levelComplete';this.busy=false;this.tone('finish');const o=this.makeOverlay(last?'星光湖大合奏完成！':'這段星光記住了！',last?`五段螢火蟲旋律全部完成！\n共答對 ${this.session.totalCorrect} 次　溫暖提醒 ${this.session.mistakes} 次`:`${this.session.level.name}完成！\n看順序、記位置，再慢慢點回去。`);if(last){o.add(this.button(500,485,230,58,'再玩一次',()=>this.restart(),0x4c6f73));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe4b959,'#58491f'));}else o.add(this.button(640,485,270,58,'下一段星光',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();},0x4c6f73));}
    showIntro(){const o=this.makeOverlay('星光湖的朋友來了！','先看四隻螢火蟲依序發亮，再照提示點回去。\n有些關卡要照順序，有些要從最後一隻倒著點。\n點錯不扣分，螢火蟲會再慢慢示範一次。');o.add(this.text(640,410,'沒有倒數、生命或正式獎勵，安心觀察就好。',19,'#687f79'));o.add(this.button(640,500,290,60,'開始看星光！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();this.playSequence();},0x4c6f73));}
    pauseGame(){if(!['playing','showing'].includes(this.mode))return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('讓眼睛休息一下','先看閃光順序，再點四隻螢火蟲。\n第 3、5 關要倒著點；點錯會自動重播。\n數字鍵 1～4 選擇，空白鍵重播，H 提示，S 切換速度。');o.add(this.button(640,415,270,55,'繼續看星光',()=>this.resumeGame(),0x4c6f73));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xe3e4d7,'#355466'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.tweens.resumeAll();this.mode='playing';this.time.delayedCall(120,()=>this.playSequence());}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
