import AnimalSnackGame from './AnimalSnackGame.js';
import {VolcanoGemCartSession,GEM_CART_LEVELS,GEM_COLORS} from '../data/VolcanoGemCartData.js';

const BIN_IDS=['red','yellow','blue'];

export default class VolcanoGemCartGame extends AnimalSnackGame {
    constructor(){super('VolcanoGemCartGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new VolcanoGemCartSession();this.helper=true;this.dragging=false;this.selected=false;this.busy=false;this.binViews=new Map();this.levelItems=[];
        this.drawVolcano();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawVolcano(){const g=this.add.graphics();g.fillGradientStyle(0x543049,0x8b4650,0xf29758,0x44283d,1).fillRect(0,0,1280,720);g.fillStyle(0x54343e).fillTriangle(60,470,325,115,590,470).fillTriangle(805,470,1050,145,1270,470);g.fillStyle(0xff8a48).fillTriangle(275,182,325,115,380,182).fillTriangle(1008,202,1050,145,1092,202);g.fillStyle(0xe45b40).fillRect(0,635,1280,85);g.fillStyle(0xff9a4d,.8).fillRect(0,675,1280,45);for(let i=0;i<30;i++)g.fillStyle(i%2?0xffd772:0xff8a66,.5).fillCircle(25+(i*139)%1235,100+(i*83)%560,3+i%6);}
    drawHud(){this.panel(640,43,1248,66,0xfff0d9,0xe5aa67,19).setDepth(80);this.button(105,43,160,43,'← 備選小島',()=>this.leave(),0x9f4939).setDepth(81);this.text(432,40,'火山寶石分類車',30,'#743329').setDepth(81);this.levelText=this.text(685,44,'第 1 / 5 關',17,'#9c5c43').setDepth(81);this.soundButton=this.button(935,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xf3d5a5,'#743329').setDepth(81);this.button(1095,43,160,43,'暫停 / 說明',()=>this.pauseGame(),0xf3d5a5,'#743329').setDepth(81);this.feedback=this.text(640,105,'看顏色，把寶石送進相同顏色的桶子。',20,'#ffe4b1').setDepth(81);}
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.binViews.clear();this.gem?.destroy();this.gem=null;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${GEM_CART_LEVELS.length} 關`);const level=this.session.level;
        const crater=this.add.graphics().setDepth(12);crater.fillStyle(0x332b38).fillEllipse(675,170,235,70);crater.fillStyle(0xff8d45).fillEllipse(675,168,182,40);crater.lineStyle(7,0x775047).strokeEllipse(675,170,235,70);this.levelItems.push(crater);
        this.levelItems.push(this.text(675,145,`${level.name}｜${level.guide}`,18,'#ffe3ad').setDepth(22));
        const rail=this.add.graphics().setDepth(20);rail.lineStyle(9,0x66444a).lineBetween(335,620,1015,620);rail.lineStyle(3,0xc88758).lineBetween(335,610,1015,610);this.levelItems.push(rail);
        const xs=level.active.length===1?[675]:level.active.length===2?[565,785]:[455,675,895];level.active.forEach((id,index)=>this.makeBin(id,[xs[index],540]));
        this.progressText=this.text(675,663,'',19,'#ffe5af').setDepth(70);this.levelItems.push(this.progressText);
        this.hintButton=this.button(1112,583,210,48,'✨ 顏色提示',()=>this.showHint(),0xc18055,'#fff5dc').setDepth(71);this.helperButton=this.button(1112,642,210,48,'提示光圈：開',()=>this.toggleHelper(),0xf0cf8d,'#6c3028').setDepth(71);this.levelItems.push(this.hintButton,this.helperButton);this.refresh();this.spawnGem();
    }
    makeBin(id,[x,y]){const color=GEM_COLORS[id],c=this.add.container(x,y).setDepth(35),glow=this.add.circle(0,-15,86,color.light,0),body=this.add.graphics();body.fillStyle(color.dark).fillRoundedRect(-82,-55,164,112,18);body.fillStyle(color.fill).fillRoundedRect(-72,-45,144,88,13);body.fillStyle(0xffffff,.23).fillRoundedRect(-58,-33,116,20,9);body.lineStyle(5,0x5b3940).strokeRoundedRect(-82,-55,164,112,18);const label=this.text(0,12,color.label,21,'#fff8df'),key=this.text(0,39,`${BIN_IDS.indexOf(id)+1}`,14,'#fff2ce');c.add([glow,body,label,key]).setSize(185,130).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.chooseBin(id));c.glow=glow;c.id=id;this.binViews.set(id,c);this.levelItems.push(c);}
    drawGem(colorId){const color=GEM_COLORS[colorId],c=this.add.container(675,225).setDepth(60),ring=this.add.circle(0,0,59,color.light,0),g=this.add.graphics();g.fillStyle(color.dark).fillTriangle(0,59,-54,-10,54,-10);g.fillStyle(color.fill).fillTriangle(-54,-10,-26,-50,0,-10).fillTriangle(-26,-50,26,-50,0,-10).fillTriangle(26,-50,54,-10,0,-10);g.fillStyle(color.light,.8).fillTriangle(-26,-50,0,-10,-14,-10);g.lineStyle(4,0xffffff,.55).strokeTriangle(-54,-10,-26,-50,26,-50).strokeTriangle(-54,-10,0,59,54,-10);const shine=this.text(18,-24,'✦',22,'#ffffff');c.add([ring,g,shine]).setSize(125,125).setInteractive({useHandCursor:true,draggable:true});c.ring=ring;c.colorId=colorId;c.home={x:675,y:225};c.on('pointerdown',()=>{if(this.mode!=='playing'||this.busy)return;this.dragging=false;});c.on('dragstart',()=>{if(this.mode!=='playing'||this.busy)return;this.dragging=true;this.selected=true;this.updateSelection();});c.on('drag',(_p,dx,dy)=>{if(this.mode==='playing'&&!this.busy)c.setPosition(dx,dy);});c.on('dragend',()=>{if(this.mode!=='playing'||this.busy)return;const was=this.dragging;this.dragging=false;if(was)this.dropGem();});c.on('pointerup',()=>{if(this.mode!=='playing'||this.busy||this.dragging)return;if(Phaser.Math.Distance.Between(c.x,c.y,c.home.x,c.home.y)<20){this.selected=true;this.updateSelection();this.feedback.setText(`已選好${color.label}，再點相同顏色的桶子。`);this.tone('hint');}});this.input.setDraggable(c);return c;}
    spawnGem(){if(!this.session.currentColor)return;this.selected=false;this.busy=false;this.gem=this.drawGem(this.session.currentColor);this.gem.setScale(.25);this.tweens.add({targets:this.gem,scale:1,duration:350,ease:'Back.easeOut'});this.refresh();}
    update(_time,delta){if(this.mode!=='playing'||this.busy||this.dragging||!this.gem?.active)return;this.gem.y+=delta*.018;if(this.gem.y>430)this.returnToVolcano('寶石沒有掉下去，它會再從火山口出現～',true);}
    updateSelection(){if(!this.gem)return;this.gem.ring.setAlpha(1).setFillStyle(GEM_COLORS[this.gem.colorId].light,this.selected?.3:0);this.binViews.forEach((bin,id)=>bin.glow.setAlpha(1).setScale(1).setFillStyle(GEM_COLORS[id].light,this.helper&&this.selected&&id===this.gem.colorId?.28:0));}
    dropGem(){let choice=null,distance=Infinity;this.binViews.forEach((bin,id)=>{const d=Phaser.Math.Distance.Between(this.gem.x,this.gem.y,bin.x,bin.y);if(d<distance){distance=d;choice=id;}});if(choice&&distance<145)this.sortInto(choice);else this.returnToLane('把寶石拖近一個彩色桶子～');}
    chooseBin(id){if(this.mode!=='playing'||this.busy||!this.gem||!this.binViews.has(id))return;if(!this.selected){this.feedback.setText('先點一下上方的寶石，再點桶子喔！');this.tweens.add({targets:this.gem,scale:1.12,duration:140,yoyo:true});return;}this.sortInto(id);}
    sortInto(id){const result=this.session.classify(id);if(result==='ignored')return;if(result==='retry'){this.feedback.setText(`這是${GEM_COLORS[this.gem.colorId].label}，要找同顏色的桶子～`);this.tone('hint');this.flashBin(this.gem.colorId);this.returnToLane(null);return;}this.busy=true;this.gem.disableInteractive();const bin=this.binViews.get(id);this.feedback.setText(`${GEM_COLORS[id].label}分類成功，叮噹！`);this.tone('correct');this.tweens.add({targets:this.gem,x:bin.x,y:bin.y-10,scale:.35,angle:90,duration:360,ease:'Quad.easeIn',onComplete:()=>{this.sparkles(bin.x,bin.y-30,GEM_COLORS[id].light);this.gem.destroy();this.gem=null;this.refresh();if(result==='complete')this.time.delayedCall(500,()=>this.finishLevel());else this.time.delayedCall(260,()=>this.spawnGem());}});}
    returnToLane(message){if(!this.gem)return;this.busy=true;this.selected=false;this.updateSelection();if(message)this.feedback.setText(message);this.tweens.add({targets:this.gem,x:this.gem.home.x,y:this.gem.home.y,scale:1,angle:0,duration:330,ease:'Back.easeOut',onComplete:()=>{this.busy=false;}});}
    returnToVolcano(message,count=false){if(!this.gem||this.busy)return;if(count)this.session.returnGem();this.busy=true;this.selected=false;this.feedback.setText(message);this.tweens.add({targets:this.gem,y:168,scale:.15,alpha:.25,duration:330,onComplete:()=>{this.gem.destroy();this.gem=null;this.refresh();this.time.delayedCall(220,()=>this.spawnGem());}});}
    flashBin(id){const bin=this.binViews.get(id);if(!bin)return;bin.glow.setFillStyle(GEM_COLORS[id].light,.55);this.tweens.add({targets:bin.glow,scale:1.25,alpha:0,duration:650,yoyo:true,onComplete:()=>this.updateSelection()});}
    showHint(){if(this.mode!=='playing'||this.busy)return;const id=this.session.hint();if(!id)return;this.selected=true;this.updateSelection();this.feedback.setText(`提示：${GEM_COLORS[id].label}要進${GEM_COLORS[id].label}桶。`);this.flashBin(id);this.tone('hint');this.refresh();}
    toggleHelper(){this.helper=!this.helper;this.helperButton.label.setText(this.helper?'提示光圈：開':'提示光圈：關');this.updateSelection();this.feedback.setText(this.helper?'點選寶石後，正確桶子會亮起。':'提示光圈關閉，自己看顏色挑戰！');}
    refresh(){this.progressText?.setText(`本關 ${this.session.sorted} / ${this.session.level.order.length}　｜　重新出現 ${this.session.returns} 次　提示 ${this.session.hints} 次`);}
    sparkles(x,y,color){for(let i=0;i<10;i++){const s=this.add.star(x,y,5,3,8,i%2?color:0xffffff).setDepth(75),a=i/10*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*75,y:y+Math.sin(a)*55,alpha:0,angle:130,duration:500,onComplete:()=>s.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===GEM_CART_LEVELS.length-1;this.mode='levelComplete';this.tone('finish');const o=this.makeOverlay(last?'火山寶石全部分類完成！':'彩色礦車裝好一車了！',last?`五關全部完成！\n分類 ${this.session.totalSorted} 顆　提示 ${this.session.hints} 次`:`${this.session.level.name}完成！\n分錯或漏接都不扣分，寶石會回來再試。`);if(last){o.add(this.button(500,485,230,58,'再分一次',()=>this.restart(),0xa9503b));o.add(this.button(780,485,230,58,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}else o.add(this.button(640,485,270,58,'下一車寶石',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('新顏色來了，慢慢看清楚！');},0xa9503b));}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[123]$/.test(e.code)){const id=BIN_IDS[Number(e.code.slice(-1))-1];if(this.binViews.has(id)){this.selected=true;this.updateSelection();this.chooseBin(id);}}else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyB')this.toggleHelper();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('火山寶石小隊出發！','點一下寶石，再點相同顏色的礦車桶；\n也可以直接把寶石拖進桶子。\n分錯或漏接都不扣分，寶石會回來再試。');o.add(this.text(640,410,'紅、黃、藍三色會從一種慢慢增加到三種。',19,'#8a5b42'));o.add(this.button(640,500,285,60,'開始分類！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0xa9503b));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('礦車休息一下','點寶石後再點同色桶子，或直接拖進桶子。\n提示光圈預設開啟；H 顯示提示，B 可切換光圈。\n分錯不扣分，寶石會彈回原位。');o.add(this.button(640,415,270,55,'繼續分類',()=>this.resumeGame(),0xa9503b));o.add(this.button(640,500,270,51,'返回備選小島',()=>this.leave(),0xf0cf8d,'#6c3028'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'VolcanoBonusMap');}
}
