import AnimalSnackGame from './AnimalSnackGame.js';
import {WaterFlowMazeSession,WATER_FLOW_LEVELS,WATERWAY_TYPES} from '../data/WaterFlowMazeData.js';

const CELL=148,ORIGIN_X=575,ORIGIN_Y=245;

export default class WaterFlowMazeGame extends AnimalSnackGame {
    constructor(){super('WaterFlowMazeGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new WaterFlowMazeSession();this.helper=true;this.busy=false;this.views=[];this.levelItems=[];
        this.drawWaterWorld();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    drawWaterWorld(){const g=this.add.graphics();g.fillGradientStyle(0x58b4cf,0x8bd5df,0xc7eee6,0x5ca8b8,1).fillRect(0,0,1280,720);g.fillStyle(0x3d8c9e,.7).fillRoundedRect(-30,410,1340,330,110);g.fillStyle(0x75c9ca,.8).fillRoundedRect(-20,500,1320,210,95);for(let i=0;i<38;i++)g.fillStyle(i%2?0xc9f4eb:0xffffff,.35).fillCircle(20+(i*157)%1240,95+(i*73)%590,3+i%7);for(let i=0;i<7;i++){const x=270+i*185,y=650-(i%2)*25;g.fillStyle(0x4b9b77,.75).fillEllipse(x,y,115,45);g.fillStyle(0xe6a3ba,.85).fillCircle(x,y-14,16);}}
    drawHud(){this.panel(640,43,1248,66,0xf7fffb,0xbfe4dd,19).setDepth(80);this.button(101,43,150,43,'← 遊戲列表',()=>this.leave(),0x3e8797).setDepth(81);this.text(399,40,'水流迷宮・幼童版',30,'#275f6d').setDepth(81);this.levelText=this.text(675,43,'第 1 / 5 關',18,'#628994').setDepth(81);this.soundButton=this.button(930,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xdaf0e9,'#275f6d').setDepth(81);this.button(1091,43,164,43,'暫停 / 說明',()=>this.pauseGame(),0xdaf0e9,'#275f6d').setDepth(81);
        this.panel(150,348,250,470,0xf7fffb,0xbfe4dd,23).setDepth(60);this.text(150,128,'水滴小任務',22,'#275f6d').setDepth(61);this.taskText=this.text(150,180,'',18,'#527985').setWordWrapWidth(210,true).setDepth(61);this.progressText=this.text(150,270,'',27,'#275f6d').setDepth(61);this.statText=this.text(150,332,'',16,'#628994').setDepth(61);this.hintButton=this.button(150,420,195,48,'💧 單格提示',()=>this.showHint(),0xe4bd64,'#594d2e').setDepth(62);this.helperButton=this.button(150,480,195,48,'金色影子：開',()=>this.toggleHelper(),0xdaf0e9,'#275f6d').setDepth(62);this.resetButton=this.button(150,540,195,48,'↺ 本關重來',()=>this.resetLevel(),0xdaf0e9,'#275f6d').setDepth(62);this.feedback=this.text(695,104,'點大型水道旋轉，再按「放水看看」。',20,'#316b76').setDepth(81);this.text(720,692,'點水道旋轉｜金色影子是正確方向｜接錯不扣分，可一直放水測試',16,'#3d7280').setDepth(70);}
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.views=[];this.busy=false;const level=this.session.level;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${WATER_FLOW_LEVELS.length} 關`);this.taskText.setText(`${level.name}\n${level.guide}`);
        const board=this.panel(735,390,700,520,0xeaf8ee,0x8fcbbb,34).setDepth(18);this.levelItems.push(board);
        level.pieces.forEach((piece,index)=>this.makeWaterway(piece,index));const first=this.worldPoint(level.pieces[0]),last=this.worldPoint(level.pieces[level.pieces.length-1]);this.source=this.drawSource(first.x-112,first.y).setDepth(42);this.flower=this.drawFlower(last.x+112,last.y).setDepth(42);this.levelItems.push(this.source,this.flower);
        this.flowButton=this.button(1065,580,235,58,'🌊 放水看看',()=>this.runWater(),0x3f93a3).setDepth(63);this.levelItems.push(this.flowButton);this.refresh();
    }
    worldPoint(piece){return{x:ORIGIN_X+piece.x*CELL,y:ORIGIN_Y+piece.y*CELL};}
    makeWaterway(piece,index){const p=this.worldPoint(piece),c=this.add.container(p.x,p.y).setDepth(38),pad=this.add.circle(0,0,65,0x7ec2a1).setStrokeStyle(5,0x4f967a),ghost=this.drawChannel(piece.type,piece.target,0xffdc69,.32),channel=this.drawChannel(piece.type,0,0x4eafd0,1),label=this.text(0,78,String(index+1),15,'#477265');channel.setAngle(this.session.rotations[index]*90);c.add([pad,ghost,channel,label]).setSize(142,142).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.rotatePiece(index));c.channel=channel;c.ghost=ghost;c.index=index;this.views.push(c);this.levelItems.push(c);}
    drawChannel(type,rotation,color,alpha){const g=this.add.graphics().setAngle(rotation*90);g.lineStyle(23,color,alpha).beginPath();if(type==='straight')g.moveTo(-66,0).lineTo(66,0);else g.moveTo(0,-66).lineTo(0,0).lineTo(66,0);g.strokePath();g.lineStyle(5,0xffffff,alpha*.55).beginPath();if(type==='straight')g.moveTo(-66,0).lineTo(66,0);else g.moveTo(0,-66).lineTo(0,0).lineTo(66,0);g.strokePath();return g;}
    drawSource(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.fillStyle(0x5b8278).fillRoundedRect(-50,-48,100,96,25);g.fillStyle(0x69cbe0).fillEllipse(0,0,68,62);g.fillStyle(0xdffbff,.75).fillEllipse(-10,-13,25,12);const label=this.text(0,67,'水滴泉源',16,'#2d6671');c.add([g,label]);return c;}
    drawFlower(x,y){const c=this.add.container(x,y),g=this.add.graphics();g.lineStyle(8,0x4f9b65).lineBetween(0,14,0,62);g.fillStyle(0x69ae73).fillEllipse(-17,43,31,14).fillEllipse(17,31,31,14);for(let i=0;i<6;i++){const a=i/6*Math.PI*2;g.fillStyle(0xe987ac).fillCircle(Math.cos(a)*22,-4+Math.sin(a)*22,14);}g.fillStyle(0xffd65e).fillCircle(0,-4,13);const label=this.text(0,83,'等水的花朵',16,'#477265');c.add([g,label]);c.bloom=g;return c;}
    rotatePiece(index){if(this.mode!=='playing'||this.busy)return;const result=this.session.rotate(index);if(result==='ignored')return;const view=this.views[index];this.tweens.add({targets:view.channel,angle:view.channel.angle+90,duration:180,ease:'Back.easeOut'});this.feedback.setText(result==='aligned'?'這塊水道對準金色影子了！':'水道轉了一圈，看看藍色能不能接起來。');this.tone(result==='aligned'?'correct':'send');this.refresh();}
    runWater(){if(this.mode!=='playing'||this.busy)return;const result=this.session.flow();if(result.result==='ignored')return;this.busy=true;this.feedback.setText(result.result==='complete'?'水路接通了，水滴要去找花朵！':'水滴出發，看看會流到哪裡～');this.tone('send');this.animateWater(result);this.refresh();}
    animateWater(result){const last=result.result==='complete'?this.session.level.pieces.length-1:result.leakIndex;const points=[{x:this.source.x,y:this.source.y},...this.session.level.pieces.slice(0,last+1).map(piece=>this.worldPoint(piece))];if(result.result==='complete')points.push({x:this.flower.x,y:this.flower.y});const drop=this.add.circle(points[0].x,points[0].y,15,0x76ddf0).setStrokeStyle(4,0xffffff).setDepth(68),step=index=>{if(index>=points.length){if(result.result==='complete'){this.bloomFlower();drop.destroy();}else{this.splash(drop.x,drop.y);drop.destroy();this.busy=false;this.feedback.setText(`水在第 ${result.leakIndex+1} 塊停下來了，轉一轉再試！`);this.flashView(result.leakIndex);this.tone('hint');}return;}this.tweens.add({targets:drop,x:points[index].x,y:points[index].y,duration:330,ease:'Sine.easeInOut',onComplete:()=>step(index+1)});};step(1);}
    bloomFlower(){this.tone('finish');this.feedback.setText('水成功流到花朵，盛開了！');this.tweens.add({targets:this.flower,scale:1.35,duration:300,yoyo:true,repeat:2,onComplete:()=>{this.sparkles(this.flower.x,this.flower.y);this.time.delayedCall(450,()=>this.finishLevel());}});}
    showHint(){if(this.mode!=='playing'||this.busy)return;const index=this.session.hint();if(index<0)return;this.feedback.setText(`提示：第 ${index+1} 塊水道還沒對準金色影子。`);this.flashView(index);this.tone('hint');this.refresh();}
    flashView(index){const view=this.views[index];if(view)this.tweens.add({targets:view,scale:1.15,duration:180,yoyo:true,repeat:4});}
    toggleHelper(){if(this.mode!=='playing'||this.busy)return;this.helper=!this.helper;this.helperButton.label.setText(this.helper?'金色影子：開':'金色影子：關');this.views.forEach(view=>view.ghost.setVisible(this.helper));this.feedback.setText(this.helper?'金色影子會顯示正確流向。':'影子收起來，自己觀察水路！');}
    resetLevel(){if(this.mode!=='playing'||this.busy)return;this.session.reset();this.drawLevel();this.feedback.setText('水道重新打亂，再慢慢轉一次。');this.tone('hint');}
    refresh(){const ready=this.session.level.pieces.filter((_piece,index)=>this.session.isCorrect(index)).length;this.progressText.setText(`接好 ${ready} / ${this.session.level.pieces.length}`);this.statText.setText(`旋轉 ${this.session.totalRotations} 次\n放水 ${this.session.tests} 次　提示 ${this.session.hints} 次`);}
    sparkles(x,y){for(let i=0;i<12;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffd55e:0xffffff).setDepth(74),a=i/12*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*90,y:y+Math.sin(a)*68,alpha:0,angle:150,duration:520,onComplete:()=>s.destroy()});}}
    splash(x,y){for(let i=0;i<9;i++){const d=this.add.circle(x,y,5+i%3,0x91e8f2,.9).setDepth(70);this.tweens.add({targets:d,x:x-55+i*14,y:y-45-Math.abs(i-4)*4,alpha:0,duration:480,onComplete:()=>d.destroy()});}}
    finishLevel(){const last=this.session.levelIndex===WATER_FLOW_LEVELS.length-1;this.mode='levelComplete';this.busy=false;const o=this.makeOverlay(last?'五座花園全部喝到水了！':'花朵開心地盛開了！',last?`水流迷宮五關完成！\n旋轉 ${this.session.totalRotations} 次　放水測試 ${this.session.tests} 次`:`${this.session.level.name}完成！\n接錯不扣分，每次放水都能看見哪裡要調整。`);if(last){o.add(this.button(500,485,230,58,'再玩一次',()=>this.restart(),0x3e8797));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe4bd64,'#594d2e'));}else o.add(this.button(640,485,270,58,'下一座水花園',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('新的大水道來了，點一下轉方向！');},0x3e8797));}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-4]$/.test(e.code))this.rotatePiece(Number(e.code.slice(-1))-1);else if(e.code==='Space')this.runWater();else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyR')this.resetLevel();else if(e.code==='KeyG')this.toggleHelper();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('小水滴要去找花朵！','點一下大型水道，它會旋轉 90 度。\n把 2～4 塊水道接起來，再按「放水看看」；\n接錯不扣分，水滴會告訴你在哪一塊停下。');o.add(this.text(640,410,'金色影子預設開啟，可照著影子慢慢轉。',19,'#5f8586'));o.add(this.button(640,500,290,60,'開始接水道！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0x3e8797));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('小水滴休息一下','點水道旋轉，讓藍色水路對準金色影子。\n按「放水看看」測試；接錯不扣分，可一直再試。\n鍵盤 1～4 旋轉，空白鍵放水，H 提示，R 重來。');o.add(this.button(640,415,270,55,'繼續接水道',()=>this.resumeGame(),0x3e8797));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xdaf0e9,'#275f6d'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
