import AnimalSnackGame from './AnimalSnackGame.js';
import {DIRS,WaterFlowMazeSession,WATER_FLOW_LEVELS,WATERWAY_TYPES} from '../data/WaterFlowMazeData.js';

const PIPE_COLOR=0x275f70,WATER_COLOR=0x66dcf2;
const TYPE_ICON={valve:'⚙',pump:'⬆',filter:'✦',ice:'❄',reservoir:'◉',tee:'',cross:'',straight:'',corner:''};

export default class WaterFlowMazeGame extends AnimalSnackGame{
    constructor(){super('WaterFlowMazeGame');}
    create(){
        this.sound.stopAll();this.soundOn=true;this.audioNodes=new Set();this.overlay=null;this.mode='intro';this.session=new WaterFlowMazeSession();this.busy=false;this.views=[];this.levelItems=[];this.endpointItems=[];this.timeLeft=0;this.frogClock=0;this.frogDone=false;
        this.drawWaterWorld();this.drawHud();this.drawLevel();this.bindKeys();this.showIntro();
        this.visibilityHandler=()=>{if(document.hidden&&this.mode==='playing')this.pauseGame();};this.blurHandler=()=>{if(this.mode==='playing')this.pauseGame();};document.addEventListener('visibilitychange',this.visibilityHandler);this.game.events.on('blur',this.blurHandler);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',this.visibilityHandler);this.game.events.off('blur',this.blurHandler);this.input.keyboard?.off('keydown',this.keyHandler);this.stopTones();});
    }
    update(_time,delta){
        if(this.mode!=='playing')return;const dt=Math.min(.05,Math.max(0,delta/1000)),level=this.session.level;
        if(level.timeLimit){this.timeLeft=Math.max(0,this.timeLeft-dt);this.timerText.setText(`⏳ ${Math.ceil(this.timeLeft)} 秒`);if(this.timeLeft<=0)this.failLevel('潮水時間到了，重新調整水道再試一次。');}
        if(level.frog&&!this.frogDone){this.frogClock-=dt;if(this.frogClock<=0)this.frogMischief();}
    }
    drawWaterWorld(){const g=this.add.graphics();g.fillGradientStyle(0x48aac4,0x8ad5df,0xc5eee5,0x4d9cad,1).fillRect(0,0,1280,720);g.fillStyle(0x337f95,.68).fillRoundedRect(-30,425,1340,315,110);g.fillStyle(0x73caca,.72).fillRoundedRect(-20,515,1320,205,95);for(let i=0;i<40;i++)g.fillStyle(i%2?0xc9f4eb:0xffffff,.32).fillCircle(15+(i*157)%1240,90+(i*73)%600,3+i%6);for(let i=0;i<7;i++){const x=250+i*185,y=655-(i%2)*23;g.fillStyle(0x438e70,.8).fillEllipse(x,y,115,43);g.fillStyle(0xe6a3ba,.85).fillCircle(x,y-14,15);}}
    drawHud(){
        this.panel(640,43,1248,66,0xf7fffb,0xbfe4dd,19).setDepth(80);this.button(98,43,148,43,'← 遊戲列表',()=>this.leave(),0x357f90).setDepth(81);this.text(385,40,'水精靈工坊・潮汐花園',28,'#275f6d').setDepth(81);this.levelText=this.text(665,43,'第 1 / 10 關',18,'#628994').setDepth(81);this.timerText=this.text(795,43,'',18,'#a65752').setDepth(81);this.soundButton=this.button(935,43,116,43,'音效：開',()=>{this.soundOn=!this.soundOn;if(!this.soundOn)this.stopTones();this.soundButton.label.setText(this.soundOn?'音效：開':'音效：關');},0xdaf0e9,'#275f6d').setDepth(81);this.button(1095,43,165,43,'暫停 / 說明',()=>this.pauseGame(),0xdaf0e9,'#275f6d').setDepth(81);
        this.panel(150,360,250,500,0xf7fffb,0xbfe4dd,23).setDepth(60);this.text(150,125,'潮汐任務',22,'#275f6d').setDepth(61);this.taskText=this.text(150,186,'',17,'#527985').setWordWrapWidth(210,true).setDepth(61);this.progressText=this.text(150,298,'',23,'#275f6d').setDepth(61);this.statText=this.text(150,360,'',16,'#628994').setDepth(61);this.hintButton=this.button(150,440,195,48,'✨ 水精靈提示',()=>this.showHint(),0xe4bd64,'#594d2e').setDepth(62);this.resetButton=this.button(150,500,195,48,'↺ 本關重來',()=>this.resetLevel(),0xdaf0e9,'#275f6d').setDepth(62);this.flowButton=this.button(150,560,195,52,'🌊 開閘放水',()=>this.runWater(),0x3b91a3).setDepth(62);
        this.feedback=this.text(700,104,'先觀察水道出口，再旋轉管線。',19,'#285f6c').setDepth(81);this.scoreText=this.text(1080,685,'累積 0 ★',17,'#f5ffff').setDepth(82);this.text(650,693,'點水道旋轉｜齒輪水閥用點擊開關｜每次放水會消耗一格水量',15,'#eaffff').setDepth(70);
    }
    drawLevel(){
        this.levelItems.forEach(v=>v.destroy());this.levelItems=[];this.endpointItems=[];this.views=[];this.busy=false;this.frogDone=false;const level=this.session.level;this.timeLeft=level.timeLimit||0;this.frogClock=9;this.levelText.setText(`第 ${this.session.levelIndex+1} / ${WATER_FLOW_LEVELS.length} 關`);this.timerText.setText(level.timeLimit?`⏳ ${level.timeLimit} 秒`:'');this.taskText.setText(`${level.name}\n${level.guide}`);
        const board=this.panel(735,390,770,520,0xeaf8ee,0x86c7b7,34).setDepth(18);this.levelItems.push(board);this.cell=Math.min(108,570/level.cols,400/level.rows);this.originX=710-(level.cols-1)*this.cell/2;this.originY=365-(level.rows-1)*this.cell/2;
        level.pieces.forEach((piece,index)=>this.makeWaterway(piece,index));(level.hazards||[]).forEach(h=>this.drawHazard(h));level.sources.forEach(s=>this.drawSource(s));level.sinks.forEach((s,i)=>this.drawSink(s,i));this.clearWater();this.refresh();
    }
    point(x,y){return{x:this.originX+x*this.cell,y:this.originY+y*this.cell};}
    edgePoint(endpoint){const p=this.point(endpoint.x,endpoint.y),d=DIRS[endpoint.side];return{x:p.x+d.dx*this.cell*.57,y:p.y+d.dy*this.cell*.57};}
    makeWaterway(piece,index){
        const p=this.point(piece.x,piece.y),size=this.cell*.78,c=this.add.container(p.x,p.y).setDepth(38),pad=this.add.rectangle(0,0,size,size,piece.decoy?0xb8c8a7:0x78b99b).setStrokeStyle(4,0x438c75),channel=this.drawPipe(piece.type,PIPE_COLOR,18),water=this.drawPipe(piece.type,WATER_COLOR,9).setVisible(false),icon=this.text(0,0,TYPE_ICON[piece.type]||'',piece.type==='valve'?22:19,'#fffbe4'),status=this.text(0,size*.34,piece.type==='valve'?'關':'',13,'#355f58');channel.setAngle(this.session.rotations[index]*90);water.setAngle(channel.angle);c.add([pad,channel,water,icon,status]).setSize(size,size).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.activatePiece(index));this.views[index]={container:c,pad,channel,water,icon,status,piece};this.levelItems.push(c);
    }
    drawPipe(type,color,width){const g=this.add.graphics(),ports=WATERWAY_TYPES[type]?.ports||[];g.lineStyle(width,0x174c58,.23);ports.forEach(side=>{const d=DIRS[side];g.lineBetween(0,0,d.dx*this.cell*.42,d.dy*this.cell*.42);});g.lineStyle(Math.max(4,width-6),color,1);ports.forEach(side=>{const d=DIRS[side];g.lineBetween(0,0,d.dx*this.cell*.43,d.dy*this.cell*.43);});g.fillStyle(color,1).fillCircle(0,0,Math.max(6,width*.45));return g;}
    drawSource(source){const p=this.edgePoint(source),color=source.quality==='dirty'?0x8b7549:0x61d3e8,c=this.add.container(p.x,p.y).setDepth(43),g=this.add.graphics();g.fillStyle(0x47796e).fillRoundedRect(-30,-30,60,60,16);g.fillStyle(color).fillCircle(0,0,21);g.fillStyle(0xffffff,.6).fillEllipse(-7,-8,13,7);c.add([g,this.text(0,43,source.quality==='dirty'?'污水源':'泉源',13,'#35616b')]);this.levelItems.push(c);}
    drawSink(sink,index){const p=this.edgePoint(sink),c=this.add.container(p.x,p.y).setDepth(43),g=this.add.graphics(),water=this.add.circle(0,0,33,0x76d8e9,.16);if(sink.name.includes('水車')||sink.name.includes('排洪')){g.lineStyle(7,0x7a674c);for(let i=0;i<6;i++){const a=i*Math.PI/3;g.lineBetween(0,0,Math.cos(a)*29,Math.sin(a)*29);}g.fillStyle(0xd9b76b).fillCircle(0,0,8);}else{g.lineStyle(6,0x4f9b65).lineBetween(0,8,0,35);for(let i=0;i<6;i++){const a=i/6*Math.PI*2;g.fillStyle(sink.quality==='cold'?0x9dddf2:0xe987ac).fillCircle(Math.cos(a)*17,-4+Math.sin(a)*17,10);}g.fillStyle(0xffd65e).fillCircle(0,-4,9);}const label=this.text(0,48,sink.name,13,'#426d72');c.add([water,g,label]);this.endpointItems[index]={container:c,water,label,sink};this.levelItems.push(c);}
    drawHazard(h){const p=this.point(h.x,h.y),c=this.add.container(p.x,p.y).setDepth(50),g=this.add.graphics();g.fillStyle(0xe7d8a6).fillRoundedRect(-8,0,16,30,7);g.fillStyle(0xd76f6f).fillEllipse(0,-6,55,34);g.fillStyle(0xffffff,.75).fillCircle(-13,-10,4).fillCircle(10,-4,4);c.add([g,this.text(0,35,'噓…',13,'#725b52')]);this.levelItems.push(c);}
    activatePiece(index){if(this.mode!=='playing'||this.busy)return;const view=this.views[index],piece=view.piece;if(piece.type==='valve'){const result=this.session.toggleValve(index);view.status.setText(result==='opened'?'開':'關');view.pad.setFillStyle(result==='opened'?0x79c8a0:0x9aab94);this.feedback.setText(result==='opened'?'水閥打開了！':'水閥關起來了。');this.tone('send');return;}const result=this.session.rotate(index);if(result==='ignored')return;this.tweens.add({targets:[view.channel,view.water],angle:view.channel.angle+90,duration:180,ease:'Back.easeOut'});this.feedback.setText(result==='aligned'?'聽到清脆的「喀」！這塊方向很順。':'水道轉動了，看看兩端能不能相接。');this.tone(result==='aligned'?'correct':'send');this.refresh();}
    runWater(){if(this.mode!=='playing'||this.busy)return;const result=this.session.flow();if(result.result==='ignored'){if(result.empty)this.feedback.setText('水塔空了，按「本關重來」補滿水再試。');return;}this.busy=true;this.clearWater();this.feedback.setText('開閘！水正在沿著真正接通的管線前進…');this.tone('send');this.animateTrace(result);this.refresh();}
    animateTrace(result){let i=0;const next=()=>{if(i>=result.order.length){this.time.delayedCall(260,()=>this.resolveFlow(result));return;}const state=result.order[i++],view=this.views[state.index];view.water.setVisible(true).setAlpha(.25);this.tweens.add({targets:view.water,alpha:1,duration:190});this.tweens.add({targets:view.pad,scale:1.08,duration:100,yoyo:true,onComplete:next});this.tone(state.quality==='cold'?'hint':'send');};next();}
    resolveFlow(result){if(this.mode!=='playing')return;if(result.result==='complete'){result.sinks.forEach((_s,i)=>this.bloomSink(i));this.feedback.setText(`全部接通！獲得 ${'★'.repeat(result.stars)}！`);this.tone('finish');this.time.delayedCall(850,()=>{if(this.mode==='playing')this.finishLevel(result.stars);});return;}this.busy=false;if(result.danger.length){this.feedback.setText('水碰到睡覺蘑菇了！繞另一條路吧。');this.tone('hint');}
        else{const bad=result.sinks.find(s=>s&&!s.ok);if(bad)this.feedback.setText(bad.sink.quality?'水的種類不對，需要先經過特殊水道。':'水壓不足，需要先通過壓力泵。');else this.feedback.setText('水從紅色接縫漏出來了，找出沒有相接的出口。');this.tone('hint');}
        this.flashLeaks(result.leaks);if(this.session.water<=0)this.feedback.setText(`${this.feedback.text} 水塔已空，請重開本關補水。`);this.refresh();
    }
    bloomSink(index){const e=this.endpointItems[index];if(!e)return;e.water.setFillStyle(0x76e4f2,.9);this.tweens.add({targets:e.container,scale:1.3,duration:220,yoyo:true,repeat:2});this.sparkles(e.container.x,e.container.y);}
    flashLeaks(leaks){const done=new Set();leaks.forEach(raw=>{const [x,y]=raw.split(',').map(Number),index=this.session.level.pieces.findIndex(p=>p.x===x&&p.y===y);if(index<0||done.has(index))return;done.add(index);const v=this.views[index];v.pad.setStrokeStyle(5,0xe36965);this.tweens.add({targets:v.container,alpha:.45,duration:160,yoyo:true,repeat:3,onComplete:()=>v.pad.setStrokeStyle(4,0x438c75)});});}
    clearWater(){this.views.forEach(v=>v.water.setVisible(false).setAlpha(1));this.endpointItems.forEach(e=>e?.water.setFillStyle(0x76d8e9,.16));}
    showHint(){if(this.mode!=='playing'||this.busy)return;const index=this.session.hint();if(index<0)return;const view=this.views[index],stage=((this.session.hints-1)%3)+1;if(stage===3){if(view.piece.type==='valve'){this.session.valves[index]=true;view.status.setText('開');view.pad.setFillStyle(0x79c8a0);}else{this.session.rotations[index]=view.piece.target;view.channel.setAngle(view.piece.target*90);view.water.setAngle(view.piece.target*90);}this.feedback.setText(`水精靈幫你修好第 ${index+1} 塊水道！`);}else this.feedback.setText(stage===1?`水聲提示：注意第 ${index+1} 塊水道。`:`方向提示：第 ${index+1} 塊還需要再轉一轉。`);this.tweens.add({targets:view.container,scale:1.14,duration:180,yoyo:true,repeat:3});this.tone('hint');this.refresh();}
    frogMischief(){this.frogDone=true;const candidates=this.views.map((v,i)=>({v,i})).filter(({v,i})=>v.piece.type!=='valve'&&this.session.rotations[i]===v.piece.target);if(!candidates.length)return;const {v,i}=candidates[Math.floor(this.session.levelRotations%candidates.length)];this.session.rotations[i]=(this.session.rotations[i]+1)%4;const frog=this.text(1040,150,'🐸',42,'#fff').setDepth(95);this.feedback.setText(`青蛙跳到第 ${i+1} 塊水道，把它轉了一次！`);this.tweens.add({targets:frog,x:v.container.x,y:v.container.y-25,duration:550,yoyo:true,hold:250,onComplete:()=>frog.destroy()});this.tweens.add({targets:[v.channel,v.water],angle:v.channel.angle+90,duration:220,delay:450});this.tone('hint');}
    resetLevel(){if(this.mode!=='playing'||this.busy)return;this.session.reset();this.drawLevel();this.feedback.setText('水塔補滿，水道也重新排列好了。');this.tone('hint');}
    refresh(){const level=this.session.level,openValves=level.pieces.filter((p,i)=>p.type==='valve'&&this.session.valves[i]).length,totalValves=level.pieces.filter(p=>p.type==='valve').length;this.progressText.setText(`水量 ${'💧'.repeat(this.session.water)}${'○'.repeat(Math.max(0,level.water-this.session.water))}`);this.statText.setText(`旋轉 ${this.session.totalRotations} 次　放水 ${this.session.tests} 次\n提示 ${this.session.hints} 次${totalValves?`　水閥 ${openValves}/${totalValves}`:''}`);this.scoreText.setText(`累積 ${this.session.totalStars} ★`);}
    sparkles(x,y){for(let i=0;i<12;i++){const s=this.add.star(x,y,5,3,8,i%2?0xffdf66:0xffffff).setDepth(74),a=i/12*Math.PI*2;this.tweens.add({targets:s,x:x+Math.cos(a)*80,y:y+Math.sin(a)*62,alpha:0,angle:150,duration:520,onComplete:()=>s.destroy()});}}
    finishLevel(stars){const last=this.session.levelIndex===WATER_FLOW_LEVELS.length-1;this.mode='levelComplete';this.busy=false;const o=this.makeOverlay(last?'巨大潮汐樹甦醒了！':'潮汐花園恢復水流！',last?`十座水流花園全部完成！\n共獲得 ${this.session.totalStars} 顆星　放水測試 ${this.session.tests} 次`:`${this.session.level.name}完成！\n本關獲得 ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}　水真的沿著接通的管線抵達終點。`);if(last){o.add(this.button(500,485,230,58,'重新挑戰',()=>this.restart(),0x357f90));o.add(this.button(780,485,230,58,'返回遊戲列表',()=>this.leave(),0xe4bd64,'#594d2e'));}else o.add(this.button(640,485,280,58,'前往下一座花園',()=>{o.destroy();this.overlay=null;this.session.advance();this.mode='playing';this.drawLevel();this.feedback.setText('新的潮汐機關出現了！');},0x357f90));}
    failLevel(message){if(this.mode!=='playing')return;this.mode='failed';this.busy=false;this.stopTones();const o=this.makeOverlay('排水任務還沒完成',message);o.add(this.button(640,475,280,58,'重新挑戰本關',()=>{o.destroy();this.overlay=null;this.session.load();this.mode='playing';this.drawLevel();},0x357f90));}
    bindKeys(){this.keyHandler=e=>{if(e.repeat)return;if(/^Digit[1-9]$/.test(e.code))this.activatePiece(Number(e.code.slice(-1))-1);else if(e.code==='Space')this.runWater();else if(e.code==='KeyH')this.showHint();else if(e.code==='KeyR')this.resetLevel();else if(e.code==='Escape'||e.code==='KeyP')this.mode==='paused'?this.resumeGame():this.pauseGame();};this.input.keyboard?.on('keydown',this.keyHandler);}
    showIntro(){const o=this.makeOverlay('水精靈工坊開張！','旋轉水道，讓每個出口真正相接，再開閘觀察水流。\n後面會出現分流、水閥、壓力泵、冰晶管、淨化石與限時排洪。\n每次放水會消耗一格水量，但可隨時重開本關補滿。');o.add(this.text(640,420,'提示分三次：指出問題、提示方向、幫你修好一塊。',19,'#5f8586'));o.add(this.button(640,510,300,60,'開始修水道！',()=>{o.destroy();this.overlay=null;this.mode='playing';this.sound.context?.resume?.();},0x357f90));}
    pauseGame(){if(this.mode!=='playing')return;this.mode='paused';this.tweens.pauseAll();this.stopTones();const o=this.makeOverlay('潮汐暫停','點水道旋轉 90 度；齒輪水閥點一下切換開關。\n接好後按「開閘放水」，水會逐格顯示流到哪裡。\n空白鍵放水、H 提示、R 重開本關。');o.add(this.button(640,420,270,55,'繼續修水道',()=>this.resumeGame(),0x357f90));o.add(this.button(640,500,270,51,'返回遊戲列表',()=>this.leave(),0xdaf0e9,'#275f6d'));}
    resumeGame(){if(this.mode!=='paused')return;this.overlay?.destroy();this.overlay=null;this.mode='playing';this.tweens.resumeAll();}
    restart(){this.tweens.resumeAll();this.scene.restart({returnScene:this.returnScene});}
    leave(){this.tweens.resumeAll();this.scene.start(this.scene.manager.keys[this.returnScene]?this.returnScene:'MiniGameHub');}
}
