import {RealmWorld} from './RealmWorld.js';
import {RealmJourney,SPOTS} from './RealmRules.js';
const SAVE='forest_phantom_realm_v1';
export class RealmApp{
 constructor(root,{onExit=()=>{},onSound=()=>{}}={}){this.root=root;this.onExit=onExit;this.onSound=onSound;this.abort=new AbortController();this.keys=new Set();this.axis={x:0,y:0};this.joyId=null;this.dead=false;this.paused=true;this.storageOK=true;let saved;try{saved=JSON.parse(localStorage.getItem(SAVE)||'null');}catch{}this.journey=new RealmJourney(saved);this.buildUI();}
 el(tag,cls,text,parent=this.root){const e=document.createElement(tag);e.className=cls;if(text)e.textContent=text;parent.append(e);return e;}
 on(el,type,fn){el.addEventListener(type,fn,{signal:this.abort.signal});}
 button(text,fn,parent,cls=''){const b=this.el('button',cls,text,parent);b.type='button';this.on(b,'click',fn);return b;}
 buildUI(){this.root.classList.add('realm-app');const style=this.el('style');style.textContent=`
 .realm-app{position:fixed;inset:0;z-index:10000;overflow:hidden;background:#183e38;color:#fff1ce;font:600 17px "Microsoft JhengHei",sans-serif;touch-action:none;user-select:none;isolation:isolate}
 .realm-app *{box-sizing:border-box}.realm-app canvas{width:100%;height:100%;display:block}.realm-app button{font:inherit;color:inherit;cursor:pointer;border:1px solid #d7c08b88;background:#244e46e8;border-radius:16px;min-height:46px;padding:10px 18px;touch-action:none}.realm-app button:active{transform:scale(.96);background:#67886b}.realm-app button:disabled{opacity:.5;cursor:default}
 .realm-app .top{position:absolute;top:max(12px,env(safe-area-inset-top));left:max(16px,env(safe-area-inset-left));right:max(16px,env(safe-area-inset-right));display:flex;align-items:start;justify-content:space-between;gap:10px;pointer-events:none}.realm-app .brand{background:#173e37ed;border:1px solid #dccf9866;border-radius:18px;padding:12px 18px;max-width:55%;box-shadow:0 6px 24px #173b3720}.realm-app .eyebrow{font-size:11px;letter-spacing:3px;color:#c5d9b9}.realm-app h1{margin:3px 0 7px;font-size:25px;letter-spacing:2px}.realm-app .objective{font-size:15px;color:#e9e9c2}.realm-app .topnav{display:flex;gap:7px;pointer-events:auto}.realm-app .topnav button{font-size:15px;padding:10px 13px}
 .realm-app .bottom{position:absolute;left:50%;bottom:max(15px,env(safe-area-inset-bottom));transform:translateX(-50%);background:#173e37db;border-radius:16px;padding:10px 18px;text-align:center;font-size:13px;max-width:40%;pointer-events:none}.realm-app .inventory{color:#eed59d;margin-bottom:5px}.realm-app .toast{position:absolute;left:50%;top:25%;transform:translateX(-50%);padding:12px 22px;background:#183e37eb;border:1px solid #d8c391;border-radius:16px;text-align:center;max-width:65%;opacity:0;transition:opacity .15s;pointer-events:none}
 .realm-app .joy{position:absolute;bottom:max(24px,env(safe-area-inset-bottom));left:max(27px,env(safe-area-inset-left));width:132px;height:132px;border-radius:50%;border:2px solid #eff0c780;background:#214d4659;box-shadow:inset 0 0 30px #ffffff14;touch-action:none}.realm-app .knob{position:absolute;width:56px;height:56px;left:36px;top:36px;border-radius:50%;background:#e1e6bed9;border:2px solid #fff5d4;pointer-events:none}.realm-app .joylabel{position:absolute;bottom:-19px;width:100%;text-align:center;font-size:12px;opacity:.85;pointer-events:none}
 .realm-app .actions{position:absolute;right:max(25px,env(safe-area-inset-right));bottom:max(25px,env(safe-area-inset-bottom));display:flex;align-items:end;gap:13px}.realm-app .actions button{border-radius:50%;width:82px;height:82px;padding:8px;font-size:17px;box-shadow:0 5px 16px #183b3733}.realm-app .actions .interact{width:108px;height:108px;background:#a47d3bea;border:2px solid #f4d991;font-size:21px}.realm-app .actions .fan{margin-bottom:65px;margin-right:-15px}.realm-app .context{position:absolute;bottom:27%;left:50%;transform:translateX(-50%);background:#1b433bcf;border-radius:12px;padding:8px 16px;pointer-events:none;font-size:16px;white-space:nowrap}
 .realm-app .modal{position:absolute;inset:0;background:#102d2aba;display:flex;justify-content:center;align-items:center;padding:18px;backdrop-filter:blur(4px)}.realm-app .card{width:min(740px,94%);max-height:94%;overflow:auto;background:#f7f0d9;color:#284f43;border:3px solid #bfa86b;border-radius:26px;padding:26px 34px;box-shadow:0 20px 80px #081f2b80}.realm-app h2{font-size:29px;margin:0 0 15px}.realm-app .body{font-size:19px;line-height:1.7;white-space:pre-line}.realm-app .choices{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.realm-app .choices button{flex:1;color:#fff3d4;background:#356453;min-width:130px;min-height:56px}.realm-app .puzzleProgress{color:#937537;margin-top:10px;min-height:30px}.realm-app .loading{position:absolute;inset:0;display:grid;place-items:center;background:#173e37;font-size:24px}.realm-app .rotate{position:absolute;inset:0;z-index:5;background:#173e37f5;display:none;align-items:center;justify-content:center;text-align:center;padding:40px;font-size:23px;line-height:1.8}
 @media(max-height:500px){.realm-app{font-size:14px}.realm-app .top{top:8px;left:max(10px,env(safe-area-inset-left));right:max(10px,env(safe-area-inset-right))}.realm-app .brand{padding:8px 12px}.realm-app h1{font-size:19px;margin:1px 0 3px}.realm-app .eyebrow{font-size:9px}.realm-app .objective{font-size:12px}.realm-app .topnav button{font-size:12px;min-height:42px;padding:7px 10px}.realm-app .joy{width:106px;height:106px;bottom:22px;left:max(20px,env(safe-area-inset-left))}.realm-app .knob{width:46px;height:46px;left:28px;top:28px}.realm-app .actions{bottom:16px;right:max(18px,env(safe-area-inset-right));gap:10px}.realm-app .actions button{width:65px;height:65px;font-size:14px}.realm-app .actions .interact{width:84px;height:84px;font-size:18px}.realm-app .actions .fan{margin-bottom:50px}.realm-app .bottom{font-size:10px;padding:6px 11px;bottom:9px;max-width:38%}.realm-app .card{padding:18px 25px}.realm-app h2{font-size:23px;margin-bottom:8px}.realm-app .body{font-size:16px;line-height:1.55}.realm-app .choices{margin-top:12px}.realm-app .choices button{min-height:46px}.realm-app .context{font-size:13px;bottom:26%}.realm-app .toast{font-size:14px}}
 `;
 this.canvas=this.el('canvas');this.canvas.setAttribute('aria-label','幻界立體探索地圖');const top=this.el('div','top'),brand=this.el('div','brand',null,top);this.el('div','eyebrow','PHANTOM REALM · CHAPTER 01',brand);this.el('h1','','幻界 · 星芽谷',brand);this.objective=this.el('div','objective','',brand);const nav=this.el('div','topnav',null,top);this.button('手帳',()=>this.journal(),nav);this.mapButton=this.button('鳥瞰',()=>{if(!this.world)return;this.world.overview=!this.world.overview;this.world.projection();this.mapButton.textContent=this.world.overview?'跟隨':'鳥瞰';},nav);this.button('暫停',()=>this.pause(),nav);
 const bottom=this.el('div','bottom');this.inventory=this.el('div','inventory','',bottom);this.el('div','','WASD 移動 · E 互動 · Q 引風 · Shift 快走',bottom);this.toast=this.el('div','toast');this.context=this.el('div','context');this.joy=this.el('div','joy');this.knob=this.el('div','knob','',this.joy);this.el('div','joylabel','拖曳移動',this.joy);
 const actions=this.el('div','actions');this.fanButton=this.button('引風',()=>this.useFan(),actions,'fan');this.runButton=this.button('快走',()=>{},actions);this.interactButton=this.button('互動',()=>this.interact(),actions,'interact');this.loading=this.el('div','loading','正在喚醒星芽谷…');this.rotate=this.el('div','rotate','請將手機橫放\n左手移動，右手探索。');this.rotate.style.whiteSpace='pre-line';this.bindInput();this.hud();
 }
 bindInput(){this.on(this.joy,'pointerdown',e=>{if(this.paused||this.joyId!==null)return;e.preventDefault();this.joyId=e.pointerId;this.joy.setPointerCapture(e.pointerId);this.joystick(e);});this.on(this.joy,'pointermove',e=>{if(e.pointerId===this.joyId)this.joystick(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])this.on(this.joy,type,e=>{if(e.pointerId===this.joyId)this.resetJoystick();});this.on(this.runButton,'pointerdown',e=>{if(this.paused)return;this.runId=e.pointerId;this.runButton.setPointerCapture(e.pointerId);this.running=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])this.on(this.runButton,type,()=>{this.running=false;});
 this.on(window,'keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){this.modal?this.close():this.pause();return;}if(this.paused)return;this.keys.add(e.code);if(e.code==='KeyE')this.interact();if(e.code==='KeyQ')this.useFan();});this.on(window,'keyup',e=>this.keys.delete(e.code));this.on(window,'blur',()=>this.pause());this.on(document,'visibilitychange',()=>{if(document.hidden)this.pause();});this.on(window,'resize',()=>this.resize());this.on(this.canvas,'webglcontextlost',e=>{e.preventDefault();this.paused=true;this.clearInput();this.dialog('畫面暫時中斷','請返回遊戲列表再進入，已完成的任務會保留。',[['返回遊戲列表',()=>this.onExit()]]);});}
 joystick(e){const r=this.joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),max=r.width*.34;this.axis=l<6?{x:0,y:0}:{x:dx/Math.max(max,l),y:dy/Math.max(max,l)};this.knob.style.transform=`translate(${this.axis.x*max}px,${this.axis.y*max}px)`;}
 resetJoystick(){this.joyId=null;this.axis={x:0,y:0};this.knob.style.transform='';}
 clearInput(){this.resetJoystick();this.running=false;this.keys.clear();}
 resize(){const r=this.root.getBoundingClientRect();this.world?.resize(r.width,r.height);const portrait=r.height>r.width;this.rotate.style.display=portrait?'flex':'none';if(portrait){this.paused=true;this.clearInput();if(!this.modal&&!this.loading)this.pause();}}
 async start(){try{this.world=new RealmWorld(this.canvas);await this.world.load();if(this.dead){this.world.dispose();return;}this.loading.remove();this.loading=null;this.resize();this.dialog('歡迎來到幻界','這裡的水車停了，星燈也失去光芒。\n找榛果爺爺接下委託，探索拱橋、坡道與高台。\n\n左搖桿移動；右側互動／引風／按住快走。\n手帳有任務與線索，鳥瞰可以查看整座山谷。',[['開始探索',()=>this.close()]]);this.last=performance.now();this.frame=requestAnimationFrame(t=>this.tick(t));}catch(e){if(this.dead)return;this.loading?.remove();this.loading=null;this.dialog('幻界尚未成功載入','請確認已完整覆蓋更新包，並使用支援 WebGL 2 的瀏覽器。\n其他遊戲仍可從列表進入。',[['返回遊戲列表',()=>this.onExit()]]);console.error('Phantom realm load failed',e);}}
 tick(t){if(this.dead)return;const dt=Math.min(.05,(t-this.last)/1000);this.last=t;let axis={x:0,y:0},moving=false;if(!this.paused){axis={x:this.axis.x+(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),y:this.axis.y+(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)};moving=this.journey.move(dt,axis,this.running||this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'));if(this.journey.collect()){this.save();this.notify(`找到螢火蟲！ ${this.journey.found.length} / 3`);this.onSound('correct');}this.hud();}this.world.render(this.journey,this.paused?0:dt,axis,moving);if(this.toastUntil&&t>this.toastUntil)this.toast.style.opacity='0';this.frame=requestAnimationFrame(n=>this.tick(n));}
 hud(){this.objective.textContent=this.journey.objective();this.inventory.textContent=`${this.journey.fan?'引風扇 ✓':'探險背包'} · ${this.journey.gear?'齒輪 ✓':'齒輪 —'} · 螢火 ${this.journey.found.length}/3`;const id=this.journey.nearby();this.context.textContent=id?`E / 互動 · ${SPOTS[id].name}`:'';this.context.style.display=id?'block':'none';this.fanButton.disabled=!this.journey.fan;this.interactButton.textContent=id==='keeper'?'交談':id==='lift'?'搭乘':id==='valve'?'機關':'互動';}
 notify(text){this.toast.textContent=text;this.toast.style.opacity='1';this.toastUntil=performance.now()+4200;}
 save(){try{localStorage.setItem(SAVE,JSON.stringify(this.journey.export()));this.storageOK=true;}catch{this.storageOK=false;this.notify('目前無法保存進度；請先不要關閉此頁。');}}
 result(r){if(r.changed){this.save();this.onSound(r.win?'finish':'correct');}this.hud();if(r.puzzle){this.puzzle();return;}if(r.title)this.dialog(r.title,r.message,[['繼續探索',()=>this.close()]]);else if(r.message)this.notify(r.message);}
 interact(){if(this.paused)return;const id=this.journey.nearby();if(!id){this.notify('靠近居民、機關或水車，再按互動。');return;}this.result(this.journey.act(id));}
 useFan(){if(this.paused||!this.journey.fan)return;this.onSound('hint');if(this.journey.nearby()==='jam')this.result(this.journey.act('jam',true));else this.notify('風把葉子吹起了。找找營地北方纏住齒輪的夢藤。');}
 dialog(title,text,choices){this.paused=true;this.clearInput();this.modal?.remove();this.modal=this.el('div','modal');const card=this.el('div','card',null,this.modal);this.el('h2','',title,card);this.el('div','body',text,card);const buttons=this.el('div','choices',null,card);for(const [label,fn]of choices)this.button(label,fn,buttons);return card;}
 close(){if(this.root.clientHeight>this.root.clientWidth)return;this.modal?.remove();this.modal=null;this.clearInput();this.paused=false;this.last=performance.now();}
 pause(){if(this.dead||this.loading)return;if(this.modal){this.clearInput();return;}this.dialog('在星芽谷歇一會兒',`${this.journey.objective()}\n${this.storageOK?'已完成的任務會自動保存。':'目前無法保存，離開可能遺失進度。'}`,[['繼續',()=>this.close()],['返回遊戲列表',()=>this.onExit()]]);}
 journal(){if(this.loading)return;this.dialog('星芽探險手帳',`目前：${this.journey.objective()}\n\n① 營地交談，取得引風扇。\n② 西岸北方吹開夢藤，找回齒輪。\n③ 過拱橋，從東岸南側木坡道登上高台。\n④ 石碑：葉先醒來，月接住露水，星才亮起。\n⑤ 開閘後可搭滑索回營地，修復水車。\n\n支線：三隻螢火蟲分別在西岸花叢、東岸南端、高台深處。`,[['回到探索',()=>this.close()],['重玩本章',()=>this.dialog('重新探索？','只重設幻界第一章與螢火蟲紀錄，不影響其他遊戲。',[['取消',()=>this.journal()],['確認重玩',()=>{this.journey=new RealmJourney();this.save();this.hud();this.close();}]])]]);}
 puzzle(){this.journey.steps=[];const card=this.dialog('星芽引水閘','石碑刻著：「葉先醒來，月接住露水，星才亮起。」\n依序點亮符印；選錯會熄滅，可以重新嘗試。',[['葉',()=>pick('leaf')],['星',()=>pick('star')],['月',()=>pick('moon')],['先離開',()=>this.close()]]);const status=this.el('div','puzzleProgress','尚未點亮符印',card);const pick=s=>{const r=this.journey.rune(s);status.textContent=r.message;if(r.changed){this.save();this.onSound('correct');this.dialog('水流回來了！',r.message,[['繼續探索',()=>this.close()]]);this.hud();}};}
 dispose(){this.dead=true;cancelAnimationFrame(this.frame);this.abort.abort();this.clearInput();this.world?.dispose();this.root.remove();}
}
