import {SOUVENIR_SOURCES} from './SouvenirSourcesV323.js';
import {souvenirProgress} from './SouvenirProgression.js';
export const SOUVENIR_CATALOG=Object.freeze([
 {id:'first_acorn',name:'初遇橡果',rarity:'common',story:'小小橡果繫上雛菊，記住第一次踏出營地的勇氣。'},
 {id:'wind_seed_bottle',name:'風息種子瓶',rarity:'common',story:'把一縷晨風留在瓶裡，蒲公英的旅行才剛剛開始。'},
 {id:'morning_dew_crystal',name:'晨露星芽晶',rarity:'common',story:'露珠捧著一片嫩芽，映出星芽谷第一道晨光。'},
 {id:'garden_shovel_charm',name:'園藝小鏟吊飾',rarity:'common',story:'鏟柄繫著小黃花，泥土裡也藏著值得珍惜的故事。'},
 {id:'dandelion_bird_feather',name:'浮空雀羽飾',rarity:'common',story:'柔軟的小羽毛，還記得隨著蒲公英一起飄起的日子。'},
 {id:'pumpkin_star_medal',name:'南瓜星章',rarity:'rare',story:'金色星框抱住一顆南瓜，收藏一段勇敢又甜甜的冒險。'}
]);
export function bookSummary(souvenirs={}){return {...souvenirProgress(souvenirs),chapterCount:SOUVENIR_CATALOG.filter(x=>Object.hasOwn(souvenirs||{},x.id)).length};}
const art=new URL('../../assets/phantom-realm/souvenirs-v322/collection-atlas.png',import.meta.url).href;
export class SouvenirBookV322 {
 constructor(host,state,onClose=()=>{}){this.state=state;this.onClose=onClose;this.filter='all';this.selected=0;this.previousFocus=document.activeElement;this.root=document.createElement('div');this.root.className='souvenir-overlay';host.append(this.root);this.root.innerHTML=`<style>
.souvenir-overlay{position:absolute;inset:0;z-index:45;background:#173e37dc;display:grid;place-items:center;padding:16px;color:#62462e;font:600 18px/1.5 "Microsoft JhengHei",sans-serif;touch-action:auto}
.souvenir-overlay *{box-sizing:border-box}.souvenir-overlay .sb-book{width:min(1120px,100%);height:min(750px,96%);background:#fff0cc;border:5px solid #a57742;border-radius:28px;box-shadow:0 20px 60px #102d2799;display:flex;flex-direction:column;padding:22px;overflow:hidden}
.souvenir-overlay .sb-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.souvenir-overlay h2{font-size:28px;margin:0}.souvenir-overlay p{margin:6px 0}.souvenir-overlay .sb-sub{font-size:17px;color:#796347}
.souvenir-overlay.souvenir-overlay button{font:700 18px/1.4 "Microsoft JhengHei",sans-serif;position:static;width:auto;height:auto;min-height:46px;border:2px solid #bd975f;border-radius:14px;background:#fff7e5;color:#63472e;padding:8px 14px;cursor:pointer;transform:none;touch-action:manipulation}
.souvenir-overlay button:focus-visible{outline:3px solid #287d79;outline-offset:2px}.souvenir-overlay .sb-tabs{display:flex;gap:8px;margin:12px 0}.souvenir-overlay button.active{background:#42695b;color:#fff4d8}
.souvenir-overlay .sb-progress{background:#e9d6a8;border-radius:16px;padding:10px 15px}.souvenir-overlay progress{display:block;width:100%;height:15px;accent-color:#568674}
.souvenir-overlay .sb-main{display:grid;grid-template-columns:1fr 280px;gap:18px;flex:1;min-height:0;margin-top:14px}.souvenir-overlay .sb-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;overflow:auto;align-content:start;padding:3px}
.souvenir-overlay.souvenir-overlay .sb-card{display:flex;flex-direction:column;align-items:center;padding:8px;min-width:0;border:3px solid #ceba91}.souvenir-overlay .sb-card.selected{border-color:#548477;box-shadow:0 0 0 2px #548477}.souvenir-overlay .sb-card.rare{border-color:#70aaca}
.souvenir-overlay .sb-art{display:block;width:140px;max-width:100%;aspect-ratio:1;background-size:300% 200%;background-repeat:no-repeat;border-radius:16px}.souvenir-overlay .sb-art.locked{filter:url(#souvenir-silhouette);opacity:.6}.souvenir-overlay .sb-name{font-size:18px}.souvenir-overlay .sb-status{font-size:15px;color:#80684b}
.souvenir-overlay .sb-detail{background:#f5e0b2;border-radius:20px;padding:17px;overflow:auto}.souvenir-overlay .sb-detail .sb-art{width:190px;margin:auto}.souvenir-overlay h3{font-size:23px;margin:12px 0 4px}.souvenir-overlay .sb-empty{grid-column:1/-1;padding:30px;text-align:center}.souvenir-overlay .sb-foot{font-size:16px;margin-top:12px}
@media(max-width:760px){.souvenir-overlay .sb-main{grid-template-columns:1fr 210px}.souvenir-overlay .sb-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.souvenir-overlay .sb-art{width:110px}.souvenir-overlay .sb-book{padding:14px}.souvenir-overlay h2{font-size:23px}}
@media(max-width:520px){.souvenir-overlay{padding:7px}.souvenir-overlay .sb-main{display:block;overflow:auto}.souvenir-overlay .sb-grid{overflow:visible}.souvenir-overlay .sb-detail{margin-top:14px}.souvenir-overlay .sb-head{align-items:start}.souvenir-overlay .sb-sub{font-size:15px}}
@media(max-height:500px){.souvenir-overlay .sb-book{height:100%;padding:10px 16px}.souvenir-overlay .sb-sub,.souvenir-overlay .sb-foot{display:none}.souvenir-overlay .sb-tabs{margin:6px 0}.souvenir-overlay .sb-progress{padding:4px 12px}.souvenir-overlay .sb-art{width:100px}}
</style><svg width="0" height="0" style="position:absolute" aria-hidden="true"><filter id="souvenir-silhouette" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 .38 0 0 0 0 .32 0 0 0 0 .23 -3 -3 -3 0 8.4"/></filter></svg><section class="sb-book" role="dialog" aria-modal="true" aria-label="星芽谷紀念品圖鑑"><header class="sb-head"><div><h2>星芽谷・紀念品圖鑑</h2><p class="sb-sub">把一路上的小小奇蹟，收藏成長大的勇氣。</p></div><button class="sb-close" aria-label="關閉紀念品圖鑑">✕</button></header><div class="sb-progress"></div><nav class="sb-tabs" aria-label="收藏篩選"></nav><div class="sb-main"><div class="sb-grid"></div><aside class="sb-detail" aria-live="polite"></aside></div><p class="sb-foot">每件只記錄一次・普通 1 點／稀有 2 點・永久收藏，不佔背包格子</p></section>`;
 this.root.querySelector('.sb-close').onclick=()=>this.close();for(const [id,label] of [['all','全部'],['owned','已收集'],['missing','未收集']]){const b=document.createElement('button');b.textContent=label;b.dataset.filter=id;b.onclick=()=>{this.filter=id;const next=SOUVENIR_CATALOG.findIndex(x=>id==='all'||(id==='owned')===this.owned(x));if(next>=0)this.selected=next;this.render()};this.root.querySelector('.sb-tabs').append(b);}
 this.key=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();this.close();}if(e.key==='Tab'){const buttons=[...this.root.querySelectorAll('button')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};this.root.addEventListener('keydown',this.key);this.render();this.root.querySelector('.sb-close').focus();
 }
 owned(item){return Object.hasOwn(this.state.souvenirs||{},item.id)}
 image(i,owned){const a=document.createElement('span');a.className='sb-art'+(owned?'':' locked');a.style.backgroundImage=`url("${art}")`;a.style.backgroundPosition=`${i%3*50}% ${Math.floor(i/3)*100}%`;a.setAttribute('aria-hidden','true');return a;}
 render(){const s=bookSummary(this.state.souvenirs);const rewards=['傷害 +1','敏捷 +1','HP 上限 +1','SP 上限 +1'];this.root.querySelector('.sb-progress').innerHTML=`<strong>Lv.${s.level}　下一級 ${s.intoLevel} / ${s.needed} 點</strong><progress max="${s.needed}" value="${s.intoLevel}"></progress><span>本章 ${s.chapterCount} / 6 件　・　升至 Lv.${s.level+1}：${rewards[(s.level-1)%4]}</span>`;
 for(const b of this.root.querySelectorAll('[data-filter]')){b.classList.toggle('active',b.dataset.filter===this.filter);b.setAttribute('aria-pressed',String(b.dataset.filter===this.filter));}
 const grid=this.root.querySelector('.sb-grid');grid.replaceChildren();let count=0;SOUVENIR_CATALOG.forEach((item,i)=>{const owned=this.owned(item);if(this.filter==='owned'&&!owned||this.filter==='missing'&&owned)return;count++;const b=document.createElement('button');b.className='sb-card '+item.rarity+(this.selected===i?' selected':'');b.append(this.image(i,owned));const title=document.createElement('strong');title.className='sb-name';title.textContent=item.name;const status=document.createElement('span');status.className='sb-status';status.textContent=(owned?'已收藏 ✓':'未收集')+' · '+(item.rarity==='rare'?'稀有 2 點':'普通 1 點');b.append(title,status);b.onclick=()=>{this.selected=i;this.render();this.root.querySelector('.sb-card.selected')?.focus()};grid.append(b);});if(!count){const p=document.createElement('p');p.className='sb-empty';p.textContent='這一頁還沒有收藏，留給接下來的冒險。';grid.append(p);}
 const item=SOUVENIR_CATALOG[this.selected],owned=this.owned(item),detail=this.root.querySelector('.sb-detail');detail.replaceChildren(this.image(this.selected,owned));for(const [tag,text] of [['h3',item.name],['p',owned?'已永久收藏':'尚未收集'],['p',item.story],['p','收藏價值：'+(item.rarity==='rare'?'2':'1')+' 點'],['p','取得方式：'+SOUVENIR_SOURCES[item.id]]]){const n=document.createElement(tag);n.textContent=text;detail.append(n);}
 }
 close(){if(!this.root.isConnected)return;this.root.remove();this.previousFocus?.focus();this.onClose();}
}
